### ISSUE TITLE
Outlaw only suggest Slice and Dice as Finisher

### ISSUE THREAD

**Issue by Xenadia** [Sidoine/Ovale#100]
Hello Guys

First of all - we appreciate your hard work you put in this tool!

Sadly like the topic says - there are issues outlaws slice and dice talent. it only suggest slice and dice as a finisher. maybe thats a small code update to fix this for us please?!

thank you again guys!
Xenadia

**Comment by Morl0ck** [comment]
I tried looking into this. I see that the rogue spells for slice and dice are outdated. I'm gonna try to update them and see if it'll make a difference.

**Comment by Sidoine** [comment]
I don't have a level 100 rogue so you have to tell me if the fix is correct

**Comment by Morl0ck** [comment]
The fix was successful @Sidoine
