### ISSUE TITLE
Enhancement Shaman - Crash Lightning

### ISSUE THREAD

**Issue by Sharkenstein** [Sidoine/Ovale#12]
Firstly - thank you very much for maintaining this add-on - we very much appreciate your work. 
Using the add-on with multiple target rotations selected, Crash Lightning never shows for use no matter how many targets are engaged. Are you able to fix this?

Thank You.

**Comment by tressym69** [comment]
Thank you for all of your hard work Sidoine!

To follow up I am also having the same issue.

Version 7.0.8

Talents: Boulderfist, Wind Rush Totem, Lightning Surge Totem, Ancestral Swiftness, Tempest, Crashing Storm, Landslide

Crash Lightning talented (w/ Crashing Storm) should be cast on cool-down but as the first poster stated it is not being recommended in the rotation no matter how many targets are being presented with the default script and even with the default script set to targets > 0

**Comment by Sidoine** [comment]
Fixed in 7.0.9
