### ISSUE TITLE
Need a 7.1 update, stat!  Thanks for all the hard work.

### ISSUE THREAD

**Issue by Oxxinator** [Sidoine/Ovale#138]
Need a 7.1 update, stat!  Thanks for all the hard work.

**Comment by rottingcorpse** [comment]
Message: Interface\AddOns\Ovale\Equipment.lua:352: table index is nil
Time: 10/26/16 10:56:08
Count: 1
Stack: Interface\AddOns\Ovale\Equipment.lua:352: in main chunk

Locals: OVALE = "Ovale"
Ovale = <table> {
 Ovale_CombatStarted = <function> defined @Interface\AddOns\Ovale\Ovale.lua:149
 OneTimeMessage = <function> defined @Interface\AddOns\Ovale\Ovale.lua:391
 EnableModule = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 IterateEmbeds = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 MSG_PREFIX = "Ovale"
 OvaleDebug = <table> {
 }
 defaultModulePrototype = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 UpdateControls = <function> defined @Interface\AddOns\Ovale\Ovale.lua:215
 DisableModule = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 UpdateVisibility = <function> defined @Interface\AddOns\Ovale\Ovale.lua:180
 OvaleData = <table> {
 }
 checkBoxWidget = <table> {
 }
 RegisterMessage = <function> defined @Interface\AddOns\Ovale\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\Ovale\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 ResetControls = <function> defined @Interface\AddOns\Ovale\Ovale.lua:210
 ToggleCheckBox = <function> defined @Interface\AddOns\Ovale\Ovale.lua:311
 OvaleActionBar = <table> {
 }
 Ovale_CombatEnded = <function> defined @Interface\AddOns\Ovale\Ovale.lua:153
 OvaleComboPoints = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\Ovale\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 listWidget = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 OvaleAST = <table> {
 }
 IsChecked = <function> defined @Interface\AddOns\Ovale\Ovale.lua:288
 PrintOneTimeMessages = <function> defined @Interface\AddOns\Ovale\Ovale.lua:402
 OvaleOptions = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\Ovale\Ovale.lua:103
 NewModule = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 GetModule = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 defaultModuleLibraries = <table> {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Ovale.lua:176
 GetCheckBox = <function> defined @Interface\AddOns\Ovale\Ovale.lua:270
 OvaleEquipment = <table> {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Ovale.lua:263
 OvaleCooldown = <table> {
 }
 GetName = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 OvaleCondition = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Ovale\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 OvaleBestAction = <table> {
 }
 name = "Ovale"
 OvaleQueue = <table> {
 }
 playerClass = "WARLOCK"
 orderedModules = <table> {
 }
 Error = <function> defined @Interface\AddOns\Ovale\Ovale.lua:385
 Disable = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 OvaleAura = <table> {
 }
 OvaleTimeSpan = <table> {
 }
 OvalePoolGC = <table> {
 }
 Ovale_OptionChanged = <function> defined @Interface\AddOns\Ovale\Ovale.lua:157
 OvalePool = <table> {
 }
 OvaleProfiler = <table> {
 }
 Print = <function> defined @Interface\AddOns\Ovale\Ovale.lua:376
 L = <table> {
 }
 GetMethod = <function> defined @Interface\AddOns\Ovale\Ovale.lua:411
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Enable = <function> defined @Interface\AddOns\Ovale\libs\AceAddon-3.0\AceAddon-3.0.lua:325
 IsModule = <f

**Comment by Sidoine** [comment]
@rottingcorpse What are you class and spec?

**Comment by rottingcorpse** [comment]
Fixed with update for 7,1, issue was with any class/spec (just different error lines around same array)
