### ISSUE TITLE
Ret Pally 7.1 issue

### ISSUE THREAD

**Issue by Brdrker** [Sidoine/Ovale#140]
My chat window is now getting this error with the release of 7.1:

OvaleCompile: Unknown spell with ID 202270 used in Spell(202270)

or

OvaleCompile: Unknown spell with ID 202270 used in SpellCooldown(202270)

I will see a flurry of 6 messages of this type when I initially log into my character, where I see 4 of the first one and 2 of the second one.

**Comment by cmccad** [comment]
I can confirm.  The Ret talent "Blade of Wrath" got changed in 7.1 and no longer exists as a separate ability or as a DoT.  BoW just resets the CD of Blade of Justice on auto-attack.  As a temporary fix, copying the value from "blade_of_justice" to lines 51 thru 55 in "scripts/ovale_paladin_spells.lua" seems to work, in that there are no errors and BoJ lights up in the UI.

**Comment by Brdrker** [comment]
Looks like this may have been corrected in the latest release. I could make this edit on my prior version but the new one shows edits to the paladin spells lua.
