### ISSUE TITLE
feral druid rotation doesn't include regrowth=<

### ISSUE THREAD

**Issue by kinley83** [Sidoine/Ovale#141]
please please changed the healing touch to regrowth please

**Comment by thompsondj** [comment]
Ashamane's Frenzy seems to be missing as well.

**Comment by Morl0ck** [comment]
Hey Kinley83.

As a workaround, you can edit the ovale_druid_spells.lua file.
find the line that has Define(healing_touch ...
and change it to Define(healing_touch 8936), 8936 being the regrowth spell id.

This is a temporary fix until its fixed in ovale.

**Comment by kevindesmet** [comment]
Hey @kinley83 
The bug exists as simulationcraft hadn't updated their APL to use regrowth instead of healing touch.
This bug has recently been fixed in simc (https://github.com/simulationcraft/simc/commit/6a3f1c64b8b1ddcbdd2ee2810a4d81eb1f553e23) and will be incorporated the next version of Ovale.

**Comment by scotthelm** [comment]
What version is targeted to merge these changes?
