### ISSUE TITLE
[Suggestion] Fire Mage - Marquee Bindings of the Sun King

### ISSUE THREAD

**Issue by warcraftrealist** [Sidoine/Ovale#157]
Just a suggestion, but I noticed ovale knows when Marquee Bindings of the Sun King is equipped and appropriately shows pyroblast hardcasts when the proc hits. Would it be possible for ovale to no longer show the icon if the proc time is less than your cast time?

For example, if your normal pyroblast cast time is 4 seconds, the proc should no longer show when the proc effect is less than 4 seconds. Because now if you hard cast pyroblast the proc effect won't happen.

**Comment by kevindesmet** [comment]
This seems like the good people of simc needs to take that into consideration.
I have opened a ticket, let's wait for their response.
