### ISSUE TITLE
Key Bindings not recognized on Bar 1 after latest update

### ISSUE THREAD

**Issue by hungrypilot** [Sidoine/Ovale#159]
Main bar (Bar 1) keybinds on Bartender 4 are not detected in the latest update.  All other keybinds work fine with the exception of Bar 1.

**Comment by rottingcorpse** [comment]
Please use main menu -> keyboard configuration -> bartender 4 to set keys in order to have them visible.

**Comment by rottingcorpse** [comment]
When keys are defined via /kb, they may/will not be visible on ovale buttons (bartender4 weird magic)

**Comment by hungrypilot** [comment]
This seems to work for now, I'll test it more tomorrow.  One thing extra I had to was remove the spell from that button, and then re-add it for Ovale to recognize it.

**Comment by rottingcorpse** [comment]
That's my pull request merged, so please provide more details if you find
any strange behaviors during the test. Thanks.
