### ISSUE TITLE
Windwalker Monk Rotation

### ISSUE THREAD

**Issue by Hinalover** [Sidoine/Ovale#16]
While talented into Whirling Dragon Punch, the suggester is not taking into account if the spell is ready or not. It is just checking the cooldown. Whirling Dragon Punch is only available when Rising Sun Kick and Fists of Fury are currently on cooldown. However in Ovale, it is asking to use the spell when it is not ready yet.

This is coded as such in Simulationcraft's ready function for the spell so I only need to tell to use Whirling Dragon Punch without any checks in the APL. If you want me to, I can add those checks into the APL for you; but for SimC, they are not needed.

**Comment by Haganemyst** [comment]
Hi, any idea on how this can be done from custom script? I'd appreciate any info on how to correct the Whirling Dragon Punch issue. Thanks.

**Comment by Hinalover** [comment]
Well I know in SimC, the APL check would be
action+/whirling_dragon_punch, if=cooldown.rising_sun_kick.down&cooldown.fists_of_fury.down

But like I mentioned, that conditional is already built into the ready check for the spell.
