### ISSUE TITLE
Windwalker Monk and Katsuo's Eclipse

### ISSUE THREAD

**Issue by Sinesthesia** [Sidoine/Ovale#166]
The default action priority for windwalkers in simc should be taking the cost reduction of Fists of Fury into account, supposedly. I'm no expert on the simc code but it's what I was told, by Babylonius at least so lol. However, Ovale still isn't suggesting to use Fists until I have three chi, even when it's off cd, even though it now only costs one with the boots. I found no way to be able to import the simc priority into ovale and have it function at all to try and fix the one vs three chi. So if it's an issue with the priority, I don't know how to fix it lol

**Comment by kevindesmet** [comment]
Probably not an issue with priority but only with the spell cost in the spell definition (ovale_monk_spells.lua).
Will have a look at it and suggest a fix. I don't have the legendary so it'll be difficult for me to test. I may ask you to test the changes before committing the code.

**Comment by kevindesmet** [comment]
@Sinesthesia could you check out https://github.com/Sidoine/Ovale/pull/169/files and confirm if your issue when you apply those changes?

**Comment by Sinesthesia** [comment]
Yep that did the trick. Sorry for the delay over the weekend lol
