### ISSUE TITLE
Not getting any output while trying to convert from simcraft

### ISSUE THREAD

**Issue by toxicherpes** [Sidoine/Ovale#170]
I'm trying to convert a simcraft rotation to ovale but whenever I put the rotation in the "input" tab nothing happens. It was working a few weeks ago but not at the moment.

Here's some images http://imgur.com/a/P1Uil

**Comment by kevindesmet** [comment]
@toxicherpes can you provide the text you were using in the input box?

**Comment by toxicherpes** [comment]
hunter="Ñova"
level=110
race=human
role=attack
position=ranged_back
professions=tailoring=602/engineering=599
talents=1113111
artifact=55:0:0:0:0:307:1:308:1:309:1:310:1:311:1:312:3:313:3:314:3:315:3:316:3:318:3:319:3:320:3:321:1:322:1:1337:1
spec=marksmanship

# This default action priority list is automatically created based on your character.
# It is a attempt to provide you with a action list that is both simple and practicable,
# while resulting in a meaningful and good simulation. It may not result in the absolutely highest possible dps.
# Feel free to edit, adapt and improve it to your own needs.
# SimulationCraft is always looking for updates and improvements to the default action lists.

# Executed before combat begins. Accepts non-harmful actions only.
actions.precombat=flask,type=flask_of_the_seventh_demon
actions.precombat+=/food,type=nightborne_delicacy_platter
actions.precombat+=/summon_pet
# Snapshot raid buffed stats before combat begins and pre-potting is done.
actions.precombat+=/snapshot_stats
actions.precombat+=/potion,name=prolonged_power,if=active_enemies>2
actions.precombat+=/potion,name=deadly_grace
actions.precombat+=/augmentation,type=defiled
actions.precombat+=/windburst

# Executed every time the actor is available.
actions=auto_shot
actions+=/arcane_torrent,if=focus.deficit>=30&(!talent.sidewinders.enabled|cooldown.sidewinders.charges<2)
actions+=/blood_fury
actions+=/berserking
actions+=/volley,toggle=on
actions+=/auto_shot
actions+=/variable,name=safe_to_build,value=debuff.hunters_mark.down|(buff.trueshot.down&buff.marking_targets.down)
actions+=/variable,name=use_multishot,value=((buff.marking_targets.up|buff.trueshot.up)&spell_targets.multishot>1)|(buff.marking_targets.down&buff.trueshot.down&spell_targets.multishot>2)
actions+=/call_action_list,name=open,if=active_enemies=1&time<=15
actions+=/a_murder_of_crows,if=(target.time_to_die>=cooldown+duration|target.health.pct<20)&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=60&focus+(focus.regen*debuff.hunters_mark.remains)>=60))
actions+=/call_action_list,name=cooldowns
actions+=/call_action_list,name=trueshotaoe,if=(target.time_to_die>=cooldown+duration|target.health.pct<20)&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=60&focus+(focus.regen*debuff.hunters_mark.remains)>=60))
actions+=/black_arrow,if=debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=70&focus+(focus.regen*debuff.hunters_mark.remains)>=70)
actions+=/barrage,if=(target.time_to_20pct>10|target.health.pct<=20|spell_targets>1)&((buff.trueshot.down|(target.health.pct<=20&buff.bullseye.stack<29)|spell_targets>1)&debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&focus+(focus.regen*debuff.vulnerability.remains)>=90&focus+(focus.regen*debuff.hunters_mark.remains)>=90))
actions+=/call_action_list,name=targetdie,if=target.time_to_die<6&active_enemies=1
actions+=/call_action_list,name=patient_sniper,if=talent.patient_sniper.enabled
actions+=/call_action_list,name=non_patient_sniper,if=!talent.patient_sniper.enabled

actions.cooldowns=potion,name=prolonged_power,if=spell_targets.multishot>2&((buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<62)
actions.cooldowns+=/potion,name=deadly_grace,if=(buff.trueshot.react&buff.bloodlust.react)|buff.bullseye.react>=23|target.time_to_die<31
actions.cooldowns+=/trueshot,if=time<5|buff.bloodlust.react|target.time_to_die>=(cooldown+duration)|buff.bullseye.react>25|target.time_to_die<16

actions.non_patient_sniper=windburst
actions.non_patient_sniper+=/piercing_shot,if=focus>=100
actions.non_patient_sniper+=/sentinel,if=debuff.hunters_mark.down&focus>30&buff.trueshot.down
actions.non_patient_sniper+=/sidewinders,if=debuff.vulnerability.remains<gcd&time>6
actions.non_patient_sniper+=/aimed_shot,if=buff.lock_and_load.up&spell_targets.barrage<3
actions.non_patient_sniper+=/marked_shot
actions.non_patient_sniper+=/explosive_shot
actions.non_patient_sniper+=/sidewinders,if=((buff.marking_targets.up|buff.trueshot.up)&focus.deficit>70)|charges_fractional>=1.9
actions.non_patient_sniper+=/arcane_shot,if=!variable.use_multishot&(buff.marking_targets.up|(talent.steady_focus.enabled&(buff.steady_focus.down|buff.steady_focus.remains<2)))
actions.non_patient_sniper+=/multishot,if=variable.use_multishot&(buff.marking_targets.up|(talent.steady_focus.enabled&(buff.steady_focus.down|buff.steady_focus.remains<2)))
actions.non_patient_sniper+=/aimed_shot,if=!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>3
actions.non_patient_sniper+=/arcane_shot,if=!variable.use_multishot
actions.non_patient_sniper+=/multishot,if=variable.use_multishot

actions.open=a_murder_of_crows
actions.open+=/trueshot
actions.open+=/piercing_shot
actions.open+=/explosive_shot
actions.open+=/barrage,if=!talent.patient_sniper.enabled
actions.open+=/arcane_shot,line_cd=16&!talent.patient_sniper.enabled
actions.open+=/sidewinders,if=(buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&focus<80)
actions.open+=/marked_shot
actions.open+=/barrage,if=buff.bloodlust.up
actions.open+=/aimed_shot,if=(buff.lock_and_load.up&execute_time<debuff.vulnerability.remains)|focus>90&!talent.patient_sniper.enabled&talent.trick_shot.enabled
actions.open+=/aimed_shot,if=buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.open+=/black_arrow
actions.open+=/barrage
actions.open+=/arcane_shot
actions.open+=/aimed_shot,if=execute_time<debuff.vulnerability.remains
actions.open+=/sidewinders
actions.open+=/aimed_shot

actions.patient_sniper=marked_shot,cycle_targets=1,if=(talent.sidewinders.enabled&talent.barrage.enabled&spell_targets>2)|debuff.hunters_mark.remains<2|((debuff.vulnerability.up|talent.sidewinders.enabled)&debuff.vulnerability.remains<gcd)
actions.patient_sniper+=/windburst,if=talent.sidewinders.enabled&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>=50))|buff.trueshot.up
actions.patient_sniper+=/sidewinders,if=buff.trueshot.up&((buff.marking_targets.down&buff.trueshot.remains<2)|(charges_fractional>=1.9&(focus.deficit>70|spell_targets>1)))
actions.patient_sniper+=/multishot,if=buff.marking_targets.up&debuff.hunters_mark.down&variable.use_multishot&focus.deficit>2*spell_targets+gcd*focus.regen
actions.patient_sniper+=/aimed_shot,if=buff.lock_and_load.up&buff.trueshot.up&debuff.vulnerability.remains>execute_time
actions.patient_sniper+=/marked_shot,if=buff.trueshot.up&!talent.sidewinders.enabled
actions.patient_sniper+=/arcane_shot,if=buff.trueshot.up
actions.patient_sniper+=/aimed_shot,if=debuff.hunters_mark.down&debuff.vulnerability.remains>execute_time
actions.patient_sniper+=/aimed_shot,if=talent.sidewinders.enabled&debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&(buff.lock_and_load.up|(focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*debuff.vulnerability.remains>=80))&(!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>5|focus>120)
actions.patient_sniper+=/aimed_shot,if=!talent.sidewinders.enabled&debuff.hunters_mark.remains>execute_time&debuff.vulnerability.remains>execute_time&(buff.lock_and_load.up|(buff.trueshot.up&focus>=80)|(buff.trueshot.down&focus+debuff.hunters_mark.remains*focus.regen>=80&focus+focus.regen*debuff.vulnerability.remains>=80))&(!talent.piercing_shot.enabled|cooldown.piercing_shot.remains>5|focus>120)
actions.patient_sniper+=/windburst,if=!talent.sidewinders.enabled&focus>80&(debuff.hunters_mark.down|(debuff.hunters_mark.remains>execute_time&focus+(focus.regen*debuff.hunters_mark.remains)>=50))
actions.patient_sniper+=/marked_shot,if=(talent.sidewinders.enabled&spell_targets>1)|focus.deficit<50|buff.trueshot.up|(buff.marking_targets.up&(!talent.sidewinders.enabled|cooldown.sidewinders.charges_fractional>=1.2))
actions.patient_sniper+=/piercing_shot,if=focus>80
actions.patient_sniper+=/sidewinders,if=variable.safe_to_build&((buff.trueshot.up&focus.deficit>70)|charges_fractional>=1.9)
actions.patient_sniper+=/sidewinders,if=(buff.marking_targets.up&debuff.hunters_mark.down&buff.trueshot.down)|(cooldown.sidewinders.charges_fractional>1&target.time_to_die<11)
actions.patient_sniper+=/arcane_shot,if=variable.safe_to_build&!variable.use_multishot&focus.deficit>5+gcd*focus.regen
actions.patient_sniper+=/multishot,if=variable.safe_to_build&variable.use_multishot&focus.deficit>2*spell_targets+gcd*focus.regen
actions.patient_sniper+=/aimed_shot,if=debuff.vulnerability.down&focus>80&cooldown.windburst.remains>focus.time_to_max

actions.targetdie=marked_shot
actions.targetdie+=/windburst
actions.targetdie+=/aimed_shot,if=debuff.vulnerability.remains>execute_time&target.time_to_die>execute_time
actions.targetdie+=/sidewinders
actions.targetdie+=/aimed_shot
actions.targetdie+=/arcane_shot

actions.trueshotaoe=marked_shot
actions.trueshotaoe+=/barrage,if=!talent.patient_sniper.enabled
actions.trueshotaoe+=/piercing_shot
actions.trueshotaoe+=/explosive_shot
actions.trueshotaoe+=/aimed_shot,if=(!talent.patient_sniper.enabled|talent.trick_shot.enabled)&spell_targets.multishot=2&buff.lock_and_load.up&execute_time<debuff.vulnerability.remains
actions.trueshotaoe+=/multishot

**Comment by toxicherpes** [comment]
umm for some reason the "#" made the text bold in github

**Comment by Reglohpri** [comment]
Hunter is a little Buggy.
There is a Action Named "actions+=/volley,toggle=on" and this would stop the Output. You got an error message in Chat.

Without  "actions+=/volley,toggle=on" the Output is created but Ovale says not Spells found and so on. I tested Prie Shadow, Demon hunter, Mage Arcan, Mage Fire.. these all works fine, but the hunter doesn't work for me.

**Comment by toxicherpes** [comment]
Can anyone else help me with this? It looks like I won't be able to fix this.

**Comment by Reglohpri** [comment]
I doesn't meant, you should fix. The Author or the Owner of this Project should do.

**Comment by toxicherpes** [comment]
Can confirm that BM works but not MM
