### ISSUE TITLE
Demonology Warlock: Felguard pets bugging scripts / Demonic empowerment

### ISSUE THREAD

**Issue by Xychor** [Sidoine/Ovale#174]
Hi,

during script testing on my demo wl, I found two things which seem to work not as intended (using the default script or a freshly imported simc action list):

1. As long as a Felguard is active (applies to "Grimoire: Felguard" too) demonic empowerement ist only suggested if the buff is expiring ON the felguard itself. Other demons states are ignored.

2 "if NotDeDemons(x)" seems to return no valid arguments or is currently ignored by the addon. I tried to replace

#demonic_empowerment,if=wild_imp_no_de>3|prev_gcd.hand_of_guldan
    if NotDeDemons(wild_imp) > 3 or PreviousGCDSpell(hand_of_guldan) Spell(demonic_empowerment)
    #demonic_empowerment,if=dreadstalker_no_de>0|darkglare_no_de>0|doomguard_no_de>0|infernal_no_de>0|service_no_de>0
    if NotDeDemons(dreadstalker) > 0 or NotDeDemons(darkglare) > 0 or NotDeDemons(doomguard) > 0 or NotDeDemons(infernal) > 0 or 0 > 0 Spell(demonic_empowerment)

from the default script with: 

if PreviousGCDSpell(hand_of_guldan) or PreviousGCDSpell(call_dreadstalkers) or PreviousGCDSpell(summon_darkglare) Spell(demonic_empowerment) 

which should work alike in this context (?). 
Again the command seems to be ignored completely as long as a felguard is active. 
If i dismiss my felguard pet DemonicEmpowerment is recommended on a regular basis after (almost) every call_dreadstalkers, summon_darkglare & hand_of_guldan cast, provided that there is no other "demon spawning ability" which currently ranks higher in the execution list. 

hope that helps any further for future releases.

PS: The scripts still contain grimoire_of_sacrifice_talent , which doesn't exist for Demo WLs any more :P

**Comment by thebgpikester** [comment]
I have this issue when importing from SimC, cannot get an import to work, got unexpected symbols error, removed the end of the script and its still just suggesting demonic empowerment
