### ISSUE TITLE
Rogue assassination

### ISSUE THREAD

**Issue by utanipishtim** [Sidoine/Ovale#189]
It appears that envenom is not being properly selected in the assassination rotation for rogue.  Sometimes it appears, but usually the 1st time (and beyond) it should be used, it is not recommended by the add on.

Also, there are missing "|t" in a few lines that should read "...|target..." but instead read "...arget..." in the script:
```
# Based on SimulationCraft profile "Rogue_Assassination_T19P".
# class=rogue
# spec=assassination
# talents=2110111```

**Comment by utanipishtim** [comment]
Also, in the default script, there appears to be missing "|t" in front of a few "argets" where the script should read "...|target..." it instead reads "...arget..." per below:
# Based on SimulationCraft profile "Rogue_Assassination_T19P".
#    class=rogue
#    spec=assassination
#    talents=2110111

Include(ovale_common)
Include(ovale_trinkets_mop)
Include(ovale_trinkets_wod)
Include(ovale_rogue_spells)

AddCheckBox(opt_melee_range L(not_in_melee_range) specialization=assassination)
AddCheckBox(opt_vanish SpellName(vanish) default specialization=assassination)

AddFunction AssassinationUseItemActions
{
    Item(Trinket0Slot usable=1)
    Item(Trinket1Slot usable=1)
}

AddFunction AssassinationGetInMeleeRange
{
    if CheckBoxOn(opt_melee_range) and not target.InRange(kick)
    {
        Spell(shadowstep)
        Texture(misc_arrowlup help=L(not_in_melee_range))
    }
}

### actions.default

AddFunction AssassinationDefaultMainActions
{
    #call_action_list,name=cds
    AssassinationCdsMainActions()

    unless AssassinationCdsMainPostConditions()
    {
        #call_action_list,name=maintain
        AssassinationMaintainMainActions()

        unless AssassinationMaintainMainPostConditions()
        {
            #call_action_list,name=finish,if=(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains>2)&(!dot.rupture.refreshable|(dot.rupture.exsanguinated&dot.rupture.remains>=3.5)arget.time_to_die-dot.rupture.remains<=4)&active_dot.rupture>=spell_targets.rupture
            if { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() AssassinationFinishMainActions()

            unless { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishMainPostConditions()
            {
                #call_action_list,name=build,if=(combo_points.deficit>0|energy.time_to_max<1)
                if ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 AssassinationBuildMainActions()
            }
        }
    }
}

AddFunction AssassinationDefaultMainPostConditions
{
    AssassinationCdsMainPostConditions() or AssassinationMaintainMainPostConditions() or { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishMainPostConditions() or { ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 } and AssassinationBuildMainPostConditions()
}

AddFunction AssassinationDefaultShortCdActions
{
    #call_action_list,name=cds
    AssassinationCdsShortCdActions()

    unless AssassinationCdsShortCdPostConditions()
    {
        #call_action_list,name=maintain
        AssassinationMaintainShortCdActions()

        unless AssassinationMaintainShortCdPostConditions()
        {
            #call_action_list,name=finish,if=(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains>2)&(!dot.rupture.refreshable|(dot.rupture.exsanguinated&dot.rupture.remains>=3.5)arget.time_to_die-dot.rupture.remains<=4)&active_dot.rupture>=spell_targets.rupture
            if { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() AssassinationFinishShortCdActions()

            unless { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishShortCdPostConditions()
            {
                #call_action_list,name=build,if=(combo_points.deficit>0|energy.time_to_max<1)
                if ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 AssassinationBuildShortCdActions()
            }
        }
    }
}

AddFunction AssassinationDefaultShortCdPostConditions
{
    AssassinationCdsShortCdPostConditions() or AssassinationMaintainShortCdPostConditions() or { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishShortCdPostConditions() or { ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 } and AssassinationBuildShortCdPostConditions()
}

AddFunction AssassinationDefaultCdActions
{
    #call_action_list,name=cds
    AssassinationCdsCdActions()

    unless AssassinationCdsCdPostConditions()
    {
        #call_action_list,name=maintain
        AssassinationMaintainCdActions()

        unless AssassinationMaintainCdPostConditions()
        {
            #call_action_list,name=finish,if=(!talent.exsanguinate.enabled|cooldown.exsanguinate.remains>2)&(!dot.rupture.refreshable|(dot.rupture.exsanguinated&dot.rupture.remains>=3.5)arget.time_to_die-dot.rupture.remains<=4)&active_dot.rupture>=spell_targets.rupture
            if { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() AssassinationFinishCdActions()

            unless { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishCdPostConditions()
            {
                #call_action_list,name=build,if=(combo_points.deficit>0|energy.time_to_max<1)
                if ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 AssassinationBuildCdActions()
            }
        }
    }
}

AddFunction AssassinationDefaultCdPostConditions
{
    AssassinationCdsCdPostConditions() or AssassinationMaintainCdPostConditions() or { not Talent(exsanguinate_talent) or SpellCooldown(exsanguinate) > 2 } and { not target.DebuffRefreshable(rupture_debuff) or target.DebuffRemaining(rupture_debuff_exsanguinated) and target.DebuffRemaining(rupture_debuff) >= 3.5 or target.TimeToDie() - target.DebuffRemaining(rupture_debuff) <= 4 } and DebuffCountOnAny(rupture_debuff) >= Enemies() and AssassinationFinishCdPostConditions() or { ComboPointsDeficit() > 0 or TimeToMaxEnergy() < 1 } and AssassinationBuildCdPostConditions()
}

### actions.build

AddFunction AssassinationBuildMainActions
{
    #hemorrhage,if=refreshable
    if target.Refreshable(hemorrhage_debuff) Spell(hemorrhage)
    #hemorrhage,cycle_targets=1,if=refreshable&dot.rupture.ticking&spell_targets.fan_of_knives<=3
    if target.Refreshable(hemorrhage_debuff) and target.DebuffPresent(rupture_debuff) and Enemies() <= 3 Spell(hemorrhage)
    #fan_of_knives,if=spell_targets>=3|buff.the_dreadlords_deceit.stack>=29
    if Enemies() >= 3 or BuffStacks(the_dreadlords_deceit_buff) >= 29 Spell(fan_of_knives)
    #mutilate,cycle_targets=1,if=(!talent.agonizing_poison.enabled&dot.deadly_poison_dot.refreshable)|(talent.agonizing_poison.enabled&debuff.agonizing_poison.remains<debuff.agonizing_poison.duration*0.3)|(set_bonus.tier19_2pc=1&dot.mutilated_flesh.refreshable)
    if not Talent(agonizing_poison_talent) and target.DebuffRefreshable(deadly_poison_dot_debuff) or Talent(agonizing_poison_talent) and target.DebuffRemaining(agonizing_poison_debuff) < BaseDuration(agonizing_poison_debuff) * 0.3 or ArmorSetBonus(T19 2) == 1 and target.DebuffRefreshable(mutilated_flesh_debuff) Spell(mutilate)
    #mutilate
    Spell(mutilate)
}

AddFunction AssassinationBuildMainPostConditions
{
}

AddFunction AssassinationBuildShortCdActions
{
}

AddFunction AssassinationBuildShortCdPostConditions
{
    target.Refreshable(hemorrhage_debuff) and Spell(hemorrhage) or target.Refreshable(hemorrhage_debuff) and target.DebuffPresent(rupture_debuff) and Enemies() <= 3 and Spell(hemorrhage) or { Enemies() >= 3 or BuffStacks(the_dreadlords_deceit_buff) >= 29 } and Spell(fan_of_knives) or { not Talent(agonizing_poison_talent) and target.DebuffRefreshable(deadly_poison_dot_debuff) or Talent(agonizing_poison_talent) and target.DebuffRemaining(agonizing_poison_debuff) < BaseDuration(agonizing_poison_debuff) * 0.3 or ArmorSetBonus(T19 2) == 1 and target.DebuffRefreshable(mutilated_flesh_debuff) } and Spell(mutilate) or Spell(mutilate)
}

AddFunction AssassinationBuildCdActions
{
}

AddFunction AssassinationBuildCdPostConditions
{
    target.Refreshable(hemorrhage_debuff) and Spell(hemorrhage) or target.Refreshable(hemorrhage_debuff) and target.DebuffPresent(rupture_debuff) and Enemies() <= 3 and Spell(hemorrhage) or { Enemies() >= 3 or BuffStacks(the_dreadlords_deceit_buff) >= 29 } and Spell(fan_of_knives) or { not Talent(agonizing_poison_talent) and target.DebuffRefreshable(deadly_poison_dot_debuff) or Talent(agonizing_poison_talent) and target.DebuffRemaining(agonizing_poison_debuff) < BaseDuration(agonizing_poison_debuff) * 0.3 or ArmorSetBonus(T19 2) == 1 and target.DebuffRefreshable(mutilated_flesh_debuff) } and Spell(mutilate) or Spell(mutilate)
}

### actions.cds

AddFunction AssassinationCdsMainActions
{
}

AddFunction AssassinationCdsMainPostConditions
{
}

AddFunction AssassinationCdsShortCdActions
{
    #marked_for_death,target_if=min:target.time_to_die,if=target.time_to_die<combo_points.deficit|combo_points.deficit>=5
    if target.TimeToDie() < ComboPointsDeficit() or ComboPointsDeficit() >= 5 Spell(marked_for_death)
    #vanish,if=talent.nightstalker.enabled&combo_points>=cp_max_spend&((talent.exsanguinate.enabled&cooldown.exsanguinate.remains<1&(dot.rupture.tickingime>10))|(!talent.exsanguinate.enabled&dot.rupture.refreshable))
    if Talent(nightstalker_talent) and ComboPoints() >= MaxComboPoints() and { Talent(exsanguinate_talent) and SpellCooldown(exsanguinate) < 1 and { target.DebuffPresent(rupture_debuff) or TimeInCombat() > 10 } or not Talent(exsanguinate_talent) and target.DebuffRefreshable(rupture_debuff) } and CheckBoxOn(opt_vanish) Spell(vanish)
    #vanish,if=talent.subterfuge.enabled&dot.garrote.refreshable&((spell_targets.fan_of_knives<=3&combo_points.deficit>=1+spell_targets.fan_of_knives)|(spell_targets.fan_of_knives>=4&combo_points.deficit>=4))
    if Talent(subterfuge_talent) and target.DebuffRefreshable(garrote_debuff) and { Enemies() <= 3 and ComboPointsDeficit() >= 1 + Enemies() or Enemies() >= 4 and ComboPointsDeficit() >= 4 } and CheckBoxOn(opt_vanish) Spell(vanish)
    #vanish,if=talent.shadow_focus.enabled&energy.time_to_max>=2&combo_points.deficit>=4
    if Talent(shadow_focus_talent) and TimeToMaxEnergy() >= 2 and ComboPointsDeficit() >= 4 and CheckBoxOn(opt_vanish) Spell(vanish)
    #exsanguinate,if=prev_gcd.rupture&dot.rupture.remains>4+4*cp_max_spend
    if PreviousGCDSpell(rupture) and target.DebuffRemaining(rupture_debuff) > 4 + 4 * MaxComboPoints() Spell(exsanguinate)
}

AddFunction AssassinationCdsShortCdPostConditions
{
}

AddFunction AssassinationCdsCdActions
{
    #potion,name=old_war,if=buff.bloodlust.reactarget.time_to_die<=25|debuff.vendetta.up
    #use_item,slot=trinket1,if=buff.bloodlust.reactarget.time_to_die<=20|debuff.vendetta.up
    if BuffPresent(burst_haste_buff any=1) or target.TimeToDie() <= 20 or target.DebuffPresent(vendetta_debuff) AssassinationUseItemActions()
    #use_item,slot=trinket2,if=buff.bloodlust.reactarget.time_to_die<=20|debuff.vendetta.up
    if BuffPresent(burst_haste_buff any=1) or target.TimeToDie() <= 20 or target.DebuffPresent(vendetta_debuff) AssassinationUseItemActions()
    #blood_fury,if=debuff.vendetta.up
    if target.DebuffPresent(vendetta_debuff) Spell(blood_fury_ap)
    #berserking,if=debuff.vendetta.up
    if target.DebuffPresent(vendetta_debuff) Spell(berserking)
    #arcane_torrent,if=debuff.vendetta.up&energy.deficit>50
    if target.DebuffPresent(vendetta_debuff) and EnergyDeficit() > 50 Spell(arcane_torrent_energy)
    #vendetta,if=talent.exsanguinate.enabled&cooldown.exsanguinate.remains<5&dot.rupture.ticking
    if Talent(exsanguinate_talent) and SpellCooldown(exsanguinate) < 5 and target.DebuffPresent(rupture_debuff) Spell(vendetta)
    #vendetta,if=!talent.exsanguinate.enabled&(!artifact.urge_to_kill.enabled|energy.deficit>=70)
    if not Talent(exsanguinate_talent) and { not HasArtifactTrait(urge_to_kill) or EnergyDeficit() >= 70 } Spell(vendetta)
}

AddFunction AssassinationCdsCdPostConditions
{
    PreviousGCDSpell(rupture) and target.DebuffRemaining(rupture_debuff) > 4 + 4 * MaxComboPoints() and Spell(exsanguinate)
}

### actions.finish

AddFunction AssassinationFinishMainActions
{
    #death_from_above,if=combo_points>=cp_max_spend
    if ComboPoints() >= MaxComboPoints() Spell(death_from_above)
    #envenom,if=combo_points>=cp_max_spend-talent.master_poisoner.enabled|(talent.elaborate_planning.enabled&combo_points>=3+!talent.exsanguinate.enabled&buff.elaborate_planning.remains<2)
    if ComboPoints() >= MaxComboPoints() - TalentPoints(master_poisoner_talent) or Talent(elaborate_planning_talent) and ComboPoints() >= 3 + Talent(exsanguinate_talent no) and BuffRemaining(elaborate_planning_buff) < 2 Spell(envenom)
}

AddFunction AssassinationFinishMainPostConditions
{
}

AddFunction AssassinationFinishShortCdActions
{
}

AddFunction AssassinationFinishShortCdPostConditions
{
    ComboPoints() >= MaxComboPoints() and Spell(death_from_above) or { ComboPoints() >= MaxComboPoints() - TalentPoints(master_poisoner_talent) or Talent(elaborate_planning_talent) and ComboPoints() >= 3 + Talent(exsanguinate_talent no) and BuffRemaining(elaborate_planning_buff) < 2 } and Spell(envenom)
}

AddFunction AssassinationFinishCdActions
{
}

AddFunction AssassinationFinishCdPostConditions
{
    ComboPoints() >= MaxComboPoints() and Spell(death_from_above) or { ComboPoints() >= MaxComboPoints() - TalentPoints(master_poisoner_talent) or Talent(elaborate_planning_talent) and ComboPoints() >= 3 + Talent(exsanguinate_talent no) and BuffRemaining(elaborate_planning_buff) < 2 } and Spell(envenom)
}

### actions.maintain

AddFunction AssassinationMaintainMainActions
{
    #rupture,if=(talent.nightstalker.enabled&stealthed.rogue)|(talent.exsanguinate.enabled&((combo_points>=cp_max_spend&cooldown.exsanguinate.remains<1)|(!ticking&(time>10|combo_points>=2+artifact.urge_to_kill.enabled))))
    if Talent(nightstalker_talent) and Stealthed() or Talent(exsanguinate_talent) and { ComboPoints() >= MaxComboPoints() and SpellCooldown(exsanguinate) < 1 or not target.DebuffPresent(rupture_debuff) and { TimeInCombat() > 10 or ComboPoints() >= 2 + HasArtifactTrait(urge_to_kill) } } Spell(rupture)
    #rupture,cycle_targets=1,if=combo_points>=cp_max_spend-talent.exsanguinate.enabled&refreshable&(!exsanguinatedemains<=1.5)&target.time_to_die-remains>4
    if ComboPoints() >= MaxComboPoints() - TalentPoints(exsanguinate_talent) and target.Refreshable(rupture_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(rupture_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(rupture_debuff) > 4 Spell(rupture)
    #kingsbane,if=(talent.exsanguinate.enabled&dot.rupture.exsanguinated)|(!talent.exsanguinate.enabled&(debuff.vendetta.up|cooldown.vendetta.remains>10))
    if Talent(exsanguinate_talent) and target.DebuffRemaining(rupture_debuff_exsanguinated) or not Talent(exsanguinate_talent) and { target.DebuffPresent(vendetta_debuff) or SpellCooldown(vendetta) > 10 } Spell(kingsbane)
    #pool_resource,for_next=1
    #garrote,cycle_targets=1,if=refreshable&(!exsanguinatedemains<=1.5)&target.time_to_die-remains>4
    if target.Refreshable(garrote_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(garrote_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(garrote_debuff) > 4 Spell(garrote)
}

AddFunction AssassinationMaintainMainPostConditions
{
}

AddFunction AssassinationMaintainShortCdActions
{
}

AddFunction AssassinationMaintainShortCdPostConditions
{
    { Talent(nightstalker_talent) and Stealthed() or Talent(exsanguinate_talent) and { ComboPoints() >= MaxComboPoints() and SpellCooldown(exsanguinate) < 1 or not target.DebuffPresent(rupture_debuff) and { TimeInCombat() > 10 or ComboPoints() >= 2 + HasArtifactTrait(urge_to_kill) } } } and Spell(rupture) or ComboPoints() >= MaxComboPoints() - TalentPoints(exsanguinate_talent) and target.Refreshable(rupture_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(rupture_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(rupture_debuff) > 4 and Spell(rupture) or { Talent(exsanguinate_talent) and target.DebuffRemaining(rupture_debuff_exsanguinated) or not Talent(exsanguinate_talent) and { target.DebuffPresent(vendetta_debuff) or SpellCooldown(vendetta) > 10 } } and Spell(kingsbane) or target.Refreshable(garrote_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(garrote_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(garrote_debuff) > 4 and Spell(garrote)
}

AddFunction AssassinationMaintainCdActions
{
}

AddFunction AssassinationMaintainCdPostConditions
{
    { Talent(nightstalker_talent) and Stealthed() or Talent(exsanguinate_talent) and { ComboPoints() >= MaxComboPoints() and SpellCooldown(exsanguinate) < 1 or not target.DebuffPresent(rupture_debuff) and { TimeInCombat() > 10 or ComboPoints() >= 2 + HasArtifactTrait(urge_to_kill) } } } and Spell(rupture) or ComboPoints() >= MaxComboPoints() - TalentPoints(exsanguinate_talent) and target.Refreshable(rupture_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(rupture_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(rupture_debuff) > 4 and Spell(rupture) or { Talent(exsanguinate_talent) and target.DebuffRemaining(rupture_debuff_exsanguinated) or not Talent(exsanguinate_talent) and { target.DebuffPresent(vendetta_debuff) or SpellCooldown(vendetta) > 10 } } and Spell(kingsbane) or target.Refreshable(garrote_debuff) and { not target.DebuffPresent(exsanguinated) or target.DebuffRemaining(garrote_debuff) <= 1.5 } and target.TimeToDie() - target.DebuffRemaining(garrote_debuff) > 4 and Spell(garrote)
}

### actions.precombat

AddFunction AssassinationPrecombatMainActions
{
    #flask,name=flask_of_the_seventh_demon
    #augmentation,name=defiled
    Spell(augmentation)
    #food,name=seedbattered_fish_plate
    #snapshot_stats
    #apply_poison
    #stealth
    Spell(stealth)
}

AddFunction AssassinationPrecombatMainPostConditions
{
}

AddFunction AssassinationPrecombatShortCdActions
{
    unless Spell(augmentation) or Spell(stealth)
    {
        #potion,name=old_war
        #marked_for_death,if=raid_event.adds.in>40
        if 600 > 40 Spell(marked_for_death)
    }
}

AddFunction AssassinationPrecombatShortCdPostConditions
{
    Spell(augmentation) or Spell(stealth)
}

AddFunction AssassinationPrecombatCdActions
{
}

AddFunction AssassinationPrecombatCdPostConditions
{
    Spell(augmentation) or Spell(stealth)
}

### Assassination icons.

AddCheckBox(opt_rogue_assassination_aoe L(AOE) default specialization=assassination)

AddIcon checkbox=!opt_rogue_assassination_aoe enemies=1 help=shortcd specialization=assassination
{
    if not InCombat() AssassinationPrecombatShortCdActions()
    unless not InCombat() and AssassinationPrecombatShortCdPostConditions()
    {
        AssassinationDefaultShortCdActions()
    }
}

AddIcon checkbox=opt_rogue_assassination_aoe help=shortcd specialization=assassination
{
    if not InCombat() AssassinationPrecombatShortCdActions()
    unless not InCombat() and AssassinationPrecombatShortCdPostConditions()
    {
        AssassinationDefaultShortCdActions()
    }
}

AddIcon enemies=1 help=main specialization=assassination
{
    if not InCombat() AssassinationPrecombatMainActions()
    unless not InCombat() and AssassinationPrecombatMainPostConditions()
    {
        AssassinationDefaultMainActions()
    }
}

AddIcon checkbox=opt_rogue_assassination_aoe help=aoe specialization=assassination
{
    if not InCombat() AssassinationPrecombatMainActions()
    unless not InCombat() and AssassinationPrecombatMainPostConditions()
    {
        AssassinationDefaultMainActions()
    }
}

AddIcon checkbox=!opt_rogue_assassination_aoe enemies=1 help=cd specialization=assassination
{
    if not InCombat() AssassinationPrecombatCdActions()
    unless not InCombat() and AssassinationPrecombatCdPostConditions()
    {
        AssassinationDefaultCdActions()
    }
}

AddIcon checkbox=opt_rogue_assassination_aoe help=cd specialization=assassination
{
    if not InCombat() AssassinationPrecombatCdActions()
    unless not InCombat() and AssassinationPrecombatCdPostConditions()
    {
        AssassinationDefaultCdActions()
    }
}

### Required symbols
# agonizing_poison_debuff
# agonizing_poison_talent
# arcane_torrent_energy
# augmentation
# berserking
# blood_fury_ap
# deadly_poison_dot_debuff
# death_from_above
# elaborate_planning_buff
# elaborate_planning_talent
# envenom
# exsanguinate
# exsanguinate_talent
# fan_of_knives
# garrote
# garrote_debuff
# hemorrhage
# hemorrhage_debuff
# kick
# kingsbane
# marked_for_death
# master_poisoner_talent
# mutilate
# mutilated_flesh_debuff
# nightstalker_talent
# rupture
# rupture_debuff
# shadow_focus_talent
# shadowstep
# stealth
# subterfuge_talent
# the_dreadlords_deceit_buff
# urge_to_kill
# vanish
# vendetta
# vendetta_debuff

**Comment by cisox** [comment]
@utanipishtim The reason it enlarged the text is that GitHub uses Markdown for text formatting and the `#` character is used for headers. You can add three backtick \``` characters above and below whatever you want to paste and it will be formatted without Markdown.

```
# Based on SimulationCraft profile "Rogue_Assassination_T19P".
# class=rogue
# spec=assassination
# talents=2110111
```

**Comment by utanipishtim** [comment]
Thank you cisox!
Also, Ovale version 7.1.3.1 appears to be the last version that does NOT have the issue with envenom.

**Comment by redrush85** [comment]
Confirmed. Envenom still doesn't work properly
