### ISSUE TITLE
Very High number of Lua Errors in WoW with Ovale Spell Priority 7.0.6

### ISSUE THREAD

**Issue by bhaskie357** [Sidoine/Ovale#19]
Message: Interface\AddOns\Ovale\libs\AceDBOptions-3.0\AceDBOptions-3.0.lua:357: unfinished string near '"'
Time: 08/04/16 11:37:43
Count: 1
Stack: 
Locals: 

HUGE number of the following increments:

Message: Interface\AddOns\Ovale\Frame.lua:172: attempt to call method 'UnitGUID' (a nil value)
Time: 08/04/16 11:38:27
Count: 1664
Stack: Interface\AddOns\Ovale\Frame.lua:172: in function `OnUpdate'
Interface\AddOns\Ovale\Frame.lua:89: in function <Interface\AddOns\Ovale\Frame.lua:88>

Locals: self = <table> {
 OnRelease = <function> defined @Interface\AddOns\Ovale\Frame.lua:104
 GetScore = <function> defined @Interface\AddOns\Ovale\Frame.lua:136
 OnAcquire = <function> defined @Interface\AddOns\Ovale\Frame.lua:100
 AceGUIWidgetVersion = 7
 LayoutFunc = <function> defined @Interface\AddOns\Recount\Libs\AceGUI-3.0\AceGUI-3.0.lua:629
 userdata = <table> {
 }
 base = <table> {
 }
 frame = <unnamed> {
 }
 UpdateActionIcon = <function> defined @Interface\AddOns\Ovale\Frame.lua:235
 OnUpdate = <function> defined @Interface\AddOns\Ovale\Frame.lua:165
 Hide = <function> defined @Interface\AddOns\Ovale\Frame.lua:92
 children = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Frame.lua:331
 LayoutFinished = <function> defined @Interface\AddOns\Ovale\Frame.lua:128
 actions = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Ovale\Frame.lua:337
 Show = <function> defined @Interface\AddOns\Ovale\Frame.lua:96
 content = <unnamed> {
 }
 events = <table> {
 }
 updateFrame = OvaleUpdateFrame {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Frame.lua:59
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = 1.#INF
}
elapsed = 0.031000001356006
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 baseName = "Ovale"
 Enable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 moduleName = "OvaleGUID"
 EnableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 UnregisterAllEvents = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 defaultModuleLibraries = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
 UnregisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 SetEnabledState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 RegisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 enabledState = true
 SetDefaultModuleState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 RegisterEvent = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterAllMessages = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 GetName = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 IterateModules = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 name = "Ovale_OvaleGUID"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 IsEnabled = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 UnregisterEvent = <function> defined @Interface\Ad

**Comment by g0shua** [comment]
Same here, mine are similar:

`710x Ovale\Frame.lua:185: attempt to call method 'EvaluateScript' (a nil value)
Ovale\Frame.lua:185: in function `OnUpdate'
Ovale\Frame.lua:89: in function <Ovale\Frame.lua:88>

Locals:
self = <table> {
 OnRelease = <function> defined @Ovale\Frame.lua:104
 AceGUIWidgetVersion = 7
 GetScore = <function> defined @Ovale\Frame.lua:136
 OnAcquire = <function> defined @Ovale\Frame.lua:100
 LayoutFunc = <function> defined @Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:629
 base = <table> {
 }
 userdata = <table> {
 }
 frame = <unnamed> {
 }
 children = <table> {
 }
 UpdateActionIcon = <function> defined @Ovale\Frame.lua:235
 OnUpdate = <function> defined @Ovale\Frame.lua:165
 Hide = <function> defined @Ovale\Frame.lua:92
 actions = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 UpdateFrame = <function> defined @Ovale\Frame.lua:331
 LayoutFinished = <function> defined @Ovale\Frame.lua:128
 skinGroup = <table> {
 }
 UpdateIcons = <function> defined @Ovale\Frame.lua:337
 Show = <function> defined @Ovale\Frame.lua:96
 content = <unnamed> {
 }
 events = <table> {
 }
 updateFrame = OvaleUpdateFrame {
 }
 ToggleOptions = <function> defined @Ovale\Frame.lua:59
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = 1.#INF
}
elapsed = 0.0010000000474975
guid = nil
refresh = "Player-64-0046CE00"
state = <table> {
 Log = <function> defined @Ovale\State.lua:205
 isInitialized = true
 GetSpellInfoProperty = <function> defined @Ovale\Data.lua:480
 lastEnable = <table> {
 }
 isState = true
 GetStateDuration = <function> defined @Ovale\State.lua:179
 GetMethod = <function> defined @Ovale\Ovale.lua:411
 variable = <table> {
 }
 GetState = <function> defined @Ovale\State.lua:171
 futureLastEnable = <table> {
 }
 PutState = <function> defined @Ovale\State.lua:185
 CheckRequirements = <function> defined @Ovale\Data.lua:370
 defaultTarget = "target"
 Initialize = <function> defined @Ovale\State.lua:159
 Reset = <function> defined @Ovale\State.lua:166
 CheckSpellInfo = <function> defined @Ovale\Data.lua:458
 futureVariable = <table> {
 }
 CheckSpellAuraData = <function> defined @Ovale\Data.lua:410
}
(*temporary) = nil
(*temporary) = <table> {
 baseName = "Ovale"
 SetDefaultModuleLibraries = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 DebugTimestamp = <function> defined @Ovale\Debug.lua:180
 Debug = <function> defined @Ovale\Debug.lua:169
 Enable = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 moduleName = "OvaleCompile"
 EnableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 UnregisterAllEvents = <function> defined @SharedMedia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 defaultModuleLibraries = <table> {
 }
 SendMessage = <function> defined @SharedMedia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 UnregisterMessage = <function> defined @SharedMedia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 SetEnabledState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 RegisterMessage = <function> defined @SharedMedia\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 enabledState = true
 SetDefaultModuleState = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 RegisterEvent = <function> defined @Interfac`

**Comment by ShmooDude** [comment]
Figured it out.  None of the libraries are included when you download it from github.  Go copy them from the curse version of ovale and it works fine.

Though I left a line of debug code in my fix so you might end up with some numbers in your chat.  Looks like sidoine merged my fix for that though so if you dl the latest master it should be fine.).

**Comment by g0shua** [comment]
I thought it was a library issue too but the weird thing is that I updated via Curse Client and am getting this. I might have updated from an alpha release. I'll reinstall it when I get home.

**Comment by bhaskie357** [comment]
I originally updated from Curse as well.  I just tried updating from Curse again to ver. 7.0.8 and an now getting the following Lua Error:

Message: Interface\AddOns\Ovale\Frame.lua:356: attempt to call method 'GetIconNodes' (a nil value)
Time: 08/04/16 15:07:34
Count: 1
Stack: Interface\AddOns\Ovale\Frame.lua:356: in function `UpdateIcons'
Interface\AddOns\Ovale\Ovale.lua:265: in function `UpdateFrame'
Interface\AddOns\Ovale\Ovale.lua:125: in function <Interface\AddOns\Ovale\Ovale.lua:116>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: self = <table> {
 OnRelease = <function> defined @Interface\AddOns\Ovale\Frame.lua:104
 GetScore = <function> defined @Interface\AddOns\Ovale\Frame.lua:136
 OnAcquire = <function> defined @Interface\AddOns\Ovale\Frame.lua:100
 AceGUIWidgetVersion = 7
 LayoutFunc = <function> defined @Interface\AddOns\Recount\Libs\AceGUI-3.0\AceGUI-3.0.lua:629
 userdata = <table> {
 }
 base = <table> {
 }
 frame = <unnamed> {
 }
 UpdateActionIcon = <function> defined @Interface\AddOns\Ovale\Frame.lua:235
 OnUpdate = <function> defined @Interface\AddOns\Ovale\Frame.lua:165
 Hide = <function> defined @Interface\AddOns\Ovale\Frame.lua:92
 children = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Frame.lua:331
 LayoutFinished = <function> defined @Interface\AddOns\Ovale\Frame.lua:128
 actions = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Ovale\Frame.lua:337
 Show = <function> defined @Interface\AddOns\Ovale\Frame.lua:96
 content = <unnamed> {
 }
 events = <table> {
 }
 updateFrame = OvaleUpdateFrame {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Frame.lua:59
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = 1.#INF
}
profile = <table> {
 apparence = <table> {
 }
 source = "Ovale"
 list = <table> {
 }
 check = <table> {
 }
 standaloneOptions = false
 showHiddenScripts = false
 code = ""
}
left = 0
maxHeight = 0
maxWidth = 0
top = 0
BARRE = 8
margin = 4
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 baseName = "Ovale"
 Enable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 moduleName = "OvaleCompile"
 EnableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 UnregisterAllEvents = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 defaultModuleLibraries = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
 UnregisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 SetEnabledState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 RegisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 enabledState = true
 SetDefaultModuleState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-

Once I close, I get fast, incrementing errors:

Message: Interface\AddOns\Ovale\Frame.lua:172: attempt to call method 'UnitGUID' (a nil value)
Time: 08/04/16 15:09:14
Count: 3755
Stack: Interface\AddOns\Ovale\Frame.lua:172: in function `OnUpdate'
Interface\AddOns\Ovale\Frame.lua:89: in function <Interface\AddOns\Ovale\Frame.lua:88>

Locals: self = <table> {
 OnRelease = <function> defined @Interface\AddOns\Ovale\Frame.lua:104
 GetScore = <function> defined @Interface\AddOns\Ovale\Frame.lua:136
 OnAcquire = <function> defined @Interface\AddOns\Ovale\Frame.lua:100
 AceGUIWidgetVersion = 7
 LayoutFunc = <function> defined @Interface\AddOns\Recount\Libs\AceGUI-3.0\AceGUI-3.0.lua:629
 userdata = <table> {
 }
 base = <table> {
 }
 frame = <unnamed> {
 }
 UpdateActionIcon = <function> defined @Interface\AddOns\Ovale\Frame.lua:235
 OnUpdate = <function> defined @Interface\AddOns\Ovale\Frame.lua:165
 Hide = <function> defined @Interface\AddOns\Ovale\Frame.lua:92
 children = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Frame.lua:331
 LayoutFinished = <function> defined @Interface\AddOns\Ovale\Frame.lua:128
 actions = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Ovale\Frame.lua:337
 Show = <function> defined @Interface\AddOns\Ovale\Frame.lua:96
 content = <unnamed> {
 }
 events = <table> {
 }
 updateFrame = OvaleUpdateFrame {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Frame.lua:59
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = 1.#INF
}
elapsed = 0.015000000596046
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 baseName = "Ovale"
 Enable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 moduleName = "OvaleGUID"
 EnableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 UnregisterAllEvents = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 defaultModuleLibraries = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
 UnregisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 SetEnabledState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 RegisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 enabledState = true
 SetDefaultModuleState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 RegisterEvent = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterAllMessages = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 GetName = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
 IterateModules = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 name = "Ovale_OvaleGUID"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 IsEnabled = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 UnregisterEvent = <function> defined @Interface\Ad

**Comment by ShmooDude** [comment]
Looks like all the /n (which is code for put a new line here) were replaced with an actual carriage return.

It must have been a bug when it got pushed to curse because the code in github that it's based on is correct.

If you want the latest version while Sidoine tracks down how this happened (could be broken on curse's end).  Just go to the code section and download the master and overwrite the contents of the Ovale directory with the contents (in the zip) of Ovale-master.  Do this rather than deleting the Ovale directory so you keep the library files you need since the github version doesn't include them.

**Comment by bhaskie357** [comment]
Thanks for all of your work on this!  I hate to be a pain, but....

I downloaded the .ZIP from the code section of the page, and I receive the following error:

Message: Interface\AddOns\Ovale\Frame.lua:356: attempt to call method 'GetIconNodes' (a nil value)
Time: 08/04/16 15:43:03
Count: 1
Stack: Interface\AddOns\Ovale\Frame.lua:356: in function `UpdateIcons'
Interface\AddOns\Ovale\Ovale.lua:265: in function `UpdateFrame'
Interface\AddOns\Ovale\Ovale.lua:125: in function <Interface\AddOns\Ovale\Ovale.lua:116>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ce\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: self = <table> {
 OnRelease = <function> defined @Interface\AddOns\Ovale\Frame.lua:104
 GetScore = <function> defined @Interface\AddOns\Ovale\Frame.lua:136
 OnAcquire = <function> defined @Interface\AddOns\Ovale\Frame.lua:100
 AceGUIWidgetVersion = 7
 LayoutFunc = <function> defined @Interface\AddOns\Recount\Libs\AceGUI-3.0\AceGUI-3.0.lua:629
 userdata = <table> {
 }
 base = <table> {
 }
 frame = <unnamed> {
 }
 UpdateActionIcon = <function> defined @Interface\AddOns\Ovale\Frame.lua:235
 OnUpdate = <function> defined @Interface\AddOns\Ovale\Frame.lua:165
 Hide = <function> defined @Interface\AddOns\Ovale\Frame.lua:92
 children = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Frame.lua:331
 LayoutFinished = <function> defined @Interface\AddOns\Ovale\Frame.lua:128
 actions = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Ovale\Frame.lua:337
 Show = <function> defined @Interface\AddOns\Ovale\Frame.lua:96
 content = <unnamed> {
 }
 events = <table> {
 }
 updateFrame = OvaleUpdateFrame {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Frame.lua:59
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = 1.#INF
}
profile = <table> {
 apparence = <table> {
 }
 source = "Ovale"
 list = <table> {
 }
 check = <table> {
 }
 standaloneOptions = false
 showHiddenScripts = false
 code = ""
}
left = 0
maxHeight = 0
maxWidth = 0
top = 0
BARRE = 8
margin = 4
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 baseName = "Ovale"
 Enable = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 moduleName = "OvaleCompile"
 EnableModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 IsModule = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 UnregisterAllEvents = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:202
 defaultModuleLibraries = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:87
 UnregisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 SetEnabledState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 RegisterMessage = <function> defined @Interface\AddOns\Clique\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 enabledState = true
 SetDefaultModuleState = <function> defined @Interface\AddOns\Recount\Libs\AceAddon-3.0\AceAddon-

**Comment by ShmooDude** [comment]
Are you sure you copied the contents of Ovale-master folder that was inside the zip (and not just extracted the zip) into your Ovale folder?  You should get asked if you want to overwrite 124 or so files.

**Comment by bhaskie357** [comment]
Correct.  I downloaded the .ZIP file to a separate directory and copied it to the AddOns\Ovale directory, overwriting the files.  I checked, and the Lib directory has the other files in besides the .xml file...

To be sure, I removed the addon completely, and re-installed it from Curse to ver 7.0.5.  This worked.  I then updated from the Code Section, again, copying the files to a separate directory, and copying the contents of each directory separately, overwriting the older files.

It now appears to be working without the errors.  I'm just looking for a way other than the file date stamp to ensure the version it is running.

Anyway, it is working!  Yay!  Nice work, all!

**Comment by g0shua** [comment]
@ShmooDude that appears to have cleared up my incrementing errors, many thanks.

```
There remains 3 that are showing up at login that seem trivial:
3x Ovale\libs\AceDBOptions-3.0\AceDBOptions-3.0-15.lua:357: unfinished string near '"'
3x Ovale\libs\AceComm-3.0\AceComm-3.0-9.lua:107: unfinished string near '"^[-'
3x Ovale\libs\LibTextDump-1.0\LibTextDump-1.0-1.lua:314: unfinished string near '"'
```

**Comment by ShmooDude** [comment]
@g0shua Yeah, looking at em that looks like the same thing.  That somehow "\n" got replaced with a carriage return.  Make sure you have all the libraries installed inside Ovale (Ovale/Libs).  If you do, try replacing them with the ones in version 7.0.5 though I had no problem with the 7.0.8 libs (looks like the 7.0.8 version was taken down anyhow).  After that I'm out of ideas.

@bhaskie357 /ovale version is probably what you're looking for.  Mine currently says development version which is all it's ever going to say getting it from github.  The version 7.0.8 from curse would say that (if it worked).  That file gets the version number automatically when it's put on curse.

**Comment by g0shua** [comment]
@ShmooDude Currently the master Ovale/libs folder is practically empty. I'll check prior releases and grab them that way. I have the libs folders from a previous Curse install so I'll overwrite those. The errors come back randomly too so I may end up having to keep Ovale disabled until this is resolved.

**Comment by ShmooDude** [comment]
Version 7.0.8 on Curse works fine for me now.

**Comment by g0shua** [comment]
Agreed, all clear here as well.
