### ISSUE TITLE
MM outported script from SIMC doesn't work

### ISSUE THREAD

**Issue by toxicherpes** [Sidoine/Ovale#190]
When I cast stuff the ovale plugin doesnt pick it up 
 MM Hunter only i think

**Comment by Reglohpri** [comment]
Why are you closing your old ticket #170?
Is this fixed now? I left any informations for the Author / Owner to check this.

Sincerely
Holger

**Comment by toxicherpes** [comment]
I thought I should make a ticket because ovale providing a output is fixed, it's just that the output doesn't work. Sorry if I made a mistake. Wonder if the plugin coder even reads these.

**Comment by Sidoine** [comment]
I read them :) 
It's just that these last months, I lack time, but I do my best

**Comment by Sidoine** [comment]
Could you explain what does not work? I just tested the script on a my hunter and it seems to work. But I am in no way an expert

**Comment by toxicherpes** [comment]
![Uploading Capture.PNG…]()

**Comment by toxicherpes** [comment]
shit didn't mean to close it  

When I put my simcraft profile into the input I get these errors. (in picture)
When I try to use the output it doesn't pick up that i've used a spell. Like if aimed shot comes up I would use it but ovale doesn't pick up it and give me the next spell to use.

**Comment by Sidoine** [comment]
Oh yes, there is something strange in the simcraft profile, I had to fix them before importing. See https://github.com/Sidoine/Ovale/blob/master/simulationcraft/SimulationCraft_Hunter_MM_T19P.simc
