### ISSUE TITLE
DemonicFuryDeficit() doesn't work - fix included

### ISSUE THREAD

**Issue by komurka4** [Sidoine/Ovale#194]
Function DemonicFuryDeficit() doesn't work.

Test script:
```
Include(ovale_common)
Include(ovale_trinkets_mop)
Include(ovale_trinkets_wod)
Include(ovale_demonhunter_spells)

AddIcon enemies=1 help=main specialization=havoc
{
	if DemonicFuryDeficit() < 30 Spell(chaos_strike)
	if DemonicFuryDeficit() >= 30 Spell(demons_bite)
}
```

Should show you Demon Blades/Demon's Bite until you're 30 from capping fury, then show Chaos Strike.

How to fix:
Modify file Power.lua, change:
`fury = { id = SPELL_POWER_FURY, token = "FURY", mini = 0, costString = FURY_COST }`
to:
`demonicfury = { id = SPELL_POWER_FURY, token = "FURY", mini = 0, costString = FURY_COST }`

**Comment by kevindesmet** [comment]
use `FuryDeficit()` instead
