### ISSUE TITLE
Demo Warlock scripts

### ISSUE THREAD

**Issue by Vanthios** [Sidoine/Ovale#195]
Hi there-

I asked on curse but didn't get an answer so I'll ask here :)

 Does anyone know what is usually the latest script? I have three listed and not sure the difference or why so many. Not sure why there is three or they say 7.0. Maybe demonology hasn't been updated? Which one should I use?
 
- [7.0] SimulationCraft: Warlock_Demonology_T19P
- Default script (simulationcraft_warlock_demonology_t19p)
- [7.0] Ovale Demonology Warlock

**Comment by kevindesmet** [comment]
`SimulationCraft: Warlock_Demonology_T19P` is the script you should use.
The default script also points to this one. It is mentionned twice but exactly the same script.

`[7.0] Ovale Demonology Warlock` was added by @Sidoine back in August when simc was not yet updated with the new scripts. I guess, this script can now be removed?

**Comment by Vanthios** [comment]
Thank you so much!
