### ISSUE TITLE
[7.1.4.2] "not BuffPresent()" condition not working

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#196]
-----
AddIcon  specialization=protectio
{
if BuffPresent(shield_of_the_righteous_buff) spell(shield_of_the_righteous)
}
------
Code above is working correctly, but code below is not. The spell is always suggested. "unless" condition does not work also
------
AddIcon  specialization=protection
{
if not BuffPresent(shield_of_the_righteous_buff) spell(shield_of_the_righteous)
}
-------

**Comment by Sidoine** [comment]
Use if BuffExpires(shield...) Spell(...)

**Comment by ShmooDude** [comment]
The second one will display SotR as being usable when the SotR buff expires, so some time in the future, so you're right that it would always display SotR while the former does not.  `BuffExpires()` should exhibit the same behavior as `not BuffPresent()`  Is the second one saying to cast it now, or in the future (ie when SotR is going to fall off).
