### ISSUE TITLE
shaman spell windstrike has wrong ID

### ISSUE THREAD

**Issue by firesgc** [Sidoine/Ovale#200]
In "ovale_shaman_spells.lua" "Define(windstrike 115356) " should be "Define(windstrike 17364)"

**Comment by kevindesmet** [comment]
That is incorrect.
Windstrike is 115356, Stormstrike is 17364
Stormstrike becomes Windstrike when Ascendance is up.
I see no issue with the current script, please elaborate if you do.

**Comment by firesgc** [comment]
Hmm... I can't find this spell in my spellbook at all and in wowhead (http://www.wowhead.com/spell=115356/windstrike) it is "Uncategorized". Normally it should have as category (Specialization->Shaman->Enhancement).
Weird...
