### ISSUE TITLE
Moving the bar

### ISSUE THREAD

**Issue by ishirra** [Sidoine/Ovale#201]
I can't really seem to find a way to move the bar on my screen.  It is now in the middle of my screen, blocking my view so i would like to move it.  
Is this possible and how do I do it?

**Comment by ishirra** [comment]
Found it! Silly me, need to open my eyes

**Comment by SpareSimian** [comment]
What was your solution? There seems to be a very tiny anchor at bottom left of the buttons that I can move if I somehow magically shift-left-click and drag. But it seems to be very hard to find on my 4k display. Is there a trick to this?
