### ISSUE TITLE
Havoc DH script broken in last release

### ISSUE THREAD

**Issue by alarge** [Sidoine/Ovale#203]
Prior to last release, the script seemed to work fine.  With the latest release, "Demon Blades" (a passive) is shown a large percentage of the time, and other abilities (Fel Rush in particular) seem to be under-represented.

**Comment by VonZilla** [comment]
Same here.  :)

**Comment by kevindesmet** [comment]
@alarge 
I think the script is stuck in "pooling_for_meta" and thus results into a rotation to not spend any fury until meta is used (or charging).
Can you try and use meta and inspect the behavior during meta and when meta is on cooldown?

@Sidoine 
Been trying something to add a "InBossFight()" condition. Do you have any remarks?
See: https://github.com/kevindesmet/Ovale/commit/e1336b38036382f43d3e51dd13befd0c041d6537

**Comment by alarge** [comment]
After playing with this a bunch more, I've come to the conclusion that this is just a poor design decision.  Someone decided to move Vengeful Retreat and Fel Rush from the main suggester to the short cooldowns and to pool for Metamorphosis without suggesting it.  So now, my logic when reading the icons is:

  1. Is there a suggestion up?  If so, use it

  2. Otherwise, is there a short-term CD up?  If so, use it UNLESS it is Blur.

  3. Otherwise, is Metamorphosis up on the long-term CDs?  If so, use it.

This makes it pretty damned difficult to use.

My take is that (1) VR and FR should be moved back to the core rotation and (2) if the core rotation is going to stall when waiting for Meta to be used, then it should also show up on the core rotation.

**Comment by kevindesmet** [comment]
@alarge 

I am fiddling around with the suggestions you made by putting basically every spell back into the main rotation (except for blur).
For metamorphosis: a checkbox was added to opt-in using meta only on boss fights or always.

See pull request #206
