### ISSUE TITLE
WOW 7.1.5 : Ovale 7.1.4.2 : Errors listed in Chat Window

### ISSUE THREAD

**Issue by DrStrik9** [Sidoine/Ovale#212]
Ovale still works great in 7.1.5. -- But now there are hundreds of error messages showing up in the WOW Chat Window whenever the character is in combat. It's not a killer, but very messy, and impossible to keep track of conversations. -- Tested here only on Shadow Priest.

**Comment by kevindesmet** [comment]
@DrStrik9 Can you make a screenshot of it (or paste what you see in the chat?)

**Comment by DrStrik9** [comment]
Here are a couple of screen shots: the first one is immediately after logging on, and the second one is at the targets. I hope this helps.  :+)

![screen shot 2017-01-10 at 2 13 10 pm](https://cloud.githubusercontent.com/assets/25041864/21827142/2d9795c4-d73f-11e6-9c92-2f03a0ae3df3.png)
![screen shot 2017-01-10 at 2 14 31 pm](https://cloud.githubusercontent.com/assets/25041864/21827145/31237726-d73f-11e6-8e8d-af01fc1a4bad.png)

**Comment by Nitespirit** [comment]
Getting the same error spam here.  Looks like it relates to Mind Sear talent.

**Comment by DrStrik9** [comment]
That makes sense. Mind Sear was removed. AOE is now accomplished with Mind Flay while Shadow Word: Pain is active.

**Comment by alarge** [comment]
There are several spells that have been removed from the game.  I think someone just needs to go through and scrub them from the code base.  In the cases I've run across (Mind Sear, Drain Soul vs. Drain Life, Mana Tap), the scripts still work fine -- there's just lots of chat window spam.

**Comment by Sidoine** [comment]
I will fix these errors this week end
