### ISSUE TITLE
Ovale Simulationcraft output no longer returns anything

### ISSUE THREAD

**Issue by sirmollerson** [Sidoine/Ovale#216]
Currently when I input the default deathknight APL into the input and click accept nothing gets returned in the output window. 

If the input has errors the error checking is still returning things into the chat.

**Comment by heksebek** [comment]
i have also issue sinds yesterday after the update there is nu output window and it keep saying in the chat unknow speel with id 196104used in spell 196104. i only have this isue with my warlock.
also tryed different specs but it still wouldnt work
