### ISSUE TITLE
[Feature request] new functions for estimated healing like CritDamage, Damage etc.

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#226]
If anyone could, please...

**Comment by Rabalaba** [comment]
you can use UnitStat("player", 4)*GetCombatRatingBonus(CR_VERSATILITY_DAMAGE_DONE)*GetCombatRatingBonus(CR_CRIT_SPELL)

**Comment by ShmooDude** [comment]
Those functions already exist.  Not sure if they still work but they're there.
