### ISSUE TITLE
Lua Error Spam

### ISSUE THREAD

**Issue by Ghanrak** [Sidoine/Ovale#23]
"Message: Interface\AddOns\Ovale\Frame.lua:172: attempt to call
Time: 08/11/16 19:58:19
Count: 12238
Stack: [C]: in function `UnitGUID'
Interface\Addons\Ovale\Frame.lua:172: in function `OnUpdate'
Interface\Addons\Ovale\Frame.lua:89: in function
<Interface\Addons\Ovale\Frame.lua:88>

Locals:"

This is the message that continues to spam.

**Comment by ShmooDude** [comment]
My guess is it's the same thing that happened last time, that all the /n got changed to actual carriage returns as it looks very similar.

**Comment by g0shua** [comment]
Yup, same thing again. Downloading the latest release and overwriting the files in the Ovale directory worked. Just gives out a few small lib errors:

```
1x Ovale\libs\AceDBOptions-3.0\AceDBOptions-3.0-15.lua:357: unfinished string near '"'
1x Ovale\libs\AceComm-3.0\AceComm-3.0-9.lua:107: unfinished string near '"^[-'
1x Ovale\libs\LibTextDump-1.0\LibTextDump-1.0-1.lua:298: unfinished string near '"'
```

Is there a good source for the current libs? How are those downloaded exactly?

**Comment by ShmooDude** [comment]
Just use a previous version's libraries (7.0.8 or 7.0.5 should be fine).

**Comment by g0shua** [comment]
Errors stopped with 7.9.0.1 via Curse.
