### ISSUE TITLE
Affliction warlock script problem (Reap Souls)

### ISSUE THREAD

**Issue by alarge** [Sidoine/Ovale#232]
I've been having Reap Soul issues and I think I finally figured out why.  I think the spell id for deadwind_harvester_buff is wrong (says 214867, but I think it is really 216708).  The problem manifests itself as a suggestion to cast Reap Soul, even when you have an existing Deadwind Harvester buff (sometimes much longer buff than you'd get if you ate your currently available souls).

**Comment by kevindesmet** [comment]
@alarge can you please check the changes as shown in https://github.com/kevindesmet/Ovale/commit/98126f9cdb2ab3d65c5a3a1e3455fc936697fd46 and say if this does in fact solve your issue?
I have no warlock on my own, so can't verify

**Comment by alarge** [comment]
Commented directly on the commit, but yes, I think this is the right change.
