### ISSUE TITLE
Nighthold- Elisande fight

### ISSUE THREAD

**Issue by Bingo176** [Sidoine/Ovale#252]
The Frost DK script on this fight goes crazy. Not sure exactly what causes it but it constantly cycles between Obliterate, Howling Blast, and Frost Strike every half second. Might have something to do with the fight mechanics but it does happen right when the fight starts.

**Comment by ChocoSauce** [comment]
Same thing happens with some fights with the SV script. It just keeps suggesting Raptor Strike over and over. Nighthold and Ovale seem to be incompatible or something.

**Comment by Bingo176** [comment]
Another thing to note this didn't start at the launch of NH. I would say it started about 2 versions ago of Ovale.

**Comment by kevindesmet** [comment]
@Bingo176 
Can you tell me your build (talents)?
Does it happen on LFR as well?
Which legendaries do you have?

**Comment by Bingo176** [comment]
3/1/2/3/2/3/2
Yes
Perseverance of the Ebon Martyr
4

**Comment by kevindesmet** [comment]
I just tried LFR on my Frost DK.
He does not have legendaries nor tier set and I was unable to reproduce what you mean.
He does have very low haste value (only 8%)

The thing I'm wondering though whether it is an issue with the recharge time of our runes.
I suspect blue bubble slows down the recharge time and pink bubble speeds it up.
However, the (blue or pink) debuff don't increase haste rating, they just apply a fixed percentage.
The recharge times of runes are calculated based on the haste rating at the time the spell is cast.

It would make sense that with higher haste rating, the impact of blue or pink debuff is higher.

@Sidoine what is your opinion?

**Comment by ChocoSauce** [comment]
Can high haste values mess up Ovale? I've noticed that it tends to mess up most on fights where there is some kind of speed up like Elisande and Chronomatic Anonmaly. 

I play SV hunter with 4 piece and 2 legendaries. Way of moknathal, murder of crows, steel trap, serpent sting, spitting cobra. There are a lot of buttons and cooldowns that are monitored. I have about 24% haste and with lust and other things it seems the script bug out. It'll be working fine and then randomly at some point during the fight it'll only suggest raptor strike and nothing else.

**Comment by Bingo176** [comment]
I know it's been a bit since this has been talked about. Still persists in newest version. Did a little testing in LFR including a clean install before i started(saved variables etc). The only way I could get it to go away was a /reload mid combat then sometimes it would come back others it would not. Not sure it would help but just a little more info.

**Comment by Sidoine** [comment]
It may be a haste problem but it will be difficult to investigate. I will try anyway.

**Comment by Bingo176** [comment]
I just ran another LFR and made sure not to pick up the pink bubble(haste effect) or the slow bubble. It mainly seems to be an issue with the Howling Blast logic or something. It recommends Howling Blast when rime is not not present or when Howling Blast's dot is already present on the boss but again it just flickers in and out on the bar. The other rotation looks solid minus HB just coming and going.
