### ISSUE TITLE
Affliction warlock Input

### ISSUE THREAD

**Issue by stanggt5090** [Sidoine/Ovale#262]
I'm trying to input simcraft profile into ovale and i keep getting a syntax error unexpected token 'I' when parsing SIMPLE EXPRESSION 
 Next tokens: I talent.soul_effigy.disabled ) & remains <= tick_time + gcd <EOS>

because of it i nothing comes outin output

**Comment by Sidoine** [comment]
It should be a vertical bar | and not an uppercase i
