### ISSUE TITLE
Ovale Compile Unknown Spell Error

### ISSUE THREAD

**Issue by Arthaei** [Sidoine/Ovale#266]
Hi, I'm currently getting the following error:

OvaleCompile:  Unknown spell with ID incarnation_son_of_ursoc used in spell(incarnation_son_of_ursoc).

This happens whenever I enter or exit any druid form. 

Hoping for a fix!

Thanks.

**Comment by Sidoine** [comment]
There is no reference to a incarnation_son_of_ursoc in the default scripts. Do you mean incarnation_guardian_of_ursoc? Anyway, I'm not able to reproduce the bug.

**Comment by Arthaei** [comment]
Hi, thanks for checking it for me. I've sinced realised it's part of an alternative code I'm using from the Fluid Druid forums. There are some excellent improvements from the default, but they had forgotten to update that line for some reason! thanks
