### ISSUE TITLE
add support for addduration when another spell has been cast

### ISSUE THREAD

**Issue by Hemario** [Sidoine/Ovale#271]
Balance druid talent Nature's Balance (http://www.wowhead.com/spell=202430/natures-balance) does the following:

> Aligns the power of the Moon and Stars, causing Lunar Strike to extend the duration of your Moonfire by 6.0 sec, and Solar Wrath to extend the duration of all of your Sunfires by 4.0 sec.

AFAIK it is currently not possible to declare spellinfo based on the successfull cast of another spell.

Example:
`SpellRequire(moonfire_debuff addduration 6=onspellcast;lunar_strike_balance talent=natures_balance_talent)`
`SpellRequire(sunfire_debuff addduration 4=onspellcast;solar_wrath talent=natures_balance_talent)`

**Comment by kevindesmet** [comment]
Think we really need to start considering this.
In patch 7.2.5 they will be adding even more addduration on a buff, cdreduction on a spell after the successfull cast of another spell.

For instance:
using tiger palm will reduce the cooldown of blackout strike by 6 seconds (fictional numbers, but the mechanic will end up being like that)
Right now, there is no way to define that in Ovale (unless I'm wrong).
