### ISSUE TITLE
Feral Druid - showing brutal slash when talent not taken

### ISSUE THREAD

**Issue by thompsondj** [Sidoine/Ovale#273]
Brutal slash is being recommended for feral druid even when the talent is not taken.

**Comment by bousteur** [comment]
+1 :/

**Comment by thompsondj** [comment]
Seems like it might actually be bigger than just brutal slash for feral. I noticed on my BM hunter, it's recommending Dire Frenzy when that talent is not taken as well.

**Comment by bousteur** [comment]
this recommandation is skip when you take the talent and remove it.

**Comment by kAz0** [comment]
Brutal slash still showing in the rotation without being taken also trash doesnt recognise its button
+1 for the post hope its fixed soon 
Cant play without the addon

**Comment by thompsondj** [comment]
It.. appears to have fixed itself? Haven't seen an update come through but it's not recommending brutal slash on my feral druid nor dire frenzy on my bm hunter anymore when those talents are not taken. Can anyone else confirm?

**Comment by bousteur** [comment]
It seems to be right, will confirm this evening during boss encounters.

**Comment by Sidoine** [comment]
I suspect that there was a problem with local talent caching after the 7.2 update. Maybe it was fixed by the expiration of the cache. Prior to that, I resolved a similar problem by changing my talent back and forth.

**Comment by ShmooDude** [comment]
Fixed for a while
