### ISSUE TITLE
BM hunter - showing Dire Frenzy when talent not taken

### ISSUE THREAD

**Issue by Vederia** [Sidoine/Ovale#274]
As the title says, ovale suggests Dire Frenzy althoug I do no have this talent selected. Gets hung up on it until I randomly click on another spell. Thank You !!

**Comment by libranz** [comment]
Same problem. Only Dire Frenzy appears constantly, although the selected talent "Stomp". Helps the re-election of talent on the Dire Frenzy, then back to "Stomp". In raids and dungeons you have to use the "Tome of the clear mind".

**Comment by Vederia** [comment]
Yeah been doing this, every time I log out and back on it goes back to suggesting dire Frenzy, same when I go through any kind of portal. Tomes are getting expensive .
