### ISSUE TITLE
Elemental Shaman: Single and Multi Target rotation icons not displaying correct icons

### ISSUE THREAD

**Issue by goodjams** [Sidoine/Ovale#275]
Hi, 
Since 7.2 loaded Ovale is displaying a fixed icon (refer to screenshot) for the single and multi shot rotation icons. IT will randomly switch to the actual icons during combat but randomly goes back to the fixed icon.
I have unloaded all addons but the issue still persists.
On another character the problem does not occur.

![wowscrnshot_032917_194356](https://cloud.githubusercontent.com/assets/26762909/24446246/85a50b5a-14b8-11e7-9702-ed196ec7b4b5.jpg)

**Comment by oisteink** [comment]
It's working, but it's telling you to cast storm elemental

**Comment by goodjams** [comment]
I am not talented into storm elemental,I have Echo of the elements talented

**Comment by Bluefer** [comment]
mine isn't working. my enhancement Shaman shows the same 2 icons in the middle for the length of a fight.

**Comment by goodjams** [comment]
Have found more info if i trigger fire elemental then the icons will cycle correctly until fire elemental comes off cooldown.
Hope this helps

**Comment by oisteink** [comment]
Talent difinitions seems odd - like pre 7.1.5.
From ovale_shaman_spells.lua:
```
Define(hot_hand_talent 2)
Define(boulderfist_talent 3)
Define(totemic_persistence_talent 8)
Define(hailstorm_talent 12)
Define(echo_of_the_elements_talent 12)
Define(overcharge_talent 14)
Define(icefury_talent 15)
Define(unleashed_fury_talent 16)
Define(crashing_storm_talent 16)
Define(cloudburst_totem_talent 19)
Define(primal_elementalist_talent 17)
Define(elemental_blast_talent 18)
Define(elemental_fusion_talent 19)
Define(ascendance_talent 19)
Define(storm_elemental_talent 20)
Define(high_tide_talent 21)
Define(liquid_magma_talent 21)
```

**Comment by Bluefer** [comment]
hunter has the same problem. Any fix in the works are is it uninstall time?
