### ISSUE TITLE
WW 7.2 Katsuo's Eclipse nerf

### ISSUE THREAD

**Issue by Hinalover** [Sidoine/Ovale#277]
In 7.2, the Legendary, Katsuo's Eclipse, was nerfed. Before it caused Fists of Fury to only cost 1 chi. Now it costs 2 Chi. In the image provided the mini-weak aura below ovale represents the number of Chi I have. Currently it's at 1 chi but Ovale is showing to use Fists of Fury. You can see in the bottom right corner that my Fists of Fury is not lit up to be usable.

![](https://i.gyazo.com/3944fd506970e00e6bd00f5473c0f21b.png)

As an aside, I did update the SimC APL the night before the patch (though I haven't updated the profiles yet) and it looks like you didn't update the Ovale profile yet. It was mostly minor stuff but there was a bit of work on Touch of Death code.

**Comment by kevindesmet** [comment]
fix provided in commit https://github.com/Sidoine/Ovale/pull/282/commits/a28ead050885a2c447d9f909c0c5701cf62ea87b
