### ISSUE TITLE
Assassination Rogue Not Showing Envenom

### ISSUE THREAD

**Issue by djbox40** [Sidoine/Ovale#281]
I have used default scripts and a script created through simming myself. I cannot seem to get envenom to show up in my rotation.

Here is my code I use for ovale.
[sinRogueCode.txt](https://github.com/Sidoine/Ovale/files/887283/sinRogueCode.txt)

**Comment by djbox40** [comment]
It wasn't showing envenom simply because in the script, it always wanted to maintain rupture on other targets instead of using envenom. I adjusted the script accordingly and now it works great.

**Comment by mepocket** [comment]
Nice, that you could adjust the problem for yourself, but how did u manage that. i really do suck at coding and it would be pretty cool to have it fixed by anyone :-P
