### ISSUE TITLE
BaseDuration not working for Hunters

### ISSUE THREAD

**Issue by LunaEclipse73** [Sidoine/Ovale#283]
I just did some testing, and while BaseDuration works fine on my Shadow Priest and other classes to get base durations of debuffs for calculating pandemic range, it doesn't work for Hunters.  This can be easily verified by adding an icon with the following:

`AddIcon { BaseDuration(lacerate_debuff) } `

The icon created will display INF, same with Murder of Crows debuff.

**Comment by ChocoSauce** [comment]
That would explain why the current script in Ovale keeps suggesting Lacerate over and over when there is over 10 seconds left on the debuff.

**Comment by LunaEclipse73** [comment]
One of the users who helps with my addon with optimizing Hunter scripts discovered the reason.  Spell definition for Lacerate Debuff does not contain duration information.  Modify it to the following and it displays correctly.

```
Define(lacerate_debuff 185855)
     SpellInfo(lacerate_debuff duration=12)
```
