### ISSUE TITLE
Lots of errors on PTR

### ISSUE THREAD

**Issue by Darkmoded** [Sidoine/Ovale#299]
I know its early, just wanted to let you know everything is broken on the PTR. 

Cheers,

**Comment by Bingo176** [comment]
It's weird they didn't change anything by the looks of it. Maybe I missed something. Either way a few small errors pop up but resolving them causes a ton of other issues.

**Comment by Bingo176** [comment]
Message: Interface\AddOns\Ovale\Power.lua:132: table index is nil
Time: 05/29/17 18:40:03
Count: 1
Stack: Interface\AddOns\Ovale\Power.lua:132: table index is nilInterface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
Interface\AddOns\Ovale\Power.lua:132: in main chunk

Locals: errorMessage = "Interface\AddOns\Ovale\Power.lua:132: table index is nil"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0
----------------------------------------------
Message: Interface\AddOns\Ovale\Stance.lua:47: table index is nil
Time: 05/29/17 18:40:03
Count: 1
Stack: Interface\AddOns\Ovale\Stance.lua:47: table index is nilInterface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
Interface\AddOns\Ovale\Stance.lua:47: in main chunk

Locals: errorMessage = "Interface\AddOns\Ovale\Stance.lua:47: table index is nil"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0
