### ISSUE TITLE
Druid feral rotation

### ISSUE THREAD

**Issue by bousteur** [Sidoine/Ovale#3]
Current rotation isn't complete.
 I'll try to explain:
 If combopoints=5 then {
         If bloodtalonstalent AND PredatorySwiftnessbuff present then {
                   healing touch
                   }
          Else {
                   if savageroarbuff absent then{
                           savage roar
                   }
                   If targetRipdebuff absent then{
                           rip
                   }
                   Ferocious Bite
         }
}
Else {
    If clearcastingbuff present then {
            trash
    }
    If targetrakedebuff absent then {
            rake
    }
    shred
}

Sorry, i'm not a coder, i tryed to explain rotation with some basic knowledge.

**Comment by ShmooDude** [comment]
#4 should fix this (though there's other rotational issues mostly due to the action list on the current simcraft being not well done for level 100.  But that's not really an Ovale problem, that's a simcraft problem.
