### ISSUE TITLE
DK - GCD

### ISSUE THREAD

**Issue by Ophidon** [Sidoine/Ovale#30]
Version: 7.0.11.0

I see in this most recent update that the GCD for DK's was updated to 1.0 non-hasted. However, while that was true from possibly the beginning of the spec until now, as of Legion DK's have been placed on a 1.5s hasted gcd. True at least for Frost and Unholy, no personal experience with Blood, but likely them as well.

Here is a thread discussing this change: http://www.arenajunkies.com/topic/348799-death-knight-gcd-in-legion/

You might want to verify the current status of the other previously 1.0 non-hasted gcd classes too, they might have been changed for Legion as well. I can understand why they'd do it, as it makes it much easier for Haste to scale as a stat for these classes.

**Comment by ShmooDude** [comment]
Ah, ok. I knew they did it for hunters, didn't think about DKs.  So just the energy classes then (Rogue, Cat Form Druid, WW/BM Monk).
