### ISSUE TITLE
Doesn't run at all in 7.2.5

### ISSUE THREAD

**Issue by flatluigi** [Sidoine/Ovale#306]
Something made it busted completely. Might be that SPELL_POWER_X is no longer usable, but it could be a range of things.

**Comment by Tombsv** [comment]
Having the same problem. I can see the settings icon next to the mini map. But the addon is not showing.

**Comment by wjmadden** [comment]
BugSack flagged line 47 in Stance.lua with a 'table index is nil' error:

	[API_GetSpellInfo(171745)] = "druid_claws_of_shirvallah",

Once I commented it out things seemed to work fine.

**Comment by mwiland** [comment]
all i know is that this is completely 100% broken. i dont know anything about debugging. i need help on this.

**Comment by Konnartist** [comment]
Open up Stance.lua and put '--' in front of [API_GetSpellInfo(171745)] = "druid_claws_of_shirvallah", then save the file.. Ovale will work after this

**Comment by thompsondj** [comment]
Same experience here. Addon was broken and not showing up at all. Commenting out  [API_GetSpellInfo(171745)] = "druid_claws_of_shirvallah" in Stance.lua makes it work again.

**Comment by Tombsv** [comment]
Can confirm. Commenting out [API_GetSpellInfo(171745)] = "druid_claws_of_shirvallah" solved my problem. Which is something I didn't think it would due to it being a druid spell and I'm a  hunter. But I don't know anything about code so. :D

**Comment by zachljp** [comment]
okay so im all new to this where do i go to fix my addon. I see something about Stance.lua but when I go to it, i dont have an option to do what I need to do to fix my addon. Pls help

**Comment by wjmadden** [comment]
In your World of Warcraft directory, drill down into the Interface/Addons/Ovale directory. There you'll find Stance.lua. Edit the file in your favorite plain text editor, and put two dashes at the start of line 47 (the line I referenced above)

**Comment by zachljp** [comment]
I have done all that, i dont see a 'Stance.lua' Is it called something else? because im not finding, sorry for being a pain but that was my go to at the get-go but did not find it.

**Comment by Lotusflower84** [comment]
Where next to line 47 do I put the 2 dashes?.

**Comment by wjmadden** [comment]
Two dashes are the start comment marker in Lua. put them at the start of the line

**Comment by Lotusflower84** [comment]
So not next to the text but all the way to the left of it?.

**Comment by wjmadden** [comment]
It shouldn't matter - the double dash says to treat all characters to the right of the double dash until the end of the line as a comment
