### ISSUE TITLE
Elemental Shaman spell list is broken

### ISSUE THREAD

**Issue by MichaelKaiser** [Sidoine/Ovale#310]
When I log on my elemental Shaman LUA errors are rising immediately, saying that in Cooldown.lua:460  arithmetics are done with duration, which is a nil value.
To get a trace of the cause I added 
`
cdduration = cd.duration
if not cdduration then cdduration=0 end
`
and changed the access in 460 from cd.duration to cdduration. I know, this will only fix the symtoms, not the cause.
Reloading the UI after this a vast list of spells, which are now unknown is posted into the chat window (which I guess is the cause of the problem).

**Comment by Sidoine** [comment]
Element shaman script need a level 100 shaman, which I don't have. Can somebody tell me if it works?
