### ISSUE TITLE
Ovale doesn't work with Beast Mastery Hunter in Patch 7.2.5

### ISSUE THREAD

**Issue by Ash0207** [Sidoine/Ovale#313]
Pulled up WoW today and noticed my Ovale wasn't showing up on my interface but everything in my chat bar and settings appeared as if the addon was working properly. I tried turning the addon off and back on, I tried using different scripts, I tried deleting the addon and reinstalling it, made sure everything was checked and turned on. Nothing worked, I Googled the issue and I saw some comments involving a bug in line 47 in Stance.lua. So commented line 47 like I read in a few other comments that they said worked for them regarding issues with Ovale in patch 7.2.5. It did work for my alt which is a Feral Druid, but it will not work for my main which is a Beast Mastery Hunter. Does anyone know the debug fix for this class?

**Comment by ShmooDude** [comment]
Until we get around to fixing it, use this script:
https://pastebin.com/uhiLPWB9

Should work.

**Comment by Hummingbird4** [comment]
Also does not work with Arcane Mage but does seem to work with both Frost and Fire

**Comment by Ash0207** [comment]
Tried using the script above in custom script for the addon and i refreshed my UI and it didn't show up. I turned the addon off and back on and it still didn't pop up. Any other suggestions? Any idea when this will be fixed if no other suggestions are available?

**Comment by Sidoine** [comment]
Is this still an issue?

**Comment by Hummingbird4** [comment]
No longer an issue

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
