### ISSUE TITLE
Ovale not working with WW Monk in new update

### ISSUE THREAD

**Issue by kelleekicksass** [Sidoine/Ovale#321]
getting 2 error codes

Date: 2017-06-16 17:34:24
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Ovale\Stance.lua line 300:
   '<eof>' expected near 'end'

2nd error message 

Date: 2017-06-16 17:34:40
ID: 2
Error occured in: Global
Count: ∞
Message: ..\AddOns\Ovale\Ovale.lua line 171:
   attempt to index field '?' (a nil value)
Debug:
   Ovale\Ovale.lua:171: IsPreloaded()
   Ovale\Compile.lua:688: EvaluateScript()
   Ovale\Frame.lua:185: OnUpdate()
   Ovale\Frame.lua:89:
      Ovale\Frame.lua:88
Locals:
self = <table> {
 Ovale_CombatStarted = <function> defined @Interface\AddOns\Ovale\Ovale.lua:149
 OneTimeMessage = <function> defined @Interface\AddOns\Ovale\Ovale.lua:391
 OvaleScore = <table> {
 }
 EnableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "Ovale"
 IterateEmbeds = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
 MSG_PREFIX = "Ovale"
 OvaleDebug = <table> {
 }
 frame = <table> {
 }
 defaultModulePrototype = <table> {
 }
 playerGUID = "Player-123-05B16DCC"
 db = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:440
 OvaleShadowWordDeath = <table> {
 }
 OvaleSpellBook = <table> {
 }
 OvaleWarriorCharge = <table> {
 }
 defaultModuleState = true
 FinalizeString = <function> defined @Interface\AddOns\Ovale\Ovale.lua:345
 IsEnabled = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
 UpdateControls = <function> defined @Interface\AddOns\Ovale\Ovale.lua:215
 OvaleSteadyFocus = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:381
 UpdateVisibility = <function> defined @Interface\AddOns\Ovale\Ovale.lua:180
 OvaleSpellDamage = <table> {
 }
 OvaleData = <table> {
 }
 checkBoxWidget = <table> {
 }
 RegisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 ResetControls = <function> defined @Interface\AddOns\Ovale\Ovale.lua:210
 ToggleCheckBox = <function> defined @Interface\AddOns\Ovale\Ovale.lua:311
 OvaleActionBar = <table> {
 }
 OvaleCooldown = <table> {
 }
 Ovale_CombatEnded = <function> defined @Interface\AddOns\Ovale\Ovale.lua:153
 OvaleSigil = <table> {
 }
 OvaleComboPoints = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:398
 OvalePassiveAura = <table> {
 }
 OvaleEnemies = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 OvaleHonorAmongThieves = <table> {
 }
 enabledState = true
 OvaleRunes = <table> {
 }
 RegisterEvent = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 OvaleLexer = <table> {
 }
 OvaleRecount = <table> {
 }
 listWidget = <table> {
 }
 OvaleDataBroker = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 OvaleDamageTaken = <table> {
 }
 OvaleBossMod = <table> {
 }
 OvaleHealth = <table> {
 }
 OvaleAST = <table> {
 }
 IsChecked = <function> defined @Interface\AddOns\Ovale\Ovale.lua:288
 OvaleState = <table> {
 }
 OvaleVersion = <table> {
 }
 PrintOneTimeMessages = <function> defined @Interface\AddOns\Ovale\Ovale.lua:402
 OvaleOptions = <table> {
 }
 OvaleArtifact = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\Ovale\Ovale.lua:103
 NewModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:266
 OvaleSpellFlash = <table> {
 }
 OvaleWildImps = <table> {
 }
 OvalePool = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:241
 OvaleGUID = <table> {
 }
 OvaleScripts = <table> {
 }
 OvalePaperDoll = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 OvaleBanditsGuile = <table> {
 }
 OvalePower = <table> {
 }
 OvaleFuture = <table> {
 }
 ToggleOptions = <function> defined @Interface\AddOns\Ovale\Ovale.lua:176
 GetCheckBox = <function> defined @Interface\AddOns\Ovale\Ovale.lua:270
 OvaleEquipment = <table> {
 }
 UpdateFrame = <function> defined @Interface\AddOns\Ovale\Ovale.lua:263
 OvaleSkada = <table> {
 }
 GetName = <function> defined @Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:310
 OvaleCondition = <table> {
 }
 SendMessage = <function> defined @Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 OvaleBestAction = <table> {
 }
 name = "Ovale"
 OvaleQueue = <table>

**Comment by kevindesmet** [comment]
which version are you using?
