### ISSUE TITLE
While playing a subtlety rogue, crossing zone boundaries outputs 7 "Unknown spell" errors

### ISSUE THREAD

**Issue by darrenmonahan** [Sidoine/Ovale#322]
When loading or moving into different zones, the following is printed to the General chat window:

OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).
OvaleCompile: Unknown spell with ID 206237 used in Spell(206237).

Spell ID 206237 is Enveloping Shadows, which was removed in 7.2.5.

**Comment by RJTeefus** [comment]
22 days ago!
