### ISSUE TITLE
GetHasteMultiplier error

### ISSUE THREAD

**Issue by Ravenslair38** [Sidoine/Ovale#323]
30x Ovale\Data.lua:654: attempt to call method 'GetHasteMultiplier' (a nil value)
Ovale\Data.lua:654: in function `GetBaseDuration'
Ovale\Aura.lua:1301: in function `ApplySpellAuras'
Ovale\Aura.lua:1083: in function `?'
Ovale\State.lua:82: in function `InvokeMethod'
Ovale\Future.lua:1442: in function `ApplySpell'
Ovale\Future.lua:1051: in function `ApplyInFlightSpells'
Ovale\BestAction.lua:359: in function `StartNewAction'
Ovale\Frame.lua:206: in function `OnUpdate'
Ovale\Frame.lua:89: in function <Ovale\Frame.lua:88>

Locals:

**Comment by rockschtar** [comment]
Have the same error with destruction warlock

**Comment by jaybyrrd** [comment]
Can confirm.

**Comment by Ravenslair38** [comment]
on my lock im also getting this error 

497x Ovale\Data.lua:654: attempt to call method 'GetHasteMultiplier' (a nil value)
Ovale\Data.lua:654: in function `GetBaseDuration'
Ovale\Aura.lua:1301: in function `ApplySpellAuras'
Ovale\Aura.lua:1083: in function `?'
Ovale\State.lua:82: in function `InvokeMethod'
Ovale\Future.lua:1442: in function `ApplySpell'
Ovale\Future.lua:1051: in function `ApplyInFlightSpells'
Ovale\BestAction.lua:359: in function `StartNewAction'
Ovale\Frame.lua:206: in function `OnUpdate'
Ovale\Frame.lua:89: in function <Ovale\Frame.lua:88>

Locals:

**Comment by jaybyrrd** [comment]
#318 seems to fix this.

**Comment by jaybyrrd** [comment]
Closed by #318 I believe. Can weq get an updated status on this?

**Comment by Sidoine** [comment]
Should be fixed in beta version
