### ISSUE TITLE
Affliction Warlock Rotation

### ISSUE THREAD

**Issue by Lockmaster1** [Sidoine/Ovale#326]
Get a Lua error upon cast of unstable affliction hope this helps love the addon.

Message: Interface\AddOns\Ovale\Data.lua:654: attempt to call method 'GetHasteMultiplier' (a nil value)
Time: 06/19/17 15:57:10
Count: 1153
Stack: Interface\AddOns\Ovale\Data.lua:654: attempt to call method 'GetHasteMultiplier' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: in function `GetHasteMultiplier'
Interface\AddOns\Ovale\Data.lua:654: in function `GetBaseDuration'
Interface\AddOns\Ovale\Aura.lua:1301: in function `ApplySpellAuras'
Interface\AddOns\Ovale\Aura.lua:1083: in function `?'
Interface\AddOns\Ovale\State.lua:82: in function `InvokeMethod'
Interface\AddOns\Ovale\Future.lua:1442: in function `ApplySpell'
Interface\AddOns\Ovale\Future.lua:1051: in function `ApplyInFlightSpells'
Interface\AddOns\Ovale\BestAction.lua:359: in function `StartNewAction'
Interface\AddOns\Ovale\Frame.lua:206: in function `OnUpdate'
Interface\AddOns\Ovale\Frame.lua:89: in function <Interface\AddOns\Ovale\Frame.lua:88>

Locals: errorMessage = "Interface\AddOns\Ovale\Data.lua:654: attempt to call method 'GetHasteMultiplier' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

**Comment by Sidoine** [comment]
Fixed in beta version
