### ISSUE TITLE
OvaleCompile: Unknown spell error (Enhancement Shaman)

### ISSUE THREAD

**Issue by Ghanrak** [Sidoine/Ovale#330]
> OvaleCompile: Unknown spell with ID 201897 used in Spell(201897).
> OvaleCompile: Unknown spell with ID 201897 used in Charges(201897 count=0).
> OvaleCompile: Unknown spell with ID 201897 used in Spell(201897).
> OvaleCompile: Unknown spell with ID 201897 used in Spell(201897).
> OvaleCompile: Unknown spell with ID 201897 used in Spell(201897).
> OvaleCompile: Unknown spell with ID 201897 used in Charges(201897 count=0).

This spams my chat log upon logging in, as well as any time I activate Ascendance and when its duration expires.

**Comment by Lilykoi** [comment]
I too am getting that same spam on Shaman on either Enhancement or Elemental.

**Comment by kevindesmet** [comment]
potential fix for enhancement shaman, needs testing
https://github.com/Sidoine/Ovale/pull/331/commits/9e923b5e10f245d575d4b76fec6d72091c7ebf8e

**Comment by Sidoine** [comment]
Should be fixed in current beta version
