### ISSUE TITLE
pet_count not implemented

### ISSUE THREAD

**Issue by sargentsurg** [Sidoine/Ovale#332]
Found this in simc but not sure how to implement it in ovale so we have a similar way to count how many Demonlogy warlock pets are active.
https://github.com/simulationcraft/simc/blob/fc8ffa7ec8a134a21a3317daac0a8af4e6edfd88/engine/class_modules/sc_warlock.cpp#L7308

**Comment by Sidoine** [comment]
There is a Demons condition that do what you want
