### ISSUE TITLE
Can't import SimulationCraft script: Unable to find spell

### ISSUE THREAD

**Issue by fabriciomind** [Sidoine/Ovale#338]
https://pastebin.com/cFa6dHcV

Using SimulationCraft version 725-01.
Last Ovale version 7.2.4.0

`OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'rune_of_power'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fireball'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'dragons_breath'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'scorch'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'rune_of_power'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Variable 'firestarter.active' is not implemented.
OvaleSimulationCraft: Warning: Unable to find spell 'fireball'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'scorch'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fireball'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'scorch'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fireball'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'scorch'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'fire_blast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'phoenixs_flames'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'pyroblast'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).
OvaleSimulationCraft: Warning: Unable to find spell 'flamestrike'
OvaleSimulationCraft: Warning: Unable to determine tag for 'UNKNOWN', assuming 'main' (actionType: spell).`

**Comment by Sidoine** [comment]
Should be solved
