### ISSUE TITLE
Issues with Guardian Druid Script

### ISSUE THREAD

**Issue by tehmufifnman** [Sidoine/Ovale#345]
It seems like it suggestions Frenzied Regen when I don't have enough rage to cast it, or while it doesn't have any charges.

It may have something to do with this legendary.
http://www.wowhead.com/item=137025/skysecs-hold

As well as the current Guardian tier 20 bonuses.
http://www.wowhead.com/item=147133/stormheart-tunic&bonus=3561:1482

```
(2) Set (Guardian): The cooldown of Frenzied Regeneration is reduced by up to 40%, based on your current health when you use it. Cooldown is reduced more when used at lower health.
(4) Set (Guardian): The cooldown of Frenzied Regeneration is reduced by 1 sec for every 20 Rage you spend.
```

Aside from those issues, it also seems to suggest Frenzied Regen WAY more often than it should, and Ironfur not NEARLY enough?  That is just how it "feels" in practice.

I have no idea if you have or not, but might look at https://www.icy-veins.com/ to see if there are any changes work making.

Thank you all for your hard work and such an amazing addon!  Is there anywhere I can buy you a beer?

**Comment by Sidoine** [comment]
Is it fixed in the beta version?

**Comment by tehmufifnman** [comment]
I have not been using the beta yet because Kevindesmet's 7.3.2 Guardian Druid script has not been brought into core Ovale.
