### ISSUE TITLE
[7.2.4.1] "Casting()" condition not working properly

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#346]
Condition not working for "player"target parameter (or blank), but working properly with "target" target parameter
Not working:
if Casting(demonbolt) spell(demonbolt)
if player.Casting(demonbolt) spell(demonbolt)

Working:
if target.Casting(demonbolt) spell(demonbolt)

**Comment by Sidoine** [comment]
It's not a bug. Ovale shows the action at the end of the current cast and, at the end of the cast, the cast will have ended.
