### ISSUE TITLE
Frame rate drops when targeting

### ISSUE THREAD

**Issue by rayzorback33** [Sidoine/Ovale#348]
I recently got a new laptop and installed WoW along with all my addons. I noticed a drop in my frame rates by about 20 when I target something. Through enabling and disabling each addon I found out that Ovale was causing the problem. Is there a fix for this? I didn't have this problem on my previous laptop. I also don't have any of the boxes checked for ovale's visibility.

**Comment by ShmooDude** [comment]
Which script spec are you using?
