### ISSUE TITLE
Unholy DK APL Varliables

### ISSUE THREAD

**Issue by Bingo176** [Sidoine/Ovale#351]
Looks like they changed some of the variables for the Unholy DK APL. I tried looking through a bunch of the lua files to see if it would be an easy fix but does not look like it. 

Importing the T20 APL gives 
![untitled](https://user-images.githubusercontent.com/25187247/29952703-f9f5e66e-8e7f-11e7-8fbb-f7952eee4e87.png)

Some looks like all new logic. Unsure if it's even something to look into?

**Comment by Sidoine** [comment]
T20 scripts are not supported yet.
