### ISSUE TITLE
Simulation Script import breaks addon

### ISSUE THREAD

**Issue by Dimmn** [Sidoine/Ovale#353]
I'm not sure if this mod is dead now. If so is a shame. Such a great addon.

Whenever I import the simc_gui script to ovale it breaks the mod. I really enjoyed using this mod, please keep it alive!

**Comment by kevindesmet** [comment]
which script?

**Comment by Dimmn** [comment]
When you sim your character there's a simc_gui thats in the simulation craft folder. You copy the text and import it into ovale/simulationcraft/input Then you click on Output and that script is what you put into the Custom Script of Ovale which will show you the exact rotation simulation craft used. This is broken.

**Comment by ShmooDude** [comment]
You're gonna have to get more specific.  Exactly what script are you trying to paste in and what error are you getting?  Post it in a pastebin or something.

**Comment by Sidoine** [comment]
T19 scripts should import in beta version
