### ISSUE TITLE
Balance Druid Moonkin Form script/rotation broken.

### ISSUE THREAD

**Issue by velveteenheart** [Sidoine/Ovale#354]
I am unable to use the addon in Moonkin form as Balance Druid. The addon tells me to spam two abilities - Half Moon and Lunar Strike, and only suggest a possible variant in rotation when I press a random bound abilities. It then becomes stuck on the last spell I have used. It works fine outside of Moonkin form; nothing seems irregular there. Also, I have noticed I must click a script to sort of 'activate' the addon when logging into the Balance character. It works for Feral and Guardian, even Resto.

I removed other addons and used this on a clean install - and same, it did not work. The issues began after the last update, a week or so ago.

**Comment by velveteenheart** [comment]
Still no fix. Any help?

**Comment by velveteenheart** [comment]
I am using the default script. It's odd, because the problem only occurs in moonkin form. I have tried everything that I am capable of doing (switching between scripts, reloading ui, loading only a few addons, deleting addons, making sure weakauras/elvui/vuhdo scripts are up-to-date) but nothing seems to fix it. I don't know what to do.

**Comment by Araldwenn** [comment]
I've got exactly the same issue. I'm using v7.1.8.1 (i'm playing on private server which is 7.1.5).

**Comment by Sidoine** [comment]
I'm unable to reproduce this bug. Please check if it works with the beta version.
