### ISSUE TITLE
Warlock affliction issues with 7.3.0.2 version

### ISSUE THREAD

**Issue by orchid666** [Sidoine/Ovale#356]
I noticed two issues for Affliction with the last Ovale script:

- Long CD Soul Harvest is never suggested when talent is taken
- Seed of corruption is suggested even if Im out of soul shards.

Thanks!

**Comment by orchid666** [comment]
Am I the only one to have those issues?

**Comment by Sidoine** [comment]
Should be fixed in beta4+
