### ISSUE TITLE
input Hunter_beast_mastery_t20h.simc, 7 errors; Hunter_marksmanship_T20H.simc, 2 errors

### ISSUE THREAD

**Issue by zzyyj** [Sidoine/Ovale#360]
===========Beast_mastery-=============
Warning: Variable "full_recharege_time" is not implemented.
Warning: Variable "full_recharege_time" is not implemented.
Warning: symbol "call_of_the_wild' not defined
Warning: symbol "one_with_the_pack_talent' not defined
Warning: symbol "parsels_tongue' not defined
Warning: symbol "parsels_tongue_buff' not defined
Warning: symbol "qapla_eredun_war_order' not defined

===========Markmanship===============
Syntax error: unexpected token 'value_else' when parsing action line; expression keyword expected
Next tokens: = debuff.vulnerability.remains, condition = talent.sidewinders.enable & cooldown.sidewinders.full_recharege_time < variable.vuln_window <EOS>

Anyone help to solve thes issues?

**Comment by zzyyj** [comment]
Ovale and simulationCraft just download the last version today.

**Comment by orchid666** [comment]
Same issue here, its been a while so not sure if they are coming with a fix

**Comment by Sidoine** [comment]
Should be fixed in beta version
