### ISSUE TITLE
Destruction warlock 7.3 APL Symbol issues

### ISSUE THREAD

**Issue by Gorilladeez** [Sidoine/Ovale#362]
Hi there, I've recently started using this addon and tried to import the current SIMC APL from the addon when I do that I am getting "Warning: Symbol" errors. Here's a screenshot: 
<a href="https://imgur.com/F9NObnA"><img src="https://i.imgur.com/F9NObnA.png" title="source: imgur.com" /></a>

Any idea why?

**Comment by Sidoine** [comment]
Could you try the beta5 please?
