### ISSUE TITLE
Combo Points Don't appear to be tracking

### ISSUE THREAD

**Issue by bradleygill** [Sidoine/Ovale#373]
After a lot of testing and changing things around, the addon doesn't seem to be tracking ComboPoints anymore for the feral druid.  I haven't had the chance to test it with the Rogue yet, but I imagine it could be similar.  I looked through as much as I could find everywhere on the webs and couldn't find where anyone else has submitted this information.

All of the scripts supplied as well as a modified SimCraft generated script don't seem to be operating.

When attacking Shred will come up all the time with no finisher (rip), however, if I use rip once, the addon will then pop out of default actions and then use shred until the debuff tick time gets low on rip, then trigger ferocious bite, no matter what the combo points are at (tested at 1, 2, 3, 4, and 5.).

It just seems as though it's seeing the debuff, but unable to count the current combo points.

**Comment by bradleygill** [comment]
Nevermind...   all I have to do is open my eyes and look a little harder in the ticket list.  I see it just a few tickets down...  Sorry for wasting bandwidth.

**Comment by Sidoine** [comment]
Did you try beta4 ?
