### ISSUE TITLE
Assassination Rogue miss spells

### ISSUE THREAD

**Issue by Linkten** [Sidoine/Ovale#374]
Hi !

I don't know why but when i play my rogue with assassination specialisation, ovale just ask me to be stealth and he don't ask me more, i mean, no more spell appear in the ovale bar.

The addon work perfectly with outlaw and subtlety.

I tried with custom script, general script and with ur "live" version and beta 3 - 4.

Can you help me ?

**Comment by Linkten** [comment]
Actually, the assassination rogue have the same problem with beta5.

**Comment by Sidoine** [comment]
I don't know, it works with my own character. Maybe it's the talents that differ?

**Comment by Linkten** [comment]
Maybe yes, i'm not 110 actually. I tried with a "sesame" rogue and it seems to work. Thanks for your work.

Btw i'm a main feral and i don't know if you see the update of my thread but feral drood don't work with the beta :/  He just ask me to use my stealth and my ashamane. No more spells appear.

Keep the good work !

**Comment by Linkten** [comment]
With the new update of Ovale, the assassination rogue have again a problem :/

He just ask me to spam my Fan of knives and my Envenom
