### ISSUE TITLE
Nil value error occurring with beta 4

### ISSUE THREAD

**Issue by Ookami313** [Sidoine/Ovale#375]
Updated to beta 4 and now are getting the following error when logging in.  Ovale does not seem to function either. Thanks.

`Date: 2017-11-27 20:52:57
ID: 1
Error occured in: Global
Count: ∞
Message: ..\AddOns\Ovale\dist\Power.lua line 143:
   attempt to perform arithmetic on field '?' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   Ovale\dist\Power.lua:143: PowerCost()
   Ovale\dist\Power.lua:252:
      Ovale\dist\Power.lua:243
   (tail call): ?
   Ovale\dist\Data.lua:415: CheckSpellInfo()
   Ovale\dist\Spells.lua:127: IsUsableSpell()
   Ovale\dist\BestAction.lua:198:
      Ovale\dist\BestAction.lua:169
   (tail call): ?
   Ovale\dist\BestAction.lua:271: visitor()
   Ovale\dist\BestAction.lua:791: RecursiveCompute()
   Ovale\dist\BestAction.lua:772: PostOrderCompute()
   Ovale\dist\BestAction.lua:743:
      Ovale\dist\BestAction.lua:733
   (tail call): ?
   Ovale\dist\BestAction.lua:498: visitor()
   Ovale\dist\BestAction.lua:791: RecursiveCompute()
   Ovale\dist\BestAction.lua:772: PostOrderCompute()
   Ovale\dist\BestAction.lua:743:
      Ovale\dist\BestAction.lua:733
   (tail call): ?
   Ovale\dist\BestAction.lua:498: visitor()
   Ovale\dist\BestAction.lua:791: RecursiveCompute()
   Ovale\dist\BestAction.lua:772: PostOrderCompute()
   Ovale\dist\BestAction.lua:743:
      Ovale\dist\BestAction.lua:733
   (tail call): ?
   Ovale\dist\BestAction.lua:498: visitor()
   Ovale\dist\BestAction.lua:791: RecursiveCompute()
   Ovale\dist\BestAction.lua:772: PostOrderCompute()
   Ovale\dist\BestAction.lua:743:
      Ovale\dist\BestAction.lua:733
   (tail call): ?
   Ovale\dist\BestAction.lua:724: GetAction()
   Ovale\dist\Frame.lua:154:
      Ovale\dist\Frame.lua:122
   (tail call): ?
Locals:
(*temporary) = 1.2690000534058
(*temporary) = <function> defined =[C]:-1

AddOns:
`

**Comment by Sidoine** [comment]
What is the class of your character?

**Comment by Ookami313** [comment]
I'll have to re-download and install B4 again since I reverted back to a previous version after the error occurred. Off the top of my head, I want to say all of my characters were experiencing the error. I want to  say at the least my DK, DH, and Monk. I'll try to remember to verify when I get home and update,

**Comment by Ookami313** [comment]
Ran through my characters and the only errors that occurred were for my Monk and Mage with B4. I had thought it occurred for all of them. Updated to B5 and the error on seems to occur for my Monk now. Hope that helps.
