### ISSUE TITLE
Affliction lock 7.3.3 - Rotation is still not working properly with any scripts.

### ISSUE THREAD

**Issue by azarielrdm** [Sidoine/Ovale#386]
-It's recommending to use Reap Souls when you have ANY charges.. you're supposed so save them up to at least 5-6 in most situations so you can unleash 4-5 unstable afflictions during its duration.
-It's not signalling to use the filler spell "drain soul"
-It's flashing to use unstable affliction with no charges
     -in more detail... i have one unstable charge, it flashes to use it, you do so and it's still flashing it while it's being cast, which tells the player that is the next thing you need to do, hit unstable affliction again, but there's no charge to do so.

Reverting back to 7.3.0.3 as it's still the only version affliction works properly

**Comment by jgleigh** [comment]
I just get errors on my Affliction Lock when logging in:

Date: 2017-12-09 10:54:48
ID: 1
Error occured in: Global
Count: 4
Message: ..\AddOns\Ovale\dist\Compile.lua line 514:
   attempt to call global 'AddToBuffList' (a nil value)
Debug:
   Ovale\dist\Compile.lua:514:
      Ovale\dist\Compile.lua:483
   Ovale\dist\Compile.lua:538:
      Ovale\dist\Compile.lua:526
   Ovale\dist\Compile.lua:656: EvaluateScript()
   Ovale\dist\Frame.lua:132:
      Ovale\dist\Frame.lua:122
   (tail call): ?

Date: 2017-12-09 10:54:49
ID: 2
Error occured in: Global
Count: ∞
Message: ..\AddOns\Ovale\dist\Frame.lua line 176:
   attempt to index local 'action' (a nil value)
Debug:
   Ovale\dist\Frame.lua:176: UpdateActionIcon()
   Ovale\dist\Frame.lua:162:
      Ovale\dist\Frame.lua:122
   (tail call): ?

**Comment by Sidoine** [comment]
@azarielrdm Version 7.3.3 should have fixed your bug, is it the case?
@jgleigh This bug will be fixed in version 7.3.5

**Comment by azarielrdm** [comment]
I just tried 7.3.5 and it's still not working right.  It calls for reap souls at top priority even if it only has a single charge.  The moment you get another charge it wants to eat it immediately.  It also will spellflash for unstable affliction even if there's no charges but only if you just used one.  Say i have 1 charge, it will call to use it, then still flash the button when there isn't any charges so it doesn't do anything, you're hitting a dead button at that point. It's not usable in this state.  Even if you can work through that, it still "changes its mind" rapidly about what to use next so it's not effective as a rotation assistant.  I'm still having to use 7.3.0.3, the last version affliction was working properly.
