### ISSUE TITLE
Demonology Warlock: Script request

### ISSUE THREAD

**Issue by tressym69** [Sidoine/Ovale#39]
Sidoine, 
Thanks for updating the script it is working much better, couple of things I found that were still bugged.

Version: 7.0.14.0
Talents: Shadowy Inspiration, Improved Dreadstalkers, Demon Skin, Power Trip, Burning Rush, Grimoire of Synergy, Demonbolt
Script:  [7.0] Ovale Demonology Warlock

Issue 1:  Doom is not being suggested in the rotation at all.
Issue 2:  When your pet dies in combat instead of suggesting to cast your pet again, it keeps suggesting to cast Demonic Empowerment until you cast your pet.
Issue 3:  When you cast Summon Doomguard or Summon Infernal the next thing that should be suggested is Demonic Empowerment
Issue 4:  Need to add Cast Demonwrath if there are 5+ targets stacked around your demons, or while moving if you are above 60% Mana.

Thank you for your hard work.

Cheers!

**Comment by Sidoine** [comment]
The simulationcraft script has been updated, it should be correct now.
