### ISSUE TITLE
Windwalker Hit Combo+

### ISSUE THREAD

**Issue by Tanneseph** [Sidoine/Ovale#391]
One of the recent updates borked a couple of things on the Windwalker script.  The 2 major issues I've noticed is:

1) It is no longer suggesting SEF at all.  
2) It no longer avoids two of the same attacks in a row.  Specifically, it seems to be using Blackout Kick as some kind of filler, which is all kinds of wrong.

Repeating an ability and not using SEF at all (much less optimally) are the 2 worst ways to hamstring Windwalker DPS.  I truly hope adjustments can be made before this coming Tuesday, heh heh.

Otherwise, thank you for years of this addon.

**Comment by shanep2300** [comment]
I second on confirming these issues.

**Comment by Jierdan** [comment]
Still broken : (
