### ISSUE TITLE
Ovale for WW Monk

### ISSUE THREAD

**Issue by Dstain01** [Sidoine/Ovale#395]
Hi there, 

First I would like to say that I enjoy Ovale addon very much and its been very helpful since I reactivated my account. It's been a week since then and up till today. The Ovale addon is telling to hit the wrong abilities causing my mastery buff to fall off. It also is showing other abilities like Tiger palm on CD when they are not. So I figured I would post this. This could be a total user error and if so I would deeply appreciate a solution.

Thank you.

D'stain

**Comment by BatManv8v** [comment]
I am also having this issue.  Rolled back to 7.3.0.3 and all is good.

**Comment by Tanneseph** [comment]
BatManv8v, you are a god.  I opened a ticket here four days ago, and hadn't heard anything.  Did alright at the Tuesday raid, but I don't like playing without it, and was failing at mechanics I wouldn't've otherwise.  This fixed it, for now at least.  THANK YOU.

**Comment by Dstain01** [comment]
yeah thank you for the suggestion. It helped me as well.

**Comment by Jierdan** [comment]
Same here. : ( Plus Transparency-Issues.
