### ISSUE TITLE
Ret pally Rotation is missing Templar's verdict most of the time

### ISSUE THREAD

**Issue by Vallancer** [Sidoine/Ovale#396]
ever since the new update, Templar's verdict has not been showing on the ability bar unless i am in Avenging wrath.  This happens even when i am at full holy power.  If this was changed on purpose please go back to the way the rotation was before the update because it makes playing more of a hassle having to look how much holy power i have before I press Templar's verdict. Thank you

**Comment by Bassackerds** [comment]
I have the same issue. I have tried in the past to modify the codes to correct issues but always end up screwing it up.

**Comment by Bassackerds** [comment]
Is there someone that knows how to write the code willing to fix this issue please

**Comment by Sidoine** [comment]
It's how the simulationcraft script is written. I know it's annoying, I will try to add an option.

**Comment by billylekyd** [comment]
Is there any progress on this issue because I keep experimenting this problem. 

My Templar's Verdict never show on the spell bar, even when my Holy Power is full.
