### ISSUE TITLE
Spam error

### ISSUE THREAD

**Issue by serrufs** [Sidoine/Ovale#399]
http://jpegshare.net/images/bb/5e/bb5e861c910088918291d0009b4f059c.jpg

**Comment by serrufs** [comment]
7.3.6

**Comment by jgleigh** [comment]
Fatal error: [3605] Division by 0

This is on a druid with 7.3.6.

**Comment by Sidoine** [comment]
Is it related to a spec or a talent? Because I'm not able to reproduce this on my druid.

**Comment by serrufs** [comment]
http://jpegshare.net/images/11/06/1106341256d67832c70b34f197402b9b.jpg

**Comment by jgleigh** [comment]
What does the number in the error refer to? My druid is only level 100.

**Comment by noodlebud** [comment]
Fatal error: [3605] Division by 0 spammed on Feral Druid, when I switch specs to Guardian it stops.

**Comment by shqr** [comment]
Fatal error me too. MM, BM
