### ISSUE TITLE
UH DK - never suggests disease

### ISSUE THREAD

**Issue by nb41** [Sidoine/Ovale#403]
A UH DK is never prompted to cast outbreak in any of the recent releases. In the 7.3.0.3 script, Outbreak is the first suggestion, and then it is prompted for a recast any time it falls off. In the last handful of releases (including the fix for TickRemaining), it's not suggested at all. I'm not seeing any LUA errors.

**Comment by Ryladryl** [comment]
Thank you for letting me know which version still suggested Outbreak, this bug has been bothering me for a while.  I also have not had any LUA errors to go along with this bug.
