### ISSUE TITLE
DemonHunter Vengeance Rotation Failing

### ISSUE THREAD

**Issue by thunderchylde** [Sidoine/Ovale#413]
The Main and AOE icons show no actions after the latest update.

**Comment by thunderchylde** [comment]
After doing some digging it seems that anything that includes the SoulFragments() function is failing. Replacing it with a basic BuffStacks(#####) seems to work.

**Comment by Fringetastic** [comment]
Looking around for this problem, found this. Thunderchylde, do you mean to change "SoulFragments()" to "BuffStacks(SoulFragments)"?

**Comment by thunderchylde** [comment]
that's what I did yes, I don't know if there is other logic in the SoulFragments() function but BuffStacks(soul_fragments) seems to cover what I need it to.

**Comment by zalidthebur** [comment]
Which file are you making these changes in ?

**Comment by thunderchylde** [comment]
I was just making the change in a copy of the Vengeance script (copied to a custom script)
