### ISSUE TITLE
Timewalking Error

### ISSUE THREAD

**Issue by Bingo176** [Sidoine/Ovale#421]
When I joined timewalking and timewalking only I received this error. Received it on my DK as Blood and Frost. Script basically died and was suggesting spells without correct RP.

1x Ovale\dist\Power.lua:369: attempt to index local 'powerInfo' (a nil value)
Ovale\dist\Power.lua:369: in function `UpdateMaxPower'
Ovale\dist\Power.lua:348: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[3]"]:4: in function <[string "safecall Dispatcher[3]"]:4>
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\AngryAssignments\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil

**Comment by Darkmoded** [comment]
Error on Alpha 7.3.9 was well:  Playing demonology

Message: Interface\AddOns\Ovale\dist\Power.lua:394: attempt to index local 'powerInfo' (a nil value)
Time: 01/25/18 23:42:49
Count: 8
Stack: Interface\AddOns\Ovale\dist\Power.lua:394: attempt to index local 'powerInfo' (a nil value)
Current work around is /reload

Entering Time-walking spasms this Error ( have to /reload after entering dungeon , and everything is fine )
(Exiting the Time-walking spasms the same Error and having to repeat /reload)

**Comment by mwojtkowski** [comment]
it is the same bug when you join BG/Arena where UnitPowerMax will returning 0 for every type of power. There was condition to remove powerTypes with MaxPower == 0 which was causing this bug.

I changed that in fe592808865492d9cc104a2e0469a4179191bbd6 and it should be fixed
