### ISSUE TITLE
Alpha 7.3.9  Demons(creature_felguard) The demon count returns [0] for all Grimmore: service Demons

### ISSUE THREAD

**Issue by Darkmoded** [Sidoine/Ovale#423]
The following Demons(creature_felguard) > 0 always return 0 >> WildImps.lua is missing defined creatures

Define(creature_felguard 17252)
Define(creature_felhunter 417)
Define(creature_imp 416)
Define(creature_succubus 1863)
Define(creature_voidwalker 1860)

Current>>>>>>
local demonData = {
    [55659] = {
        duration = 12
    },
    [98035] = {
        duration = 12
    },
    [103673] = {
        duration = 12
    },
    [11859] = {
        duration = 25
    },
    [89] = {
        duration = 25
    }
}
My Mod >>>>>>

local demonData = {
    [55659] = {
        duration = 12
    },
    [98035] = {
        duration = 12
    },
    [103673] = {
        duration = 12
    },
    [11859] = {
        duration = 25
    },
    [89] = {
        duration = 25
    }
	--- Added >>>>>>>>
	[17252] = {
        duration = 25
    },
	[417] = {
        duration = 25
    },	
	[416] = {
        duration = 25
    },
	[1863] = {
        duration = 25
    },	
	[1860] = {
        duration = 25
    },
	--- <<<<<<<<<<<<<
}

**Comment by mwojtkowski** [comment]
I've added missing demons ids in b9fdc21db7c2999a26b27fce5f18fcb3c8e8fb6a
