### ISSUE TITLE
PreviousGCDSpell is broken

### ISSUE THREAD

**Issue by Conq1** [Sidoine/Ovale#424]
Added this to a comment below as well, but feel this title is more fitting.
PreviousGCDSpell for WindWalker Monk at least is always returning false.
Not sure if it actually returns false, but the result is as if it does. When I try to debug it looks more like the result is #inf, but not sure how the function works.
I haven't tested it with other classes yet, but will try and test with my Warlock, where this function is pretty important as well.

**Comment by Conq1** [comment]
Tested with my Warlock. Seems to work fine.
Tested with 7.3.9-Alpha on Monk. Doesn't work.

**Comment by BatManv8v** [comment]
It's not working for me ether.  Hope it will get sorted out soon.

**Comment by alarge** [comment]
It does not appear to work for my affliction warlock.  In particular, when I build logic around double-casting (or not double-casting) Unstable Affliction, it doesn't appear to recognize that UA was the previous spell cast.

**Comment by mwojtkowski** [comment]
it should be fixed with 
- 81b69b81738f67bae004e67a461f34efbb255238 - PreviousGCDSpell for instant casts/spells
- 6e8602fb59dbdb74c84ada905ee8207e7266f45f - ApplyPowerCost for spells like UA
