### ISSUE TITLE
Efficient Aura Tracking

### ISSUE THREAD

**Issue by Ophidon** [Sidoine/Ovale#431]
I have been looking into anything that could let Ovale work more efficiently, as it is by far my most demanding addon. And one thing I believe that could be of quite substantial benefit would be (perhaps an optional checkbox) to disable tracking of auras on party/raid members and their pets.

When profiling against a test dummy as I was originally doing, this problem wasn't as apparent, as only in an actual raid environment does scanauras come to equal and surpass time spent on ovalebestaction_compute. There might be a few specs that make decisions based on auras on group/raid units (thus the optional checkbox maybe..), but I believe the majority do not?

Also as a quick note there is a couple small bugs I found while profiling where ovalebestaction_compute profiling time is incorrect as there is a startprofiling at the bottom of postordercompute instead of a stopprofiling. And the ovale_unitchanged in health.lua has stopprofiling inside of an if statement which can manage to not get called.

All above is using 7.3.9-alpha.

**Comment by mwojtkowski** [comment]
By default Ovale was scanning auras using HARMFUL or HELPFUL flags which results in scanning auras of other players.

I've changed that to HARMFUL|PLAYER and HELPFUL|PLAYER so Ovale scans only for auras cast by player. It reduces scan time and is default setting in Ovale.

there is option to turn it back by going into Options > Advanced > Full buffs/debuffs scan

**Comment by Ophidon** [comment]
Will this continually check the returned raid buffs on everyone in the raid like Fortitude and AI if cast by the player using Ovale? Or the Azerite traits (and maybe trinkets, I'm unaware if any currently exist) that cast buffs on party members?

If not, perfect. If so, it's most certainly a large step in the right direction, but a third option to only track auras on the player, their own personal pet, and the target might get rid of even more overhead for the probable large majority of specs that just don't care at all about those auras.

Multi-dotting classes of course care about dots on more than just their current target, but I'm not sure Ovale can ever be a great solution for multidotters (by itself) anyway.
