### ISSUE TITLE
Unholy DK: pet.* functions not usable

### ISSUE THREAD

**Issue by alarge** [Sidoine/Ovale#437]
Currently with my Unholy DK, pet.Present() is only true when short-duration Shambling Horrors are up.  In particular, it evaluates false when only my abom is up.

Also, is there a way to ask if your gargoyle/dark arbiter is currently up?  There's no obvious buff that shows, so I would assume its in the same pet.* situation.  Maybe an argument to pet.Present that identifies the class of pet?

**Comment by Conq1** [comment]
I used to check for the CD of DA. And that way you can check if you cast it recently. 
With CoF that was hell though. :)

**Comment by s-paquette** [comment]
There is no way to check for DA/Gargoyle in the API. The closest you can get is to scrape the combat log for the event which fires when you cast the spell, record that in a mod variable, then begin a a countdown based on their tooltip duration+3-5s grace period to run the spawn animation. At the end of that countdown, set the variable back to false.

**Comment by nb41** [comment]
There's no way to check for DA/Gargoyle in the API. The way it's typically done eg. in WeakAuras is you scrape the combat log for the spellcast event when you fire off the spell, and when you see it set a mod-local variable to true and start a countdown for the duration of the pet plus 5-6s for spawn animation and positioning. At the end of that countdown, set the variable back to false.
