### ISSUE TITLE
Addon still in development ?

### ISSUE THREAD

**Issue by Ciolouse** [Sidoine/Ovale#439]
Greetings,

Is this really awesome addon still in development ?
2 months without any modifications.

Please Sidoine, come back for us !!!!

Je ne peux pas jouer sans cet addon indispensable !!! Reviens parmi nous Sidoine, la communauté WoW a besoin de toi !  :D

**Comment by Dstain01** [comment]
Sidoine

What will it take to make this addon amazing again. Time? Money? Support (emotionally)? Just lets us know,

**Comment by Sidoine** [comment]
Time :)
