### ISSUE TITLE
Vengeance Demon Hunter LUA errors

### ISSUE THREAD

**Issue by sparrowlab** [Sidoine/Ovale#441]
I get the following error upon logging in or attempting to change which script my vengeance demon hunter is using. Ovale as a whole doesn't work when playing my DH.

Message: Interface\AddOns\Ovale\dist\conditions.lua:2483: attempt to index upvalue 'OvaleDemonHunterSoulFragments' (a nil value)
Time: Sun Apr 22 07:35:02 2018
Count: 1
Stack: Interface\AddOns\Ovale\dist\conditions.lua:2483: attempt to index upvalue 'OvaleDemonHunterSoulFragments' (a nil value)
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
Interface\AddOns\Ovale\dist\conditions.lua:2483: in function <Interface\AddOns\Ovale\dist\conditions.lua:2481>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:514: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:798: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:775: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:746: in function <Interface\AddOns\Ovale\dist\BestAction.lua:736>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:501: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:798: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:775: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:746: in function <Interface\AddOns\Ovale\dist\BestAction.lua:736>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:727: in function `GetAction'
Interface\AddOns\Ovale\dist\Frame.lua:154: in function <Interface\AddOns\Ovale\dist\Frame.lua:122>
(tail call): ?

Locals: errMsg = "Interface\AddOns\Ovale\dist\conditions.lua:2483: attempt to index upvalue 'OvaleDemonHunterSoulFragments' (a nil value)"
isTSMError = false
tsmErrMsg = nil
AceGUI = <table> {
 objPools = <table> {
 }
 RegisterAsContainer = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:521
 RegisterWidgetType = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:559
 WidgetBase = <table> {
 }
 RegisterAsWidget = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:537
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 GetLayout = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:583
 GetWidgetVersion = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:613
 Create = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:172
 GetWidgetCount = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:607
 GetNextWidgetNum = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:596
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 RegisterLayout = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:573
 Release = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:206
 ClearFocus = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:257
 WidgetContainerBase = <table> {
 }
 SetFocus = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceGUI\AceGUI-3.0.lua:247
}
TSM = <table> {
 Operations = <table> {
 }
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:398
 _author = "Sapu94"
 DeleteCustomPriceSource = <function> defined @Interface\AddOns\TradeSkillMaster\CoreAPI\Prices.lua:56
 EnableModule = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "TradeSkillMaster"
 IterateEmbeds = <function> defined @Interface\AddOns\ArkInventory\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:473
 CreateGroupTree = <function> defined @Interface\AddOns\TradeSkillMaster\GUI\TSMFrames\GroupTree.lua:291
 SecureHookScript = <function>

**Comment by Kalitzburgs** [comment]
Did you found any fix for this?
