### ISSUE TITLE
Ovale in BFA?

### ISSUE THREAD

**Issue by cerravox** [Sidoine/Ovale#451]
Will this addon continue through BFA? Please tell me it will?

**Comment by Tanneseph** [comment]
I echo this comment.  Frankly, the status of Ovale is always my greatest stress when big patches hit.

**Comment by nattycozy** [comment]
Yes please keep this going! If not, is there another addon that is similar?

**Comment by DamienM4194** [comment]
https://www.dropbox.com/s/7vb7h3slc6o70gc/Ovale.zip?dl=0 

i think i fixed it. seems to work fine and show stuff.

**Comment by mwojtkowski** [comment]
I'm updating spell definitions and just finished paladin ret/prot

you can check my repo or download this [Ovale.zip](https://github.com/Sidoine/Ovale/files/2218040/Ovale.zip)

**Comment by Brdrker** [comment]
Thanks for branching and updating. Star'd your branch.

**Comment by Tanneseph** [comment]
Thanks so much for undertaking this.  I can't imagine how huge is it after all of this!!

**Comment by fwater** [comment]
@mwojtkowski  
I also want to thank you for your update. I wouldn't play this game without your update. but still have a bug.When you enter the arena, if you do not  RELOAD, Ovale will go wrong. I'm using your latest version. I don't know if you have a test or whether you can fix it.

**Comment by Azpirinexl** [comment]
I still have a problem as Elemental Shaman... Ovale always propose me to cast my Totem Mastery even if he is already present

**Comment by Tanneseph** [comment]
Azp, they have to rewrite a ton of code because of the pre-patch.  It's going to be broken for a while.  The good news is that it IS being worked on.

**Comment by mwojtkowski** [comment]
@fwater I will add that to my TODO list
@Azpirinexl  that's because I didn't updated Shaman spells yet
I've updated Paladin, Monk, DK next will be DH

**Comment by Gessolady** [comment]
Thank you for all your hard work everyone who is working on this, it is much appreciated! Will the finished addon be uploaded to Twitch/Curse when finished?

**Comment by Basil22** [comment]
Thank you much for keep working, we need Ovale badly before BFA's start :)

**Comment by Brdrker** [comment]
@mwojtkowski Where do we submit bugs to you for testing (currently getting some errors on Ret Pally. Granted I may not be "checking out" your code properly as well. I'm just going to your page and "download" what you got.

**Comment by mwojtkowski** [comment]
you get lua errors on paladin ?

**Comment by Brdrker** [comment]
I was, yes. But it's also possible the way I'm picking it up is wrong (I'm not sure just downloading from your branch and replacing my existing Ovale folder is the appropriate way but it WAS the way I did it). If you want me to post LUA errors here, I can. I was just thinking it was more appropriate to put them where you work. Just let me know.

**Comment by mwojtkowski** [comment]
I enabled Issue reporting in my repo so if you have problems with my fork please post it there

**Comment by Brdrker** [comment]
I will do a fresh pull of your fork and then go test again and let you know. The problem was a "missing" library (I moved the old Ovale into a "backup" folder and took yours as is). Will update in your branch.

**Comment by melina3** [comment]
sadly does not work for my dk.does not flash at all.any suggestions pls?

**Comment by Brdrker** [comment]
@melina3 What spec?

**Comment by melina3** [comment]
@Brdrker frost dk

**Comment by Brdrker** [comment]
@melina3 Using @mwojtkowski work (I remove the entire Ovale folder contents and replace it with his release contents), I spec'd into Frost (and, granted, my DK is only 100). The build I took for Frost was from wowhead's 8.x build out to maximize single DPS (the two tiers that are not specified, I just picked something that seemed to make sense). Swords are runeforged with the top two selections, a different one for the main hand and the other on the offhand - sorry, don't play DK that much so I don't remember these off the top of my head - razorice and fallen crusader, IIRC).

I had a go at the training dummy in Ironforge for a good 5 minutes to get the single and multi-target flow down and I had no LUA errors at all.

**Comment by Jevnaker** [comment]
i am getting ovalecompile (unknown spell with id xxxx used in spelll xxxx) and i am not sure how to fix it.

**Comment by Brdrker** [comment]
@Jevnaker Only a small subset of Ovale "spells" have been updated by @mwojtkowski 

> If you get lua errors it is probably caused by outdated spell definitions
> As for spells I've updated
> 
>     Death Knight
>     Demon Hunter
>     Monk
>     Paladin
>     all above have imported simc profiles

See this update here: 

> https://github.com/mwojtkowski/Ovale/releases

Otherwise, you are going to have to (a) import the simc for your class/spec and (b) update it's associated spells.
