### ISSUE TITLE
Post patch 8 - artifact weapon greyed out

### ISSUE THREAD

**Issue by iBigs** [Sidoine/Ovale#452]
After the patch on some of my toons, the artifact weapon is greyed out and if unequipped it can't be equipped again. I narrowed the problem to Ovale, but I have no idea why this occurs.
Is that something you can look into?

I read somewhere that it may have something to do with LibArtifactData and that the addon needs to be updated in order for it to work again.

**Comment by Sidoine** [comment]
Should be fixed
