### ISSUE TITLE
Got mine to work (so far) !! Updated again 7/29/2018

### ISSUE THREAD

**Issue by Volgrath** [Sidoine/Ovale#453]
I made the following changes to Power.lua, PaperDoll.lua, and Aura.lua in the \dist\ folder, and so far It is working.

Power.lua changes: edited lines 37 thru 66 to reflect changes to SPELL_POWER_'Type' constants.
                                UNIT_POWER event name updated to UNIT_POWER_UPDATE

PaperDoll.lua changes: removed all references to multistrike.

Aura.lua changes: line 750 updated to reflect new order/number of variables in UnitAura function.

[Updated_Files.zip](https://github.com/Sidoine/Ovale/files/2230433/Updated_Files.zip)

**Comment by Kanjieu** [comment]
Thank you a lot Volgrath, it works for me!
