### ISSUE TITLE
BM Hunter talents Errors

### ISSUE THREAD

**Issue by meecho216** [Sidoine/Ovale#456]
I installed the latest version 8.0.0-alpha
I'm receiving "OvaleCompile:Warning: unknown talent ID '%s' in my chat 
Thanks for updating Ovale

**Comment by jgleigh** [comment]
8.0.1-alpha has the same error

**Comment by Conq1** [comment]
[Ovale_Hunter_BM.txt](https://github.com/Sidoine/Ovale/files/2275889/Ovale_Hunter_BM.txt)

**Comment by mwojtkowski** [comment]
Hunter was updated in 605b1ee65af1dd0fc890d51015e71c58ba5ba1ff
