### ISSUE TITLE
Can't find icon group

### ISSUE THREAD

**Issue by Tanneseph** [Sidoine/Ovale#466]
Just downloaded the alpha today, and I'm having a problem that does crop up for me every once in a while.  I've confirmed the addon is enabled in-game, but I can't find the icon group anywhere.  This is a fresh install, so I'm not sure what the deal is.  In the past, if this somehow happens, I reinstall the addon, so I don't know what to do when it is from scratch, heh.

Related suggestion: Any chance the options menu could include something like "reset group position" or "move to center of screen."  Just thinking out loud.

**Comment by mwojtkowski** [comment]
Could you tell me with which specialization/class you get that problem with or is it on all of your toons ?
You can "reset" position by setting Horizontal/Vertical offset to 0 in Icon goup menu option

**Comment by Tanneseph** [comment]
I'm a monk, and I just confirmed that it's missing with all three specs.  I also checked that the offset was 0, and even moved those sliders around in the offchance that I'd see the icon group slide by, ha.

No luck.

**Comment by Tanneseph** [comment]
It's here for my Arcane Mage alt that I just logged into!  So that's some info.

**Comment by Tanneseph** [comment]
It's incredibly wonky, though.  I don't know if Arcane Mage isn't ready yet, or it's the fact that she's level 38, but the group goes blank when I go into combat.  I got ready to attack something with four charges good to go, and it didn't recommend Arcane Barrage, either.

Sorry about the multi-post.  Let me know if this info isn't useful, just trying to do what little I can.

**Comment by mwojtkowski** [comment]
Unfortunately Mage scripts are not updated so you will have errors/missing icons etc.  
But monk should work it was one of the first updated specs.

So from what I understand if you click on minimap icon and select script nothing happens ?
Can you make some simple custom script and see if icon shows up ?

Something like
```
Include(ovale_common)
Include(ovale_monk_spells)

AddIcon help=main specialization=windwalker
{
   Spell(tiger_palm)
}

AddIcon help=main specialization=brewmaster
{
   Spell(tiger_palm)
}

AddIcon help=main specialization=mistweaver
{
   Spell(tiger_palm)
}
```
