### ISSUE TITLE
Soulshards not working 100%

### ISSUE THREAD

**Issue by Conq1** [Sidoine/Ovale#467]
I have a problem with soulshards. Not sure if it is same issue as some of the other special power ones.
It seems it cant figure out how many shards I will have at the end of my cast.
Define(chaos_bolt 116858)
	SpellInfo(chaos_bolt soulshards=2)

**Comment by Conq1** [comment]
[Ovale_WarlockDestro.txt](https://github.com/Sidoine/Ovale/files/2275892/Ovale_WarlockDestro.txt)

**Comment by mwojtkowski** [comment]
After some debugging I found where was the problem. 

Any alternative power (soulshards, chi, holypower) check for ```this.next.power[powerType]``` in functions like SoulShards(), Chi(), HolyPower(), on non caster classes that use alternative power Rogue or Monk for example you wont notice this bug as almost all spells are instant but on caster classes Ovale will only update ```this.next.power[powerType]``` at the end of cast.
