### ISSUE TITLE
Ovale does not appear on screen in BFA

### ISSUE THREAD

**Issue by Tuniwalrus** [Sidoine/Ovale#476]
The moment BFA came out,  Ovale disappeared.  No settings whatsoever make it appear on the screen.  Only the mini map config exists;  but no Ovale.  Tried /ovale show,    tried "standalone options". Nothing works.  This is the latest version as per Twitch.  Is this just no longer a working/supported addon?

**Comment by Brdrker** [comment]
This usually means one of two things. Either (a) the spec is not currently supported or (b) you have not enabled the appropriate script for your spec. As the game has undergone a massive change and, as a result, Ovale has had to go through massive changes as a result of character action changes, your settings may have been reset to null as the script(s) that use to run may no longer be available for BfA.

**Comment by Brdrker** [comment]
![screenshot 2018-08-18 20 28 24](https://user-images.githubusercontent.com/21250895/44304277-75300980-a325-11e8-8523-d9b3e1199d06.png)

**Comment by Tuniwalrus** [comment]
Thanks.  Where do I get that script for importing?  I can't cut/paste a jpeg into the app.

**Comment by Brdrker** [comment]
It's part of the program. You don't import anything. You just select it from the pulldown. If your version doesn't have it, then it's not supported yet in the public release or you have a down-rev version.
