### ISSUE TITLE
Mage arcane error

### ISSUE THREAD

**Issue by daviongamer13** [Sidoine/Ovale#484]
8x Ovale\dist\Compile.lua:348: table index is nil
Ovale\dist\Compile.lua:348: in function <Ovale\dist\Compile.lua:323>
Ovale\dist\Compile.lua:630: in function `EvaluateScript'
Ovale\dist\Frame.lua:128: in function <Ovale\dist\Frame.lua:121>
(tail call): ?

Locals:
node = <table> {
 type = "spell_aura_list"
 rawPositionalParams = <table> {
 }
 keyword = "SpellAddBuff"
 positionalParams = <table> {
 }
 rawNamedParams = <table> {
 }
 nodeId = 2233
 name = "arcane_blast"
 paramsAsString = "205025=0 arcanecharges=-1 if_spell=205025"
 namedParams = <table> {
 }
 spellId = 30451
}
ok = true
spellId = 30451
positionalParams = <table> {
}
namedParams = <table> {
 arcanecharges = -1
 205025 = 0
 if_spell = 205025
}
keyword = "SpellAddBuff"
si = <table> {
 gcd = 0
 offgcd = 1
 aura = <table> {
 }
 require = <table> {
 }
 channel = 0
}
auraTable = <table> {
 HARMFUL = <table> {
 }
 HELPFUL = <table> {
 }
}
filter = "HELPFUL"
tbl = <table> {
}
count = 0
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 arcanecharges = -1
 205025 = 0
 if_spell = 205025
}
(for control) = "arcanecharges"
k = "arcanecharges"
v = -1
(*temporary) = nil
(*temporary) = "arcanecharges"
(*temporary) = nil
(*temporary) = "table index is nil"
__exports = <table> {
 OvaleCompile = <table> {
 }
}
TestConditions = <function> defined @Ovale\dist\Compile.lua:132
OvaleData = <table> {
 TAUREN_CLASSES = <table> {
 }
 PANDAREN_CLASSES = <table> {
 }
 BLOODELF_CLASSES = <table> {
 }
 spellInfo = <table> {
 }
 itemList = <table> {
 }
 STAT_SHORTNAME = <table> {
 }
 buffSpellList = <table> {
 }
 STAT_NAMES = <table> {
 }
 DEFAULT_SPELL_LIST = <table> {
 }
 itemInfo = <table> {
 }
 STAT_USE_NAMES = <table> {
 }
}
find = <function> defined =[C]:-1
kpairs = <function> defined =[C]:-1
checkToken = <function> defined @Ovale\dist\tools.lua:13
PARAMETER_KEYWORD = <table> {
 if_target_debuff = true
 if_buff = true
 if_spell = true
 if_equipped = true
 listitem = true
 help = true
 level = true
 if_stance = true
 checkbox = true
 pertrait = true
 talent = true
 text = true
 trait = true
 wait = true
 itemset = true
 specialization = true
 itemcount = true
}
tonumber = <function> defined =[C]:-1

**Comment by alarge** [comment]
Getting a very similar error with all the feral druid scripts.  I suspect there's a broader problem here.

**Comment by alarge** [comment]
Also, to be clear - this just started with 8.0.6.

**Comment by daviongamer13** [comment]
exactly with me too
