### ISSUE TITLE
Range failure indication in Ret Pally

### ISSUE THREAD

**Issue by Brdrker** [Sidoine/Ovale#489]
Once a target is selected (and even in battle), the following actions show a failed range check (if I understand the UI properly which I may not -- the '?' is red):

Wake of Ashes (spellID: 255937)
Inquisition (spellID: 84963)

While Wake of Ashes should definitely do a range check for dmg potential, Inquisition probably does not need it. However, in both cases, even when in immediate melee range, both show the RetPally is not close enough.

This was found in the latest release from Curse: 8.0.6

**Comment by Jkeller662** [comment]
I noticed this as well for the Fury Warrior Whirlwind when standing in melee range...

**Comment by mwojtkowski** [comment]
Wake of Ashes is declared twice in script and one has wrong spell id, for warrior whirlwind is declared only once with spell id for arms, fury has different spell id for ww

**Comment by Brdrker** [comment]
8.0.9 seemed to have fixed the WoA issues... but introduced a predilection of Crusader Strike (id: 55395) when it isn't even on cooldown. It's also not displaying the keybind. I've attempted repeated /reloadui but to no avail.
