### ISSUE TITLE
8.0.9 Errors

### ISSUE THREAD

**Issue by Genuvien** [Sidoine/Ovale#498]
OvaleCompile: No spellId for name lunar_strike

That is the error output thrown for all druid specs. Ovale does not show up currently for any druid spec.

---

Related specific to @ShmooDude custom script: https://pastebin.com/L44FLT5f

OvaleCompile: Info: improved_rake is not a parameter keyword in 'rake_debuff' spell_aura_list

**Comment by Genuvien** [comment]
OvaleCompile: Info: improved_rake is not a parameter keyword in 'rake_debuff' spell_aura_list

Still spamming quite a lot. The ovale now shows!

---
However the default(disabled) and simcraft option, the icons display, but are not showing a timer on abilities. 
The strange thing is now it's not taking the talents into consideration for the rotation, such as in cat form its telling me to Moonfire, even though I do not have Moonfire Talent selected.
Thanks man :)

**Comment by Genuvien** [comment]
Should of specified, the OvaleCompile: spam happens every time you shapeshift.

**Comment by Genuvien** [comment]
https://imgur.com/a/CkkDvOf

a picture if it helps any, lol. 

You're doing amazing btw!

**Comment by Sidoine** [comment]
Did you try 8.0.11?
