### ISSUE TITLE
spell crusader_strike does not work for retribution paladin

### ISSUE THREAD

**Issue by doneykoo** [Sidoine/Ovale#499]
crusader_strike: this spell never shows up correctly.
tested by script PR_Paladin_Retribution.

**Comment by doneykoo** [comment]
okay, I found the problem.
The new crusader_strike spell id seems to be 35395 now in 8.0 bfa.,
And there is also a line need to be removed: SpellInfo(crusader_strike unusable=1 talent=zeal_talent specialization=retribution), because the new talent 1 does not change crusader_strike anymore in 8.0 bfa.

**Comment by Brdrker** [comment]
Confirmed @doneykoo suggestion. I changed the CS SpellID and commented out the indicated line. CS, in my case, when it shows up in Ovale, now shows the proper keybind and doesn't dominate the spell rotation. I'm going back to my old bug and close it.

**Comment by Sidoine** [comment]
Fixed in 8.0.11
