### ISSUE TITLE
many errors occur during ApplySpellAfterCast, when option "Not in melee range" and "Two abilities" are both on

### ISSUE THREAD

**Issue by doneykoo** [Sidoine/Ovale#500]
I found the ApplySpellAfterCast even run for the arrow icon (the "Interface\\..."), when option "Not in melee range" and "Two abilities" are both on,
which leads to errors.
tested by script PR_Paladin_Retribution.

**Comment by ultijlam** [comment]
I feel like the two abilities option should be disabled for now until we've improved the state machine enough to make it work correctly.
