### ISSUE TITLE
errors when in group

### ISSUE THREAD

**Issue by shhfiftyfive** [Sidoine/Ovale#502]
with the recent update, my bugsack is yelling at me non-stop the moment i enter a group.

i'm not sure how to read this. maybe you can figure out what's wrong from it...

986x Ovale\dist\GUID.lua:278: Usage: UnitGUID("unit")
[C]: ?
Ovale\dist\GUID.lua:278: in function `UnitGUID'
Ovale\dist\Aura.lua:719: in function `ScanAuras'
Ovale\dist\Aura.lua:517: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
Ovale\dist\GUID.lua:192: in function `?'
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Sidoine** [comment]
It should be fixed in 8.0.10, did you try this version?

**Comment by shhfiftyfive** [comment]
yes. fixed.
