### ISSUE TITLE
Error in Compile.lua

### ISSUE THREAD

**Issue by firesgc** [Sidoine/Ovale#507]
In the file Compile.Lua the function "isTable()" is called in line 511. This function will be defined later in the same file (line 522), which can lead to an error. Furthermore, there seem to be OvaleData.spellInfos (in my case spellID 165822) that have neither the field stacking nor max_stacks defined. 

Therefore I have extended line 509 as follows:
isStacking = si and si.stacking and si.max_stacks and (si.stacking == 1 or si.max_stacks > 0)

**Comment by firesgc** [comment]
Something else: "define(death_strike 278223)" should use spellId 49998. At least that is the correct one from the spellbook

**Comment by mwojtkowski** [comment]
Yes everything between 
```
// THIS PART OF THIS FILE IS AUTOMATICALLY GENERATED
// ANY CHANGES MADE BELOW THIS POINT WILL BE LOST

//END
```
is autogenerated
