### ISSUE TITLE
Guardian Druid Thrash and Swipe keybindings not shown

### ISSUE THREAD

**Issue by duggelz** [Sidoine/Ovale#527]
Symptom: Thrash and Swipe icons show up in rotation, but keybindings are not shown.  The icons do flash if SpellFlashCore is installed, however.

Version: Ovale 8.0.20

Workaround: Change "Spell(thrash)" to "Spell(thrash_bear)" and "Spell(swipe)" to "Spell(swipe_bear)" in Guardian script.  Feral script already uses "thrash_cat" and "swipe_cat", and does not seem to have the same problem.

The SimulationCraft profiles for Guardian use "thrash" et al, and the profiles for Feral use "thrash_cat" et al, so perhaps that's the underlying problem, or perhaps there is some translation that needs to happen in the Ovale import process.

**Comment by duggelz** [comment]
And thanks for making this AddOn.

**Comment by Hemario** [comment]
@duggelz please note that these scripts are based on simc profile. More appropriate tank scripts are found in addon https://www.curseforge.com/wow/addons/ovale_tankscripts.

**Comment by duggelz** [comment]
Thanks for the tank scripts addon, seems to be working well
