### ISSUE TITLE
No bartender keybindings showing on ovale rotation

### ISSUE THREAD

**Issue by jgwallace3** [Sidoine/Ovale#534]
It hasn't worked for me for a while. I've tried using the 'keybindings' option and resetting the keys to no avail. Is this expected to work?

**Comment by shadofall** [comment]
was just playing around with it change line 89 of Addons\ovale\dist\ActionBar.lua to read as

name = "CLICK BT4Button" .. slot .. ":LeftButton"

its just an issue of a space where there shouldn't be one

**Comment by jgwallace3** [comment]
This fixed it for me. THANKS!

(There was a space between BT4Button and the end quote. I simply removed it as directed)
