### ISSUE TITLE
How to indicate icon should be "small icon" in custom script?

### ISSUE THREAD

**Issue by vanila4gorila** [Sidoine/Ovale#537]
Hello -

In the interface options, there is a small icon scale bar mentioned. I have been writing custom scripts for characters, and would like to add a couple small icons, but I am unable to find any examples of how this is denoted in the out of the box scripts. Is this a attribute I can denote when adding an icon in the custom script?

**Comment by Sidoine** [comment]
Hello,
You have to add the size=small option.
