### ISSUE TITLE
Control Undead Deathknight

### ISSUE THREAD

**Issue by Bingo176** [Sidoine/Ovale#543]
When using this spell it produced this error every time.

371x Ovale\dist\Runes-Runes.lua:190: attempt to perform arithmetic on local 'runicpower' (a nil value)
Ovale\dist\Runes-Runes.lua:190: in function `ConsumeRune'
Ovale\dist\Runes-Runes.lua:156: in function `ApplyRuneCost'
Ovale\dist\Runes-Runes.lua:142: in function `ApplySpellAfterCast'
Ovale\dist\State.lua:67: in function `ApplySpellAfterCast'
Ovale\dist\Future.lua:978: in function `ApplySpell'
Ovale\dist\Future.lua:1006: in function `ApplyInFlightSpells'
Ovale\dist\BestAction.lua:721: in function `StartNewAction'
Ovale\dist\Frame.lua:145: in function <Ovale\dist\Frame.lua:121>
(tail call): ?

Locals:
self = <table> {
 enabled = false
 current = <table> {
 }
 next = <table> {
 }
}
spellId = 111673
atTime = 1443300.435
snapshot = <table> {
 spellId = 111673
 critRating = 983
 damageMultiplier = 1
 baseDamageMultiplier = 1
 hasteRating = 508
 target = "Creature-0-3884-1763-12436-127757-00021D52FF"
 channel = false
 spellName = "Control Undead"
 attackPower = 6876
 offHandWeaponDPS = 0
 mainHandWeaponDPS = 0
 lineId = "Cast-3-3884-1763-12436-111673-00079D543C"
 masteryEffect = 27.027778625488
 masteryRating = 13.513889312744
 spellCrit = 19.65277671814
 targetName = "Reanimated Honor Guard"
 versatilityRating = 749
 stop = 1443300.435
 meleeCrit = 19.65277671814
 stamina = 10638
 queued = 1443299.166
 intellect = 794
 agility = 1219
 hastePercent = 18.217651367188
 meleeAttackSpeedPercent = 18.217651367188
 versatility = 8.8117647171021
 rangedCrit = 19.65277671814
 caster = "Player-9-031DD5CF"
 strength = 5507
 snapshotTime = 1443299.069
 spellCastSpeedPercent = 18.217651367188
 rangedAttackSpeedPercent = 18.217651367188
 start = 1443299.166
 spellPower = 794
}
consumedRune = <table> {
 endCooldown = 1443317.4969476
 startCooldown = 1443309.0379739
}
start = 1443309.0379739
duration = 8.4589736679337
runicpower = nil
(*temporary) = <table> {
 spellId = 111673
 critRating = 983
 damageMultiplier = 1
 baseDamageMultiplier = 1
 hasteRating = 508
 target = "Creature-0-3884-1763-12436-127757-00021D52FF"
 channel = false
 spellName = "Control Undead"
 attackPower = 6876
 offHandWeaponDPS = 0
 mainHandWeaponDPS = 0
 lineId = "Cast-3-3884-1763-12436-111673-00079D543C"
 masteryEffect = 27.027778625488
 masteryRating = 13.513889312744
 spellCrit = 19.65277671814
 targetName = "Reanimated Honor Guard"
 versatilityRating = 749
 stop = 1443300.435
 meleeCrit = 19.65277671814
 stamina = 10638
 queued = 1443299.166
 intellect = 794
 agility = 1219
 hastePercent = 18.217651367188
 meleeAttackSpeedPercent = 18.217651367188
 versatility = 8.8117647171021
 rangedCrit = 19.65277671814
 caster = "Player-9-031DD5CF"
 strength = 5507
 snapshotTime = 1443299.069
 spellCastSpeedPercent = 18.217651367188
 rangedAttackSpeedPercent = 18.217651367188
 start = 1443299.166
 spellPower = 794
}
(*temporary) = 1.1821765136719
(*temporary) = <table> {
 endCooldown = 1443309.0379739
 startCooldown = 1443300.579
}
(*temporary) = 1443309.0379739
(*temporary) = 1443300.435
(*temporary) = "attempt to perform arithmetic on local 'runicpower' (a nil value)"
__exports = <table> {
 OvaleRunes = <table> {
 }
}
RUNE_SLOTS = 6
IsActiveRune = <function> defined @Ovale\dist\Runes.lua:27
OvalePaperDoll = <table> {
 enabled = false
 current = <table> {
 }
 specialization = 1
 next = <table> {
 }
 SaveSpellcastInfo = <function> defined @Ovale\dist\PaperDoll.lua:196
 level = 120
 CopySpellcastInfo = <function> defined @Ovale\dist\PaperDoll.lua:193
 class = "DEATHKNIGHT"
}
OvalePower = <table> {
 enabled = false
 current = <table> {
 }
 PRIMARY_POWER = <table> {
 }
 next = <table> {
 }
 RequirePowerHandler = <function> defined @Ovale\dist\Power.lua:586
 POWER_INFO = <table> {
 }
 POWER_TYPE = <table> {
 }
 CopySpellcastInfo = <function> defined @Ovale\dist\Power.lua:589
 POOLED_RESOURCE = <table> {
 }
}

**Comment by Hemario** [comment]
Fixed in https://github.com/Sidoine/Ovale/commit/4090875474d7f621162cda770bbd80053411ea07
