### ISSUE TITLE
Ignore power requirement for spell?

### ISSUE THREAD

**Issue by vanila4gorila** [Sidoine/Ovale#553]
Hello -

I am looking for assistance to see if there is a function to ignore the power/buff requirement for a spell to have the icon display given a certain set of conditions. Scenario I am looking for this on is to have a glacial spike precast icon:

 #glacial spike precast
 #if PreviousGCDSpell(frostbolt) and BuffStacks(icicles_buff) == 4 and BuffPresent(brain_freeze_buff) Spell(glacial_spike)

Currently this is not displaying because @ the time I only have 4 icicles and am unable to cast Glacial Spike until I have 5; but, given the first line, I will have 5 once that Frostbolt finishes so want to begin precasting it.

Any assistance would be much appreciated!

**Comment by Hemario** [comment]
Trying to reproduce/investigate this with the following script:

```
Include(ovale_common)
Include(ovale_mage_spells)

SpellAddBuff(frostbolt icicles_buff=1)

AddIcon {
 Spell(glacial_spike)
 Spell(frostbolt)
}

```

What I would suspect, when I have 5 icicles, it would show glacial_spike. That works fine.

> +++ Icon 1
> Reset state with current time = 183828.596000
>     nextCast = 183828.596000
> [3029] >>> Computing 'action' at time=183828.596000: Spell(glacial_spike)
> [3029]    evaluating action: Spell(199786)
> Aura 205473 found on Player-1587-083E3365 with (183810.872, 183871.872)
>     Require aura 205473 with at least 5 stack(s) on player at time=183828.596000: passed
>    Has power 20000.000000 mana
>     Require 1.000000 mana at time=183828.596000: passed
> Didn't find an existing cd in next, look for one in current
> Call GetSpellCooldown which returned 0.000000, 0.000000, 1
> It returned -0.100000, 0.000000
> Spell cooldown is in the past
> Cooldown of spell 199786 is 0.000000 + 0.000000
> GetSpellCooldown returned 0.000000, 0.000000
> Spell cooldown is in the past
> Cooldown of spell 199786 is 0.000000 + 0.000000
> [3029]    Action 199786 is off cooldown.
> [3029]    start=183828.596000 atTime=183828.596000
> [3029]    Action 199786 can start at 183828.596000.
> [3029] <<< 'action' returns [3029] (183828.596, inf)
> [3046] >>> Computing 'action' at time=183828.596000: Spell(frostbolt)
> [3046]    evaluating action: Spell(116)
> Didn't find an existing cd in next, look for one in current
> Call GetSpellCooldown which returned 0.000000, 0.000000, 1
> It returned -0.100000, 0.000000
> Spell cooldown is in the past
> Cooldown of spell 116 is 0.000000 + 0.000000
> GetSpellCooldown returned 0.000000, 0.000000
> Spell cooldown is in the past
> Cooldown of spell 116 is 0.000000 + 0.000000
> [3046]    Action 116 is off cooldown.
> [3046]    start=183828.596000 atTime=183828.596000
> [3046]    Action 116 can start at 183828.596000.
> [3046] <<< 'action' returns [3046] (183828.596, inf)
> [4445] >>> Computing 'group' at time=183828.596000
> [4445]    group checking [3029]: (183828.596, inf) [3029]
> [4445]    group first best is [3029]: (183828.596, inf) [3029]
> [4445]    group checking [3046]: (183828.596, inf) [3046]
> [4445]    group best action 199786 remains (183828.596, inf)
> [4445] <<< 'group' returns [3029] (183828.596, inf)
> [3029]    using cached result (age = 128/128)
> GetAction: start=183828.596, id=199786
