### ISSUE TITLE
TOTEM MASTERY ISSUE

### ISSUE THREAD

**Issue by Jkeller662** [Sidoine/Ovale#555]
I listed this previously and it was just closed today.  I went back into the game and the issue has not been fixed.  When I drop my totems and start the rotation, sometimes, the totem icon does not change to the next spell that is suggested to be cast, which forces me to recast (Drop) my totems again in order to see the next spell to cast.  It almost seems as if there are two different Totem Mastery identifiers.  I say this because when I have my stance bar up, you can see when the totems are cast, the icon will move to the slot next to the previous slot it was in.  I have checked the identifier for the spell and it is in the script, however, the second identifier is not in the script and that is the issue.  I can not find the second id for the spell "Totem Mastery".  Please look closer at this issue because it is annoying to have to cast the spell twice before starting my rotation.
If you would like to contact me, please do so in order to better explain what is going on.

**Comment by Hemario** [comment]
In reference to #526.
The fix has been done, but a new release hasn't been uploaded yet.
If you are comfortable adapting the files, you can see the applied changes here: https://github.com/Sidoine/Ovale/pull/549/files

If not, please hold on for the next release.

**Comment by Jkeller662** [comment]
Version 8.0.24?

**Comment by Hemario** [comment]
Ok, I managed to (finally) reproduce your issue and you are indeed correct.
The code assumes Totem Mastery is in slot 1. This is true the first case, but the second time you cast totem mastery, it is placed in slot 2.

Expect a fix soon.
