### ISSUE TITLE
Unable to see rotation suggestion display

### ISSUE THREAD

**Issue by MrMane** [Sidoine/Ovale#56]
I updated my wow client yesterday and I can't seem to  get my Ovale to display anymore. I've tried reinstalling the mod but it still isn't displaying correctly. I encounter no error messages, could this be on my end?

**Comment by kevindesmet** [comment]
Can you check the options of the addon to see if the addon is in fact enabled and visible?
Also verify whether a script has been selected (and not just an empty script)

**Comment by ShmooDude** [comment]
I seemed to have this problem at one point too.  If you're using a custom script, try switching to the default one.  Of course when I tried to switch back it disappeared again so I think I had to just delete my settings file for Ovale and that fixed it.  Not sure what the issue was.

**Comment by MrMane** [comment]
@kevindesmet It seems to be related to my WTF Folder and/or Interface folder. I created a New WTF and Interface folder to try out a new UI (OwD) and installed Ovale and this is when I encountered this error. The Addon was enabled which I verified ingame since I only had the two mods but Ovale didn't show up. If I use the original WTF and Interface folders and install and enable only those two mods, then Ovale displays correctly with the OwD UI. It seems like something is missing but I can't tell what it is...

**Comment by kevindesmet** [comment]
That wouldn't make any sense to me that Bartender or Dominos are a prerequisite.
I have neither installed (I use ElvUI) and Ovale displays fine.

**Comment by MrMane** [comment]
I see the addon activated in the list but nothing is shown in the interface window. It only shows the "Game" tab. Maybe it shows when an actionbar replacement is used. With only the Ovale addon activated and everything else deactivated, does Ovale still show?

**Comment by kevindesmet** [comment]
Yes, Ovale should show in that list, even if it is the only addon available. It actually sounds like Ovale is active but cannot be loaded, probably due to a LUA error which is hidden to you. It could very well be a missing library.
Let me get back to you.

**Comment by kevindesmet** [comment]
It is in fact the case that there is a LUA error on login when you have Ovale as only addon. There is a missing library dependency on LibStub. As this is a very commonly used library, installation of any other addon would probably also add LibStub but for completeness we should add LibStub to the libs folder.

How to reproduce:
1. download the latest release 7.0.14.0 and install it into AddOns folder
2. on the character selection screen click on "AddOns" in the lower left corner of the screen
3. Disable all addons except Ovale
4. Login
5. /reload

==> a LUA error will be shown (same as reported before; see #33)

@Sidoine can you please update the package release script to include libs/LibStub/LibStub.lua

**Comment by kevindesmet** [comment]
@MrMane as a workaround you could also install LibStub addon seperately from Curse until the Ovale package has been fixed. [https://mods.curse.com/addons/wow/libstub](url)

**Comment by kevindesmet** [comment]
@Sidoine could it be that .pkgmeta is just case sensitive?
`libs/LibStub: svn://svn.wowace.com/wow/ace3/mainline/trunk/libstub` -->
`libs/LibStub: svn://svn.wowace.com/wow/ace3/mainline/trunk/LibStub`

**Comment by Sidoine** [comment]
This was the issue.
