### ISSUE TITLE
I want to know if there is any plan to support the version of BLIZZCON WOW CLASSIC 1.12

### ISSUE THREAD

**Issue by fwater** [Sidoine/Ovale#562]
I want to know if there is any plan to support the version of BLIZZCON WOW CLASSIC 1.12
Maybe many players will need it

**Comment by ultijlam** [comment]
That effort will have to wait until after WoW Classic is released and playable, and after there are some published rotations for each of the classes.

**Comment by Hemario** [comment]
I'm speaking for myself and not for @Sidoine but I'm sure we won't be providing support for the demo version of WOW Classic!

1. The demo is a limited time event. The demo will only be available from November 2nd to November 8th. The amount of effort that will be needed to refactor the Ovale engine to support both live and classic will be immense and not worth it for a demo that lasts 1 week.
2. The goal of the classic demo is to experience the game as it was in the classic era. Ovale wasn't created until WoTLK. It would thus make sense you experience classic without Ovale. That being said, that does not mean we won't provide support for classic in the future. I cannot wait to start development for that TBH :)
3. I did not buy a Blizzcon ticket so I cannot provide support, I'll just have to experience it through streams.

**Comment by Hemario** [comment]
From what I understood is that they will use current wow engine, but just apply the spell and aura database with values from classic (and disable all the QoL systems such as group finder, LFR, ...).
As such, the Ovale engine should be able to work pretty well. It's just the fact of implementing the data of those spells and auras and switching around multiple scripts that will be the dev challenge.
I could be completely wrong though :)

**Comment by fwater** [comment]
Many new players haven't played it, and it will open on August 26. Are there any plans to make this version?

**Comment by Sidoine** [comment]
Somebody can make a fork to support Classic
