### ISSUE TITLE
Chaman elementaire

### ISSUE THREAD

**Issue by JeedHome44** [Sidoine/Ovale#564]
Bonjour,
Pour le chaman élémentaire, ca affiche encore le sort pour poser les 4 totems alors qu'il est déjà posé, il doit y avoir un bug dans le script.

**Comment by Hemario** [comment]
Which version of Ovale are you using?

**Comment by Heracles44** [comment]
la dernière 8.0.25

**Comment by Hemario** [comment]
Could you please tell me how to reproduce it? When does it happen?
I haven't been able to since I applied my fix. Perhaps I'm still overlooking things.
