### ISSUE TITLE
Prêtre discipline

### ISSUE THREAD

**Issue by JeedHome44** [Sidoine/Ovale#565]
Bonjour,
Pourquoi n'a-t-on plus Ovale en prêtre discipline?
C'était très pratique à Legion d'avoir un coté heal et le coté multi pour dps... ca aidait beaucoup!

**Comment by Hemario** [comment]
Simc doesn't provide a dps profile for discipline priests, unfortunately.
The script we had in Legion was maintained in a custom script by me.

However, I no longer choose to maintain the custom scripts for classes I don't play. They might make a return but that will be in a similar addon compared to https://wow.curseforge.com/projects/ovale_tankscripts

**Comment by Heracles44** [comment]
dommage c'était bien pratique et je ne veux pas ajouter d'autres addon en plus...
si quelqu'un peut adapter le script que tu faisais ca serait super!

**Comment by Hemario** [comment]
There is no difference really between creating the script in Ovale or adding another addon. The performance impact should be negligible.
