### ISSUE TITLE
Raise Dead not showing for Unholy DK

### ISSUE THREAD

**Issue by vanila4gorila** [Sidoine/Ovale#569]
Raise Dead is not showing for Unholy DK using the default script.

I additionally tried custom code below:
 #summon ghoul
 if pet.IsDead() or not pet.Present() Spell(raise_dead)

The above was working prior to the 294e917 changes; looks like something in the update affected this.

**Comment by Hemario** [comment]
@vanila4gorila from my understanding you cannot cast the spell "Raise Dead" if you already have a pet up. 
A restriction was configured that raise_dead is not usable if your pet's health > 0.

Is this incorrect? If so, please elaborate so we can fix it.

**Comment by vanila4gorila** [comment]
Your understanding is correct; however, whatever was configured appears to be too restrictive - I am unable to get Raise Dead to show in any scenario, even without a pet and simply using a script to show that spell. For example, the below script is not showing Raise Dead when I have no pet and Raise Dead is not on cooldown:

#summon ghoul
Spell(raise_dead)

It seems that the Pet Health > 0 is evaluating to True somehow in all scenarios, even without a pet currently summoned.

As mentioned originally, this was working in previous builds - not sure if there is a way to incorporate the "pet.IsDead() or not pet.Present()" lines into raise_dead as mentioned in the original comment instead of the pet health > 0? These effectively accomplish the same thing and were working previously.

Please let me know if you need any more info - thanks!

**Comment by Hemario** [comment]
Did you pet die in combat and you want to icon to show in that same fight?
Or does this also happen when you are not in combat and you dismiss the pet?

**Comment by vanila4gorila** [comment]
The icon does not show in either case above.

The custom line I had in my script previously "if pet.IsDead() or not pet.Present() Spell(raise_dead)" used to show the icon in both of these scenarios.

**Comment by Hemario** [comment]
in any case, if it's blocking you for now, you can delete the following line in dist/scripts/ovale_deathknight_spells.lua to restore the functionality until we find a better fix.

`SpellRequire(raise_dead unusable 1=pet_health_pct,!0)`
