### ISSUE TITLE
Druid - Feral - compile warning for lunar_empowerment_buff

### ISSUE THREAD

**Issue by Fringetastic** [Sidoine/Ovale#576]
When using scripts as a feral, in feral form, with the balance affinity talent, warning messages are printed:

> [03:32:12] OvaleCompile: Warning: lunar_empowerment_buff is not a parameter keyword in 'lunar_strike' spell_aura_list
> [03:32:12] OvaleCompile: Warning: lunar_empowerment_buff is not a parameter keyword in 'lunar_strike' spell_aura_list
> [03:32:13] OvaleCompile: Warning: lunar_empowerment_buff is not a parameter keyword in 'lunar_strike' spell_aura_list
> [03:32:13] OvaleCompile: Warning: lunar_empowerment_buff is not a parameter keyword in 'lunar_strike' spell_aura_list

At line 429 in dist/scripts/ovale_druid_spells.lua, there's this chunk of code:
```
# Balance Affinity
Define(moonkin_form 197625)
	SpellInfo(moonkin_form to_stance=druid_moonkin_form)
	SpellInfo(moonkin_form unusable=1 if_stance=druid_moonkin_form)

	SpellAddBuff(lunar_strike lunar_empowerment_buff=0)

```
Commenting out line 434 ("SpellAddBuff(lunar_strike lunar_empowerment_buff=0)") stops the error, so I've been making and re-making this change with every release. Can you change ovale_druid_spells.lua to do this, to comment out that line?

**Comment by Fringetastic** [comment]
I should have included this link. The idea to comment out that line is Shmoo's. 
http://www.fluiddruid.net/forum/viewtopic.php?f=3&t=5709&sid=b14cd658feba8a472706941a11f8f269&start=875#p39108

That line is in two places (434 and ~520, iirc) and I tested it out this afternoon. I could leave line ~520 in and not get the error. I do not know if this affects balance druids.

**Comment by Hemario** [comment]
It shouldn't affect Balance druids, looking into it a bit. Try out the changes as proposed in https://github.com/Hemario/Ovale/commit/e482167d09ba21993d166332fb3ab2c10612f2ea and tell me if this looks ok to you.

**Comment by Fringetastic** [comment]
Sorry for the delay. Have been using for the past 30 minutes without a problem, seems good to me. Thank you!
