### ISSUE TITLE
New issue with affliction warlock script in 8.0.27

### ISSUE THREAD

**Issue by alarge** [Sidoine/Ovale#581]
Here's the stack:

Message: Interface\AddOns\Ovale\dist\BestAction.lua:759: attempt to index local 'element' (a nil value)
Time: Fri Oct 12 19:09:27 2018
Count: 2
Stack: Interface\AddOns\Ovale\dist\BestAction.lua:759: attempt to index local 'element' (a nil value)
Interface\AddOns\Ovale\dist\BestAction.lua:759: in function <Interface\AddOns\Ovale\dist\BestAction.lua:756>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:395: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:818: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:795: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:766: in function <Interface\AddOns\Ovale\dist\BestAction.lua:756>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:513: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:818: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:795: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:766: in function <Interface\AddOns\Ovale\dist\BestAction.lua:756>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:513: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:818: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:795: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:766: in function <Interface\AddOns\Ovale\dist\BestAction.lua:756>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:747: in function `GetAction'
Interface\AddOns\Ovale\dist\Frame.lua:150: in function <Interface\AddOns\Ovale\dist\Frame.lua:121>
(tail call): ?

Locals: self = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:389
 ComputeIf = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:593
 ComputeAction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:276
 ComputeLua = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:653
 ComputeState = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:665
 enabled = false
 ComputeGroup = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:539
 ComputeCompare = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:460
 ComputeCustomFunction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:507
 ComputeValue = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:682
 ComputeLogical = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:617
 ComputeFunction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:522
}
element = nil
atTime = 245091.23
timeSpan = nil
result = nil
(*temporary) = "OvaleBestAction_Compute"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'element' (a nil value)"
self_serial = 3
__exports = <table> {
 OvaleBestAction = <table> {
 }
}

**Comment by Hemario** [comment]
The culprit is this line in the profile
`actions.dots+=/siphon_life,target_if=min:remains,if=-spell_targets.sow_the_seeds_aoe<5&target.time_to_die>10&refreshable&!(cooldown.summon_darkglare.remains<=soul_shard*action.unstable_affliction.execute_time)`

Seems like Ovale can't handle -Enemies()
`if -Enemies() < 5 and target.TimeToDie() > 10 and target.Refreshable(siphon_life_debuff) and not SpellCooldown(summon_darkglare) <= SoulShards() * ExecuteTime(unstable_affliction) Spell(siphon_life)`

Replacing the `-Enemies()` to `Enemies()` no longer throws a LUA error.

Currently asking in simc Gibhub how to interpret `if=-spell_targets.sow_the_seeds_aoe<5`

**Comment by Hemario** [comment]
https://github.com/simulationcraft/simc/issues/4575

**Comment by fishcorn** [comment]
I can confirm that this fixes my affliction rotation. Probably worth turning it into a PR.

**Comment by Hemario** [comment]
It is part of https://github.com/Sidoine/Ovale/pull/584. It just hasn't been merged yet.
