### ISSUE TITLE
Serious Outlaw problem

### ISSUE THREAD

**Issue by MtMan1020** [Sidoine/Ovale#583]
First, thanks for trying to make the Outlaw perfect, but something has gone terribly wrong. Since the last update all Ovale want me to do is use stealth. When I stealth, it tells me to ambush. I ambush, it tells me to sinister strike, I do and it tells me to stealth. It happens weather Vanish is up or not. So basically it is useless.  It does it on all three scripts so I guess it is a core issue not a script problem.

**Comment by Hemario** [comment]
A fix has already been developed and is available here: https://github.com/Sidoine/Ovale/pull/579
It is however not yet published to curse, which should happen in the upcoming days
