### ISSUE TITLE
Ovale hijacked chat

### ISSUE THREAD

**Issue by vicki2810** [Sidoine/Ovale#585]
I don't know if this is a bug or something I've triggered. But when I downloaded the most recent version yesterday, my chat has been taken over by Ovale showing every detail in rapid real time, making it not only impossible to see real incoming messages but also a huge, rapidly moving distraction in the corner of my screen. How do I stop it?

**Comment by Hemario** [comment]
What spec are you playing? Can you post a screenshot?

**Comment by vicki2810** [comment]
Can I reply by email? This is a test...screen shot attached. You can
imagine though, when I'm in a dungeon it is just constantly and rapidly
moving with every spell I cast.

**Comment by vicki2810** [comment]
sorry - further to my last email and screenshot, this happens so far on my
boomie and shadowpriest

**Comment by vicki2810** [comment]
Sorry, I may be a bit thick here. And I do appreciate your help btw, but in
the only Ovale Interface I know of, I have options of
Icon group, Icon, Options, Two Abilities, Advanced, SpellFlash. And on the
right-click on icon, I don't see any debug options either.

**Comment by Hemario** [comment]
![image](https://user-images.githubusercontent.com/14911473/47113427-4ec11880-d259-11e8-8373-88ac3ad68093.png)
See the screenshot:
1. Click Ovale on the left side menu, open all the tabs
2. Click Debug
3. Click Options (if you need to, it will default to this view)
4. Disable all the checkboxes

**Comment by vicki2810** [comment]
Oh wow...this is really laying it out for me...THANKS! What a relief to have that scrolling text gone. I think the only way I would have enabled that text is that I was randomly doing some /ovale stuff, and at some point I would have used a word that I thought would do one thing, but did a whole other thing. Thanks again. The addon really helped my dps go up by about 20%. Tremendous tool.
