### ISSUE TITLE
Affliction Lock 

### ISSUE THREAD

**Issue by kataclyzmik** [Sidoine/Ovale#587]
With the Standard Single Target build, the addon suggests to cast haunt, but anything outside of haunt then goes completely blank in the boxes. No matter what build I change to it comes up blank after the initial spell. Destro and Demo both still work fine though.

**Comment by Hemario** [comment]
What is the standard single target build?

**Comment by spottsy** [comment]
Yeah same for me for ages had to go to another rotation helper on only my warlock.
