### ISSUE TITLE
Ovale going crazy with errors today

### ISSUE THREAD

**Issue by rwygand** [Sidoine/Ovale#588]
461x Ovale\dist\BestAction.lua:746: attempt to index field 'child' (a nil value)
Ovale\dist\BestAction.lua:746: in function `GetAction'
Ovale\dist\Frame.lua:150: in function <Ovale\dist\Frame.lua:121>
(tail call): ?

Locals:
self = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Ovale\dist\BestAction.lua:389
 ComputeIf = <function> defined @Ovale\dist\BestAction.lua:593
 ComputeAction = <function> defined @Ovale\dist\BestAction.lua:276
 ComputeLua = <function> defined @Ovale\dist\BestAction.lua:653
 ComputeState = <function> defined @Ovale\dist\BestAction.lua:665
 enabled = false
 ComputeGroup = <function> defined @Ovale\dist\BestAction.lua:539
 ComputeCompare = <function> defined @Ovale\dist\BestAction.lua:460
 ComputeCustomFunction = <function> defined @Ovale\dist\BestAction.lua:507
 ComputeValue = <function> defined @Ovale\dist\BestAction.lua:682
 ComputeLogical = <function> defined @Ovale\dist\BestAction.lua:617
 ComputeFunction = <function> defined @Ovale\dist\BestAction.lua:522
}
node = <table> {
}
atTime = 158905.219
(*temporary) = nil
(*temporary) = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Ovale\dist\BestAction.lua:389
 ComputeIf = <function> defined @Ovale\dist\BestAction.lua:593
 ComputeAction = <function> defined @Ovale\dist\BestAction.lua:276
 ComputeLua = <function> defined @Ovale\dist\BestAction.lua:653
 ComputeState = <function> defined @Ovale\dist\BestAction.lua:665
 enabled = false
 ComputeGroup = <function> defined @Ovale\dist\BestAction.lua:539
 ComputeCompare = <function> defined @Ovale\dist\BestAction.lua:460
 ComputeCustomFunction = <function> defined @Ovale\dist\BestAction.lua:507
 ComputeValue = <function> defined @Ovale\dist\BestAction.lua:682
 ComputeLogical = <function> defined @Ovale\dist\BestAction.lua:617
 ComputeFunction = <function> defined @Ovale\dist\BestAction.lua:522
}
(*temporary) = "OvaleBestAction_GetAction"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'child' (a nil value)"
variables = <table> {
 isState = true
 lastEnable = <table> {
 }
 isInitialized = false
 variable = <table> {
 }
 futureVariable = <table> {
 }
 futureLastEnable = <table> {
 }
}

**Comment by Hemario** [comment]
What class? What spec? Which script are you using?
