### ISSUE TITLE
RemainingCastTime()

### ISSUE THREAD

**Issue by devoxs** [Sidoine/Ovale#589]
Hello, 

Im using this condition to show the icon when cast finish in 1s but the icon is shown when cast finish. (I try to workaround latency with this. So it will show the next spell before cast finish, letting me pre-cast next spell

if target.InRange(shadow_bolt) and RemainingCastTime() <= 1
{
Spell(shadow_bolt)
}

**Comment by Sidoine** [comment]
Sorry, Ovale only display the info at the end of the current cast, and the remaining cast time will be 0 at the end of the current cast.
