### ISSUE TITLE
Question on Arms Warrior Victory Rush Cooldown doesn't show

### ISSUE THREAD

**Issue by zion563** [Sidoine/Ovale#591]
I am a novice here-I use Spellflash to have Victory Rush flash, but Ovale never shows to use it. I use it constantly when leveling fast. No big deal, I just thought it would suggest to use.

**Comment by Hemario** [comment]
Is the icon never showing or is spellflash not flashing?

**Comment by zion563** [comment]
The Ovale Icon never shows-spellflash working well flashes correctly. Funny I tried another addon that was similar (liked Ovale better) but it had the same issue. I was wondering if it was a Simulcraft whatever thing maybe

**Comment by zion563** [comment]
Spellflash is flashing perfectly for suggesting-no icon ever shows up however
