### ISSUE TITLE
Arcane Mage (Division By Zero)

### ISSUE THREAD

**Issue by jfox1980** [Sidoine/Ovale#606]
I'm not sure if this actually affects anything, but in the arcane mage rotation of a level 14 arcane mage, I get the following error when I'm pretty sure it should show the icon for Arcane Missiles when below 95% mana and having the clearcasting buff:

Ovale: [2717] Division by 0 in { 0 * total_burns() - 0 + GetStateDuration() } / total_burns

The Arcane Blast icon is still displayed after the error.

**Comment by flatluigi** [comment]
That might be part of the reason why it never seems to suggest missiles; hopefully this gets fixed
