### ISSUE TITLE
target.HasDebuffType(magic) not displaying proper image

### ISSUE THREAD

**Issue by jfox1980** [Sidoine/Ovale#609]
I'm playing a Shadow Priest. In `AddFunction ShadowSingleMainActions` I have added at the top of the code:

`if target.HasDebuffType(magic) Spell(dispel_magic)`

I've verified the spell has the correct ID in ovale_priest_spells.lua.

When targeting an enemy that I know I can debuff, the icon does not appear. I was suspicious this wouldn't work when my demon hunter was also not being presented with consume magic icons.

**Comment by Hemario** [comment]
Have you enabled "full buffs/debuffs scan" in options? The setting can be found in the Advanced section.
