### ISSUE TITLE
Frost DK: Unknown spell with ID potion used in Spell(potion).

### ISSUE THREAD

**Issue by kevindesmet** [Sidoine/Ovale#61]
Spell(potion) should probably translate into calling function FrostUsePotionStrength().

Does this only happen in Frost DK script?
Should the simc action "potion,type=draenic_strength" be translated differently?

**Comment by kevindesmet** [comment]
From first analysis it seems that the simc script has an issue.
It uses the type modifier while the name modifier is expected.

@Sidoine a couple of questions
1. where do you get the simc scripts? Are they an exact copy of what the simc community creates and no special actions added before import into Ovale?
2. do the Ovale scripts get generated each time the simc scripts are updated?

**Comment by kevindesmet** [comment]
https://github.com/simulationcraft/simc/issues/2795

**Comment by Sidoine** [comment]
It uses the scripts from their source code.
The translation code should support the two parameter names now.
