### ISSUE TITLE
Are there plans to make the version of BLIZZCON WOW CLASSIC 1.12

### ISSUE THREAD

**Issue by fwater** [Sidoine/Ovale#611]
Many new players haven't played it, and it will open on August 26. Are there any plans to make this version?

**Comment by Sidoine** [comment]
Hello. No, sorry, I don't have any plan to do this because I won't play WoW
classic but anybody is welcomed to fork the code.

**Comment by Noktam** [comment]
Arg, too bad, i loved your addon. I hope someone can fork it. (Even without all the premade script, and let us write our own)

**Comment by Hemario** [comment]
Thinking about it more and more, I'm not really sure if it is worth it. The rotation of most classes is so basic. It usually consists of 2 to 4 spells that should be used. There is a really limited amount of procs going on as well. The difficulty of your rotation is really not what makes wow classic hard.

**Comment by Noktam** [comment]
It's not only about rotation, you can write interesting script in order to conditionaly show spell on cooldownn tricket ...  It's a feature in find really usefull. I really don't need the 'simulcraft' part of ovale on wow classic, but i would love to still have ovale to write custom made profile.
