### ISSUE TITLE
bug LUA with Ovale Spell Priority 

### ISSUE THREAD

**Issue by Hiru1990** [Sidoine/Ovale#614]
page 1
Message: Interface\AddOns\Ovale\dist\Compile.lua:520: attempt to compare number with nil
Time: Tue Jun  4 14:06:58 2019
Count: 2
Stack: Interface\AddOns\Ovale\dist\Compile.lua:520: attempt to compare number with nil
Interface\AddOns\Ovale\dist\Compile.lua:520: in function <Interface\AddOns\Ovale\dist\Compile.lua:497>
Interface\AddOns\Ovale\dist\Compile.lua:546: in function <Interface\AddOns\Ovale\dist\Compile.lua:534>
Interface\AddOns\Ovale\dist\Compile.lua:659: in function `EvaluateScript'
Interface\AddOns\Ovale\dist\Frame.lua:128: in function <Interface\AddOns\Ovale\dist\Frame.lua:121>
(tail call): ?

Locals: buffId = 165822
statName = nil
isStacking = nil
si = <table> {
 aura = <table> {
 }
 duration = 10
 buff_cd = 65
 require = <table> {
 }
 stat = "haste"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
pairs = <function> defined =[C]:-1
OvaleData = <table> {
 TAUREN_CLASSES = <table> {
 }
 PANDAREN_CLASSES = <table> {
 }
 BLOODELF_CLASSES = <table> {
 }
 spellInfo = <table> {
 }
 itemList = <table> {
 }
 STAT_SHORTNAME = <table> {
 }
 buffSpellList = <table> {
 }
 STAT_NAMES = <table> {
 }
 DEFAULT_SPELL_LIST = <table> {
 }
 itemInfo = <table> {
 }
 STAT_USE_NAMES = <table> {
 }
}
find = <function> defined =[C]:-1
isLuaArray = <function> defined @Interface\AddOns\Ovale\dist\tools.lua:10
ipairs = <function> defined =[C]:-1
AddToBuffList = <function> defined @Interface\AddOns\Ovale\dist\Compile.lua:497

page 2

Message: Interface\AddOns\Ovale\dist\Frame.lua:172: attempt to index local 'action' (a nil value)
Time: Tue Jun  4 14:25:02 2019
Count: 31538
Stack: Interface\AddOns\Ovale\dist\Frame.lua:172: attempt to index local 'action' (a nil value)
Interface\AddOns\Ovale\dist\Frame.lua:172: in function `UpdateActionIcon'
Interface\AddOns\Ovale\dist\Frame.lua:158: in function <Interface\AddOns\Ovale\dist\Frame.lua:121>
(tail call): ?

Locals: self = <table> {
 visible = true
 OnCheckBoxValueChanged = <function> defined @Interface\AddOns\Ovale\dist\Frame.lua:472
 checkBoxWidget = <table> {
 }
 userdata = <table> {
 }
 actions = <table> {
 }
 type = "Frame"
 hider = OvalePetBattleFrameHider {
 }
 updateFrame = OvaleUpdateFrame {
 }
 LayoutFunc = <function> defined @Interface\AddOns\TomTom\libs\AceGUI-3.0\AceGUI-3.0.lua:600
 listWidget = <table> {
 }
 OnDropDownValueChanged = <function> defined @Interface\AddOns\Ovale\dist\Frame.lua:477
 content = <unnamed> {
 }
 events = <table> {
 }
 children = <table> {
 }
 frame = <unnamed> {
 }
 localstatus = <table> {
 }
 barre = <unnamed> {
 }
 timeSinceLastUpdate = Infinite
}
node = <table> {
 type = "icon"
 rawPositionalParams = <table> {
 }
 child = <table> {
 }
 positionalParams = <table> {
 }
 rawNamedParams = <table> {
 }
 nodeId = 4174
 paramsAsString = "checkbox=!opt_hunter_beast_mastery_aoe enemies=1 help=shortcd specialization=beast_mastery"
 namedParams = <table> {
 }
}
action = nil
element = <table> {
 asString = "Spell(bestial_wrath)"
 rawPositionalParams = <table> {
 }
 actionTexture = 132127
 actionCooldownDuration = 0
 actionTarget = "target"
 func = "spell"
 rawNamedParams = <table> {
 }
 lowername = "spell"
 actionShortcut = "R"
 paramsAsString = "19574"
 actionResourceExtend = 0
 result = <table> {
 }
 actionCooldownStart = 0
 actionIsCurrent = false
 type = "action"
 timeSpan = <table> {
 }
 actionEnable = 1
 castTime = 0
 actionId = 19574
 positionalParams = <table> {
 }
 namedParams = <table> {
 }
 actionUsable = true
 name = "Spell"
 nodeId = 2940
 actionType = "spell"
 functionHash = "Spell(19574)"
 serial = 31538
}
start = 315048.362000
now = nil
profile = <table> {
 apparence = <table> {
 }
 standaloneOptions = false
 source = <table> {
 }
 code = ""
 check = <table> {
 }
 overrideCode = ""
 list = <table> {
 }
 showHiddenScripts = false
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'action' (a nil value)"
Ovale = <table> {
 modules = <table> {
 }
 refreshNeeded = <table> {
 }
 playerClass = "HUNTER"
 db = <table> {
 }
 MSG_PREFIX = "Ovale"
 playerGUID = "Player-1621-091E985B"
}
GetTime = <function> defined =[C]:-1
OvaleBestAction = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:389
 ComputeIf = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:593
 ComputeAction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:276
 ComputeLua = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:653
 ComputeState = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:665
 enabled = false
 ComputeGroup = <function> defined @Interface\AddOns\Ovale\dist

**Comment by Hemario** [comment]
@Hiru1990 could you apply the changes as described in https://github.com/Hemario/Ovale/commit/21e6b86c6a547ff77df06f1318ef942d5eacb13c (only the first file dist/Compile.lua, the second file is not necessary) and confirm if this fixes your problem?

**Comment by Hiru1990** [comment]
> @ Hiru1990 pouvez-vous appliquer les modifications décrites dans [Hemario @ 21e6b86](https://github.com/Hemario/Ovale/commit/21e6b86c6a547ff77df06f1318ef942d5eacb13c) (uniquement le premier fichier dist / Compile.lua, le second fichier n'est pas nécessaire) et confirmer si cela résout votre problème?

no it does not work instead it writes me

page 1
Message: Interface\AddOns\Ovale\dist\Compile.lua:2: '=' expected near 'pas'
Time: Wed Jun  5 09:42:49 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\Compile.lua:2: '=' expected near 'pas'

Locals: 

page 2
Message: Interface\AddOns\Ovale\dist\SimulationCraft.lua:20: Cannot find a library instance of "ovale/Compile".
Time: Wed Jun  5 09:42:49 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\SimulationCraft.lua:20: Cannot find a library instance of "ovale/Compile".
[C]: in function `error'
Interface\AddOns\AAP-Core\lib\LibStub\LibStub.lua:23: in function `GetLibrary'
Interface\AddOns\Ovale\dist\SimulationCraft.lua:20: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "ovale/Compile"."

page 3
Message: Interface\AddOns\Ovale\dist\BestAction.lua:18: Cannot find a library instance of "ovale/Compile".
Time: Wed Jun  5 09:42:49 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\BestAction.lua:18: Cannot find a library instance of "ovale/Compile".
[C]: in function `error'
Interface\AddOns\AAP-Core\lib\LibStub\LibStub.lua:23: in function `GetLibrary'
Interface\AddOns\Ovale\dist\BestAction.lua:18: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "ovale/Compile"."

page 4
Message: Interface\AddOns\Ovale\dist\Frame.lua:8: Cannot find a library instance of "ovale/Compile".
Time: Wed Jun  5 09:42:49 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\Frame.lua:8: Cannot find a library instance of "ovale/Compile".
[C]: in function `error'
Interface\AddOns\AAP-Core\lib\LibStub\LibStub.lua:23: in function `GetLibrary'
Interface\AddOns\Ovale\dist\Frame.lua:8: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "ovale/Compile"."

page 5
Message: Interface\AddOns\Ovale\dist\conditions.lua:5: Cannot find a library instance of "ovale/Compile".
Time: Wed Jun  5 09:42:49 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\conditions.lua:5: Cannot find a library instance of "ovale/Compile".
[C]: in function `error'
Interface\AddOns\AAP-Core\lib\LibStub\LibStub.lua:23: in function `GetLibrary'
Interface\AddOns\Ovale\dist\conditions.lua:5: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "ovale/Compile"."

page 6
Message: Interface\AddOns\Ovale\dist\Compile.lua:2: '=' expected near 'pas'
Time: Wed Jun  5 09:42:52 2019
Count: 4

page 7
Message: (null)
Time: Wed Jun  5 09:42:52 2019
Count: 16

**Comment by Hemario** [comment]
@Hiru1990 , I think there must have gone something wrong with the edit.
This is the file /dist/Compila.lua https://raw.githubusercontent.com/Hemario/Ovale/21e6b86c6a547ff77df06f1318ef942d5eacb13c/dist/Compile.lua
Can you copy the contents and overwrite the entire file with it?

**Comment by Hiru1990** [comment]
> @ Hiru1990 , je pense que quelque chose ne va pas avec l'édition. 
> Ceci est le fichier /dist/Compila.lua https://raw.githubusercontent.com/Hemario/Ovale/21e6b86c6a547ff77df06f1318ef942d5eacb13c/dist/Compile.lua
> Pouvez-vous copier le contenu et écraser le fichier en entier?

it's perfect everything works fine thank you for your help it helped me a lot thank you again

**Comment by Hemario** [comment]
fixed in https://github.com/Sidoine/Ovale/releases/tag/8.1.2
