### ISSUE TITLE
Monk bug LUA (message 1/2)

### ISSUE THREAD

**Issue by sdestem** [Sidoine/Ovale#625]
Message: Interface\AddOns\Ovale\dist\Frame.lua:254: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
Time: Sat Jul  6 21:11:09 2019
Count: 2
Stack: Interface\AddOns\Ovale\dist\Frame.lua:254: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: <unnamed>:SetPoint.
[C]: in function `SetPoint'
Interface\AddOns\Ovale\dist\Frame.lua:254: in function `UpdateFrame'
Interface\AddOns\Ovale\dist\Frame.lua:555: in function `?'
...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `SendMessage'
Interface\AddOns\Ovale\dist\Options.lua:137: in function <Interface\AddOns\Ovale\dist\Options.lua:135>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:50: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:48>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:789: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:610>
[C]: ?
...Ons\ActionBarProfiles\libs\AceGUI-3.0\AceGUI-3.0.lua:71: in function <...Ons\ActionBarProfiles\libs\AceGUI-3.0\AceGUI-3.0.lua:69>
...Ons\ActionBarProfiles\libs\AceGUI-3.0\AceGUI-3.0.lua:285: in function `Fire'
...es\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:68: in function <...es\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

Locals: <none>

**Comment by Sidoine** [comment]
It seems to be related to the code that hides Ovale in pet combats.

**Comment by Sidoine** [comment]
No, it's not.
