### ISSUE TITLE
npm install or  yarn run simc fails with errors

### ISSUE THREAD

**Issue by tehmufifnman** [Sidoine/Ovale#627]
I am not sure if we're supposed to be using npm or yarn to run simcraft imports, but the following errors occur (both on a fresh checkout of the repo)

with yarn, `yarn install` completes just fine (I assume because of the presence of the `yarn.lock` file locking the node module libs to very specific versions).  `yarn run prepare-tools` also runs fine.

`yarn run simc`

> spell_data_t
spelleffect_data_t
spellpower_data_t
spelllabel_data_t
talent_data_t
item_data_t
azerite_power_entry_t
azerite_essence_entry_t
azerite_essence_power_entry_t
__class_ability_data
__tree_specialization_data
__class_mastery_ability_data
__race_ability_data
rppm_modifier_t
PR_Death_Knight_Blood.simc
Appending to ovale_deathknight.ts: pr_death_knight_blood
PR_Death_Knight_Frost.simc
Appending to ovale_deathknight.ts: pr_death_knight_frost
PR_Death_Knight_Unholy.simc
Appending to ovale_deathknight.ts: pr_death_knight_unholy
PR_Demon_Hunter_Havoc.simc
Appending to ovale_demonhunter.ts: pr_demon_hunter_havoc
PR_Demon_Hunter_Vengeance.simc
Appending to ovale_demonhunter.ts: pr_demon_hunter_vengeance
PR_Druid_Balance.simc
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
Appending to ovale_druid.ts: pr_druid_balance
PR_Druid_Feral.simc
Appending to ovale_druid.ts: pr_druid_feral
PR_Druid_Guardian.simc
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.conflict_and_strife.major' not implemented yet.
Appending to ovale_druid.ts: pr_druid_guardian
PR_Hunter_Beast_Mastery.simc
|cff33ff99OvaleSimulationCraft|r: Warning: Symbol 'reckless_force_counter_buff' not defined
Appending to ovale_hunter.ts: pr_hunter_beast_mastery
PR_Hunter_Marksmanship.simc
|cff33ff99OvaleSimulationCraft|r: Warning: Symbol 'reckless_force_counter_buff' not defined
Appending to ovale_hunter.ts: pr_hunter_marksmanship
PR_Hunter_Survival.simc
Appending to ovale_hunter.ts: pr_hunter_survival
PR_Mage_Arcane.simc
Appending to ovale_mage.ts: pr_mage_arcane
PR_Mage_Fire.simc
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.major' not implemented yet.
|cff33ff99OvaleSimulationCraft|r: Warning: operand 'essence.memory_of_lucid_dreams.minor' not implemented yet.
Appending to ovale_mage.ts: pr_mage_fire
PR_Mage_Frost.simc
Appending to ovale_mage.ts: pr_mage_frost
PR_Monk_Brewmaster.simc
Appending to ovale_monk.ts: pr_monk_brewmaster
PR_Monk_Windwalker.simc
Appending to ovale_monk.ts: pr_monk_windwalker
PR_Monk_Windwalker_Serenity.simc
Appending to ovale_monk.ts: pr_monk_windwalker_serenity
PR_Paladin_Protection.simc
Appending to ovale_paladin.ts: pr_paladin_protection
PR_Paladin_Retribution.simc
Appending to ovale_paladin.ts: pr_paladin_retribution
PR_Priest_Holy.simc
Appending to ovale_priest.ts: pr_priest_holy
PR_Priest_Shadow.simc
Appending to ovale_priest.ts: pr_priest_shadow
PR_Rogue_Assassination.simc
|cff33ff99OvaleSimulationCraft|r: |cff999933Warning:|r Syntax error: unexpected token '?' when parsing SIMPLE EXPRESSION
|cff33ff99OvaleSimulationCraft|r: |cff999933Warning:|r Next tokens: ? 4 & raid_event.adds.in > 12 <EOS>
E:\Dropbox\Projects\Ovale\Ovale-Hemario\dist\utils\importsimc.js:133
            let profileName = profile.annotation.name.substring(1, profile.annotation.name.length - 1);
                                      ^

TypeError: Cannot read property 'annotation' of undefined
    at Object.<anonymous> (E:\Dropbox\Projects\Ovale\Ovale-Hemario\dist\utils\importsimc.js:133:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

`npm install`
> Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/node_modules/@wowts/ace_db-3.0/index.ts (15,13): Type 'Diff<T[keyof T], undefined>' is not assignable to type '(AceDatabase & T)[keyof T]'.
  Type 'T[keyof T]' is not assignable to type '(AceDatabase & T)[keyof T]'.
    Type 'T' is not assignable to type 'AceDatabase & T'.
      Type 'T' is not assignable to type 'AceDatabase'.
        Type 'Diff<T[string | number | symbol], undefined>' is not assignable to type '(AceDatabase & T)[keyof T]'.
          Type 'T[string] | T[number] | T[symbol]' is not assignable to type '(AceDatabase & T)[keyof T]'.
            Type 'T[string]' is not assignable to type '(AceDatabase & T)[keyof T]'.
              Type 'Diff<T[string], undefined> | Diff<T[number], undefined> | Diff<T[symbol], undefined>' is not assignable to type '(AceDatabase & T)[keyof T]'.
                Type 'Diff<T[string], undefined>' is not assignable to type '(AceDatabase & T)[keyof T]'.
                  Type 'T[string]' is not assignable to type '(AceDatabase & T)[keyof T]'.
                    Type 'T' is not assignable to type 'AceDatabase & T'.
                      Type 'T' is not assignable to type 'AceDatabase'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/AST.ts (1954,29): Type 'AstNode' is not assignable to type '(AstNode & string & LuaArray<AstNode>) | (AstNode & LuaArray<AstNode>)'.
  Type 'AstNode' is not assignable to type 'AstNode & LuaArray<AstNode>'.
    Type 'AstNode' is not assignable to type 'LuaArray<AstNode>'.
      Index signature is missing in type 'AstNode'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/AST.ts (2722,33): Type 'FlattenParameterValue' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/AST.ts (2725,33): Type 'string | number' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Compile.ts (235,17): Type 'any' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Compile.ts (404,21): Type 'number' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Compile.ts (410,17): Type 'any' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/conditions.ts (59,17): Type 'number' is not assignable to type 'SpellInfo[T]'.
  Type 'number' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/CooldownState.ts (35,17): Type 'undefined' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Data.ts (545,29): Type 'string | number' is not assignable to type 'SpellInfo[T]'.
  Type 'string' is not assignable to type 'SpellInfo[T]'.
    Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Future.ts (744,17): Type 'string | number | boolean' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Future.ts (751,17): Type 'string | number | boolean' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/Scripts.ts (41,9): Type 'string | boolean | {}' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/SimulationCraft.ts (5471,21): Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/SimulationCraft.ts (5475,25): Type '{}' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/SimulationCraft.ts (5484,17): Type 'string' is not assignable to type 'never'.
Error E:/Dropbox/Projects/Ovale/Ovale-Hemario/src/SpellFlash.ts (134,17): Type 'number | boolean | Color' is not assignable to type 'never'.
  Type 'number' is not assignable to type 'never'.

**Comment by Sidoine** [comment]
Yes, sorry. I will fix this as soon as possible.

**Comment by tehmufifnman** [comment]
Thank you!  You do amazing work on Ovale.

**Comment by Hemario** [comment]
> PR_Rogue_Assassination.simc
> |cff33ff99OvaleSimulationCraft|r: |cff999933Warning:|r Syntax error: unexpected token '?' when parsing SIMPLE EXPRESSION
> |cff33ff99OvaleSimulationCraft|r: |cff999933Warning:|r Next tokens: ? 4 & raid_event.adds.in > 12
> E:\Dropbox\Projects\Ovale\Ovale-Hemario\dist\utils\importsimc.js:133
> let profileName = profile.annotation.name.substring(1, profile.annotation.name.length - 1);

This happens because the simc profile contains "a >? b" syntax. Which could translate into a min(a,b) kind of statement. Ovale build does not yet support this syntax and thus fails. I've been manually adjusting the profile just to be able to build.

**Comment by tehmufifnman** [comment]
This is now the current error (I know its a WIP just reporting back on the ticket <3 )

> $ node dist/utils/importsimc.js ../../simc
spell_data_t
spelleffect_data_t
spellpower_data_t
spelllabel_data_t
talent_data_t
item_data_t
azerite_power_entry_t
azerite_essence_entry_t
azerite_essence_power_entry_t
__class_ability_data
__tree_specialization_data
__class_mastery_ability_data
__race_ability_data
rppm_modifier_t
T23_Death_Knight_Blood.simc
E:\Dropbox\Projects\Ovale\Ovale\dist\Debug.js:128
                if (Ovale_1.Ovale.db.global.debug[name]) {
                                     ^

TypeError: Cannot read property 'global' of undefined
    at OvaleSpellBookClass.Debug (E:\Dropbox\Projects\Ovale\Ovale\dist\Debug.js:128:38)
    at OvaleSpellBookClass.UpdateTalents (E:\Dropbox\Projects\Ovale\Ovale\dist\SpellBook.js:108:14)
    at OvaleSpellBookClass.Update (E:\Dropbox\Projects\Ovale\Ovale\dist\SpellBook.js:103:14)
    at Object.<anonymous> (E:\Dropbox\Projects\Ovale\Ovale\dist\utils\importsimc.js:126:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Hemario** [comment]
Same error happens during the CI build: https://travis-ci.org/Sidoine/Ovale/builds/558472052?utm_source=github_status&utm_medium=notification

**Comment by Sidoine** [comment]
I'm working on this on a new branch.
