### ISSUE TITLE
LUA errors

### ISSUE THREAD

**Issue by Ciolouse** [Sidoine/Ovale#630]
It append with Warlock destruction and affliction.
Using Ovale 8.2.3 Beta.

329x Ovale\dist\BestAction.lua:756: attempt to index field 'child' (a nil value)
Ovale\dist\BestAction.lua:756: in function `GetAction'
Ovale\dist\Frame.lua:150: in function <Ovale\dist\Frame.lua:121>
(tail call): ?

Locals:
self = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Ovale\dist\BestAction.lua:391
 ComputeIf = <function> defined @Ovale\dist\BestAction.lua:603
 ComputeAction = <function> defined @Ovale\dist\BestAction.lua:278
 ComputeLua = <function> defined @Ovale\dist\BestAction.lua:663
 ComputeState = <function> defined @Ovale\dist\BestAction.lua:675
 enabled = false
 ComputeGroup = <function> defined @Ovale\dist\BestAction.lua:549
 ComputeCompare = <function> defined @Ovale\dist\BestAction.lua:470
 ComputeCustomFunction = <function> defined @Ovale\dist\BestAction.lua:517
 ComputeValue = <function> defined @Ovale\dist\BestAction.lua:692
 ComputeLogical = <function> defined @Ovale\dist\BestAction.lua:627
 ComputeFunction = <function> defined @Ovale\dist\BestAction.lua:532
}
node = <table> {
}
atTime = 589544.131000
(*temporary) = nil
(*temporary) = <table> {
 COMPUTE_VISITOR = <table> {
 }
 ComputeArithmetic = <function> defined @Ovale\dist\BestAction.lua:391
 ComputeIf = <function> defined @Ovale\dist\BestAction.lua:603
 ComputeAction = <function> defined @Ovale\dist\BestAction.lua:278
 ComputeLua = <function> defined @Ovale\dist\BestAction.lua:663
 ComputeState = <function> defined @Ovale\dist\BestAction.lua:675
 enabled = false
 ComputeGroup = <function> defined @Ovale\dist\BestAction.lua:549
 ComputeCompare = <function> defined @Ovale\dist\BestAction.lua:470
 ComputeCustomFunction = <function> defined @Ovale\dist\BestAction.lua:517
 ComputeValue = <function> defined @Ovale\dist\BestAction.lua:692
 ComputeLogical = <function> defined @Ovale\dist\BestAction.lua:627
 ComputeFunction = <function> defined @Ovale\dist\BestAction.lua:532
}
(*temporary) = "OvaleBestAction_GetAction"
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'child' (a nil value)"
variables = <table> {
 isState = true
 lastEnable = <table> {
 }
 isInitialized = false
 variable = <table> {
 }
 futureVariable = <table> {
 }
 futureLastEnable = <table> {
 }
}

**Comment by Hemario** [comment]
Please make sure you have the actual script selected.

**Comment by Ciolouse** [comment]
Script par défaut (sc_t23_warlock_affliction) used.
Thanks for quick answer ! :D
