### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Haunted18** [Sidoine/Ovale#631]
My Ovale tells me to use Focusing Iris all the time, even when its on cooldown. It is the only spell it tells me to use

**Comment by Hemario** [comment]
As a workaround until this is fixed you can do the following:

> go into scripts/ovale_<yourclass>_spells.lua and locate Define(focused_azerite_beam XXXXXX) where XXXXXX is a number, and change the number to 295258

**Comment by Haunted18** [comment]
wow that fixed it, thank you so much!

**Comment by ecchifluffy** [comment]
I've been having the same issue on my rogue with Focused Azerite Beam... was going to submit a ticket but glad someone found a workaround

**Comment by vicki2810** [comment]
Hello - sorry, I'm not familar with going into scripts - what and where is "dist" please? I've been having the same issue and it is driving me nuts
