### ISSUE TITLE
Ret Pally rotation (v8.2.5)

### ISSUE THREAD

**Issue by Brdrker** [Sidoine/Ovale#632]
Downloaded and installed the latest version of 8.2.5 when it was released. My Ret Pally has gone from only rarely waiting for some attack to come off cooldown to now waiting a lot as if everything is on cooldown. Inquisition often shows, grayed out, but is available repeatedly.

I don't have any specific examples, only that engagement since release is way more stilted than it was with the prior version.

**Comment by Hemario** [comment]
The default profile has some checks tied to Avenging Wrath. It will not use any holy power spenders when AW is about to come off cooldown or is off cooldown (5 seconds or less). Using AW will result in your normal rotation.

**Comment by Brdrker** [comment]
Understood. Thanks for the clarification.

**Comment by Brdrker** [comment]
P.S. Next time, I should probably check what script I am running... considering it was "blank" and not either of the provided scripts. Pilot error here completely.

**Comment by Hemario** [comment]
That usually also helps if you want a rotation to be shown.

**Comment by Brdrker** [comment]
Since I have your attention, I'm going to ask what is probably a stupid question. There is a "default script" and an [8.2} script for Ret Pally. Both are labeled T23 Ret Pally. I understand the differences in the scripts which are tuned for a specific talent selection (so noted in the label on the script) but on these two, I'm not sure I understand the differences. As my Pally isn't actually T23, it probably makes little difference but I thought I'd ask just the same.

**Comment by Hemario** [comment]
the default script and the T23 Ret Pally script are exactly the same. The default script is just a "symbolic" link to the script sc_t23_paladin_retribution.

Simulationcraft sometimes provides multiple scripts for the same spec (for instance frost mages sc_t23_mage_frost and sc_t23_mage_frost_frozenorb), usually with different talents selected. However, this translates into the exact same script in Ovale anyway. Simulationcraft and Ovale scripts can work with different talents selected.

**Comment by Brdrker** [comment]
Thanks.

**Comment by addf0214** [comment]
@Hemario Hi, Most time in a raid, I won't want to use AW once it's off cooldown. How should I modify this script?

**Comment by addf0214** [comment]
I've debugged the issue, and I don't think it's about the profile from SimulationCraft. Use the script in Ovale 8.2.0, which works perfectly in the 8.2.0, will not work in this and recent several versions.
And I've tried using 'node dist/utils/importsimc.js' to generate scripts, no matter how I change the origin .simc files, the addon always waiting for the AW.
