### ISSUE TITLE
Focused Azerite Beam bug

### ISSUE THREAD

**Issue by kataclyzmik** [Sidoine/Ovale#634]
I noticed on a lot of my characters that if I use the Focused Azerite Beam, the icon will not go away. It just stays in the prompt as if it wants me to cast it again, but obviously I can't.

**Comment by Hemario** [comment]
Can you try the alpha version 8.2.6-alpha (https://github.com/Sidoine/Ovale/releases/tag/8.2.6-alpha) and report whether this is fixed or not?

**Comment by kataclyzmik** [comment]
I can't seem to get it to work.

**Comment by SirIntGit** [comment]
I notice from update 2.7.5 to 2.7.6 a endless spam of Monefire on my Druid Tank. Mybe something with the DOT detection handling is broken.

**Comment by Sidoine** [comment]
This bug should be fixed, tell me if it's the case, please

**Comment by kataclyzmik** [comment]
Just tested, I don't see any errors!
