### ISSUE TITLE
No key binding for Arms Warrior execute

### ISSUE THREAD

**Issue by davidlandrith** [Sidoine/Ovale#639]
Since I started using Ovale Spell Priority with my Arms Warrior (I am currently using the Sat Aug 24 version) the Execute action does not display a key binding at all. This is true no matter where I place Execute on the action bar. All the other actions do display the key binding. I am using ElvUI (currently v21).

**Comment by Sidoine** [comment]
I do not have this problem. Do you have some talent that may modify Execute?

**Comment by davidlandrith** [comment]
That's a good question. My talents are as follows:

- Sudden Death
- Double Time
- Massacre
- Bounding Stride
- Warbreaker
- In for the Kill
- Anger Management

**Comment by davidlandrith** [comment]
Incidentally, I have the Execute Action mapped to the 3 key.
