### ISSUE TITLE
LUA-Error since 8.2.5 at my Boomie (attempt to index local 'spellPowerCosts')

### ISSUE THREAD

**Issue by Chesslion** [Sidoine/Ovale#643]
1/3:
```
Message: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Time: Sun Sep 29 10:50:07 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:680: in function <Interface\AddOns\Ovale\dist\BestAction.lua:621>
(tail call): ?
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:85: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:770: in function <Interface\AddOns\Ovale\dist\BestAction.lua:760>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:324: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:770: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:751: in function `GetAction'
Interface\AddOns\Ovale\dist\Frame.lua:152: in function <Interface\AddOns\Ovale\dist\Frame.lua:123>
(tail call): ?

Locals: (*temporary) = 0.017000
(*temporary) = <function> defined =[C]:-1

```
2/3:
===

Message: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Time: Sun Sep 29 10:50:07 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Interface\AddOns\Ovale\dist\BestAction.lua:324: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:770: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:751: in function `GetAction'
Interface\AddOns\Ovale\dist\Frame.lua:152: in function <Interface\AddOns\Ovale\dist\Frame.lua:123>
(tail call): ?

Locals: element = <table> {
 lowername = "balancedefaultshortcdactions"
 rawPositionalParams = <table> {
 }
 timeSpan = <table> {
 }
 func = "BalanceDefaultShortCdActions"
 positionalParams = <table> {
 }
 rawNamedParams = <table> {
 }
 namedParams = <table> {
 }
 name = "BalanceDefaultShortCdActions"
 paramsAsString = ""
 type = "custom_function"
 nodeId = 7449
 serial = -1
 asString = "balancedefaultshortcdactions()"
}
atTime = 8309.462000
timeSpan = <table> {
}
result = nil
node = <table> {
 asString = "AddFunction BalanceDefaultShortCdActions
{
 spell(purifying_blast)
 spell(ripple_in_space_essence)
 unless spell(concentrated_flame_essence)
 {
  if buffpresent(reckless_force_buff) and target.DebuffPresent(moonfire) and target.DebuffPresent(sunfire_debuff) and { not talent(stellar_flare_talent) or target.DebuffPresent(stellar_flare_debuff) } spell(the_unbound_force)
  spell(worldvein_resonance_essence)
  spell(thorns)
  unless spell(warrior_of_elune) or { az_ss() and not buffpresent(ca_inc) or not az_ss() and { buffpresent(ca_inc) or spellcooldown(ca_inc) > 30 } } and astralpower() >= astralpowercost(force_of_nature) and spell(force_of_nature)
  {
   if { buffpresent(ca_inc) or spellcooldown(ca_inc) > 30 } and astralpower() >= astralpowercost(solar_wrath) spell(fury_of_elune)
  }
 }
}"
 rawPositionalParams = <table> {
 }
 child = <table> {
 }
 positionalParams = <table> {
 }
 rawNamedParams = <table> {
 }
 nodeId = 6225
 name = "BalanceDefaultShortCdActions"
 paramsAsString = ""
 namedParams = <table> {
 }
 type = "add_function"
}
self = <table> {
 ovaleCondition = <table> {
 }
 ovaleData = <table> {
 }
 ComputeIf = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:404
 ovaleActionBar = <table> {
 }
 ComputeGroup = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:350
 OvaleSpellBook = <table> {
 }
 variables = <table> {
 }
 self_timeSpan = <table> {
 }
 OvalePower = <table> {
 }
 self_valuePool = <table> {
 }
 ComputeArithmetic = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:192
 ovaleEquipment = <table> {
 }
 ComputeAction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:79
 ComputeValue = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:493
 OvaleSpells = <table> {
 }
 ComputeCompare = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:271
 ComputeCustomFunction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:318
 baseState = <table> {
 }
 COMPUTE_VISITOR = <table> {
 }
 ovalePaperDoll = <table> {
 }
 onInitialize = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:63
 ovaleState = <table> {
 }
 ComputeLua = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:464
 OvaleGUID = <table> {
 }
 ComputeFunction = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:333
 OnDisable = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:66
 self_serial = 20646
 Ovale_ScriptChanged = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:69
 tracer = <table> {
 }
 profiler = <table> {
 }
 OvaleFuture = <table> {
 }
 module = <table> {
 }
 ComputeState = <function> defined @Interface\AddOns\Ovale\dist\BestAction.lua:476
 ovaleCooldown = <table> {
 }

------

3/3:

Message: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Time: Sun Sep 29 10:50:07 2019
Count: 4
Stack: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)

Locals:

**Comment by ghodhereek** [comment]
got similar issue. see below:

Date: 2019-10-11 18:38:58
ID: 1
Error occured in: Global
Count: 3
Message: ..\AddOns\Ovale\dist\Power.lua line 342:
   attempt to index local 'spellPowerCosts' (a nil value)
Debug:
   Ovale\dist\Power.lua:342: GetSpellCost()
   Ovale\dist\Power.lua:525: getPowerCostAt()
   Ovale\dist\Power.lua:572:
      Ovale\dist\Power.lua:568
   (tail call): ?
   Ovale\dist\BestAction.lua:680:
      Ovale\dist\BestAction.lua:621
   (tail call): ?
   (tail call): ?
   Ovale\dist\BestAction.lua:85: visitor()
   Ovale\dist\BestAction.lua:822: RecursiveCompute()
   Ovale\dist\BestAction.lua:799: PostOrderCompute()
   Ovale\dist\BestAction.lua:770:
      Ovale\dist\BestAction.lua:760
   (tail call): ?
   Ovale\dist\BestAction.lua:324: visitor()
   Ovale\dist\BestAction.lua:822: RecursiveCompute()
   Ovale\dist\BestAction.lua:799: PostOrderCompute()
   Ovale\dist\BestAction.lua:770:
      Ovale\dist\BestAction.lua:760
   (tail call): ?
   Ovale\dist\BestAction.lua:324: visitor()
   Ovale\dist\BestAction.lua:822: RecursiveCompute()
   Ovale\dist\BestAction.lua:799: PostOrderCompute()
   Ovale\dist\BestAction.lua:770: PostOrderCompute()
   Ovale\dist\BestAction.lua:751: GetAction()
   Ovale\dist\Frame.lua:152:
      Ovale\dist\Frame.lua:123
   (tail call): ?
Locals:
self = <table> {
 ovaleAura = <table> {
 }
 current = <table> {
 }
 ovaleData = <table> {
 }
 ovalePaperDoll = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:87
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:137
 POWER_INFO = <table> {
 }
 ovaleSpellBook = <table> {
 }
 profiler = <table> {
 }
 OnDisable = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:104
 tracer = <table> {
 }
 module = <table> {
 }
 next = <table> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:126
 requirement = <table> {
 }
 EventHandler = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:120
 ovaleFuture = <table> {
 }
 RequirePowerHandler = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:158
 UNIT_RANGEDDAMAGE = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:153
 UNIT_POWER_UPDATE = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:145
 UNIT_LEVEL = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:132
 ovale = <table> {
 }
 POWER_TYPE = <table> {
 }
 CopySpellcastInfo = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:161
 baseState = <table> {
 }
}
spell = 19574
powerType = "focus"
spellId = 19574
spellPowerCosts = nil
(*temporary) = 19574
(*temporary) = true
(*temporary) = 19574
(*temporary) = true
(*temporary) = 19574
(*temporary) = "number"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spellPowerCosts' (a nil value)"
GetSpellPowerCost = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
