### ISSUE TITLE
power lua.432

### ISSUE THREAD

**Issue by Shashlic** [Sidoine/Ovale#650]
pls check... after zone-change, portal ... homestone...

12x Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Ovale\dist\Power.lua:342: in function `GetSpellCost'
Ovale\dist\Power.lua:525: in function `getPowerCostAt'
Ovale\dist\Power.lua:572: in function <Ovale\dist\Power.lua:568>
(tail call): ?
Ovale\dist\BestAction.lua:680: in function <Ovale\dist\BestAction.lua:621>
(tail call): ?
(tail call): ?
Ovale\dist\BestAction.lua:85: in function `visitor'
Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Ovale\dist\BestAction.lua:770: in function <Ovale\dist\BestAction.lua:760>
(tail call): ?
...
Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Ovale\dist\BestAction.lua:770: in function <Ovale\dist\BestAction.lua:760>
(tail call): ?
Ovale\dist\BestAction.lua:324: in function `visitor'
Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Ovale\dist\BestAction.lua:770: in function `PostOrderCompute'
Ovale\dist\BestAction.lua:751: in function `GetAction'
Ovale\dist\Frame.lua:152: in function <Ovale\dist\Frame.lua:123>
(tail call): ?

Locals:
self = <table> {
 ovaleAura = <table> {
 }
 current = <table> {
 }
 ovaleData = <table> {
 }
 ovalePaperDoll = <table> {
 }
 OnInitialize = <function> defined @Ovale\dist\Power.lua:87
 UNIT_MAXPOWER = <function> defined @Ovale\dist\Power.lua:137
 POWER_INFO = <table> {
 }
 ovaleSpellBook = <table> {
 }
 profiler = <table> {
 }
 OnDisable = <function> defined @Ovale\dist\Power.lua:104
 tracer = <table> {
 }
 module = <table> {
 }
 next = <table> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Ovale\dist\Power.lua:126
 requirement = <table> {
 }
 EventHandler = <function> defined @Ovale\dist\Power.lua:120
 ovaleFuture = <table> {
 }
 RequirePowerHandler = <function> defined @Ovale\dist\Power.lua:158
 UNIT_RANGEDDAMAGE = <function> defined @Ovale\dist\Power.lua:153
 UNIT_POWER_UPDATE = <function> defined @Ovale\dist\Power.lua:145
 UNIT_LEVEL = <function> defined @Ovale\dist\Power.lua:132
 ovale = <table> {
 }
 POWER_TYPE = <table> {
 }
 CopySpellcastInfo = <function> defined @Ovale\dist\Power.lua:161
 baseState = <table> {
 }
}
spell = 22812
powerType = "energy"
spellId = 22812
spellPowerCosts = nil
(*temporary) = 22812
(*temporary) = true
(*temporary) = 22812
(*temporary) = true
(*temporary) = 22812
(*temporary) = "number"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spellPowerCosts' (a nil value)"
GetSpellPowerCost = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1

**Comment by rwilliams** [comment]
The fix is in this [commit](https://github.com/Sidoine/Ovale/pull/651/commits/6598f90d8d840413d3eb19f645a37dc2aee630f3). I image it'll be merged into the addon  very soon but you can manually make the change yourself in the meantime.
