### ISSUE TITLE
Fire mage!

### ISSUE THREAD

**Issue by Ronfar** [Sidoine/Ovale#653]
pyroclasm has the wrong spell id! should be 269651

**Comment by Ronfar** [comment]
Also blaster_master_buff is 274598

**Comment by Ronfar** [comment]
think i've found 2 more fire mage problems

   if { InFlightToTarget(meteor) and 0 <= 0.5 or not Talent(meteor_talent) } and { BuffPresent(rune_of_power_buff) or not Talent(rune_of_power_talent) } Spell(combustion)

that 0 <= 0.5 as long as it in combustion is never suggested with meteor talent (unsure what that suppose to even be doing)

AND

 if { Talent(rune_of_power_talent) and SpellCooldown(combustion) <= CastTime(rune_of_power) or SpellCooldown(combustion) == 0 } and not  { Talent(firestarter_talent) and target.HealthPercent() >= 90 } or BuffPresent(combustion_buff) FireCombustionphaseMainActions()

  unless { { Talent(rune_of_power_talent) and SpellCooldown(combustion) <= CastTime(rune_of_power) or SpellCooldown(combustion) == 0 } and not  { Talent(firestarter_talent) and target.HealthPercent() >= 90 } or BuffPresent(combustion_buff) } and FireCombustionphaseMainPostConditions()
  {


i'm pretty sure the AND NOT should just be and, it cause you to end up in FireCombustionphaseMainActions spamming scorch which is very incorrect at 90%+

**Comment by Ronfar** [comment]
spellId are still wrong, but i suppose entire script not working could be because spellcooldown is broken

**Comment by petrov121** [comment]
if { InFlightToTarget(meteor) and 0 <= 0.5 or not Talent(meteor_talent) } and { BuffPresent(rune_of_power_buff) or not Talent(rune_of_power_talent) } Spell(combustion)

this is a fun one. basicly this has to do with autogenerating the script from simulationcraft APL.

what it actually does is the following:
if your meteor is inflight and
    0 <= 0.5 (this is always true, it's supposed to be InflightToTarget(meteor) <= 0.5 aka, meteor is cast but hasn't landed yet)
         OR you dont have the meteor talent, in which case previous checks make no sense.
              AND you have the rune of power then
                    THEN cast combustion

Basicly the probllem here is that InFlightToTarget(meteor) always returns false. This has to do with the fact that meteor is an instant cast. Its assumed it also lands instantly and has no traveltime. 

The other issue i've yet to look into.
