### ISSUE TITLE
erreur LUA

### ISSUE THREAD

**Issue by sdestem** [Sidoine/Ovale#654]
Message: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Time: Tue Oct 29 15:13:07 2019
Count: 1
Stack: Interface\AddOns\Ovale\dist\Power.lua:342: attempt to index local 'spellPowerCosts' (a nil value)
Interface\AddOns\Ovale\dist\Power.lua:342: in function `GetSpellCost'
Interface\AddOns\Ovale\dist\Power.lua:525: in function `getPowerCostAt'
Interface\AddOns\Ovale\dist\Power.lua:572: in function <Interface\AddOns\Ovale\dist\Power.lua:568>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:680: in function <Interface\AddOns\Ovale\dist\BestAction.lua:621>
(tail call): ?
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:85: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:770: in function <Interface\AddOns\Ovale\dist\BestAction.lua:760>
(tail call): ?
Interface\AddOns\Ovale\dist\BestAction.lua:324: in function `visitor'
Interface\AddOns\Ovale\dist\BestAction.lua:822: in function `RecursiveCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:799: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:770: in function `PostOrderCompute'
Interface\AddOns\Ovale\dist\BestAction.lua:751: in function `GetAction'
Interface\AddOns\Ovale\dist\Frame.lua:152: in function <Interface\AddOns\Ovale\dist\Frame.lua:123>
(tail call): ?

Locals: self = <table> {
 ovaleAura = <table> {
 }
 current = <table> {
 }
 ovaleData = <table> {
 }
 ovalePaperDoll = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:87
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:137
 POWER_INFO = <table> {
 }
 ovaleSpellBook = <table> {
 }
 profiler = <table> {
 }
 OnDisable = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:104
 tracer = <table> {
 }
 module = <table> {
 }
 next = <table> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:126
 requirement = <table> {
 }
 EventHandler = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:120
 ovaleFuture = <table> {
 }
 RequirePowerHandler = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:158
 UNIT_RANGEDDAMAGE = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:153
 UNIT_POWER_UPDATE = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:145
 UNIT_LEVEL = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:132
 ovale = <table> {
 }
 POWER_TYPE = <table> {
 }
 CopySpellcastInfo = <function> defined @Interface\AddOns\Ovale\dist\Power.lua:161
 baseState = <table> {
 }
}
spell = 115098
powerType = "energy"
spellId = 115098
spellPowerCosts = nil
(*temporary) = 115098
(*temporary) = true
(*temporary) = 115098
(*temporary) = true
(*temporary) = 115098
(*temporary) = "number"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'spellPowerCosts' (a nil value)"
GetSpellPowerCost = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1

**Comment by UFTimmy** [comment]
I get this error every time I switch zones. I have to /reload in order to make Ovale work again.

**Comment by sdestem** [comment]
What is the solution please ??

**Comment by Sidoine** [comment]
Did you try the beta version ?
