### ISSUE TITLE
\Ovale\dist\AST.lua line 482 error

### ISSUE THREAD

**Issue by ghodhereek** [Sidoine/Ovale#655]
Date: 2019-10-30 01:33:42
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Ovale\dist\AST.lua line 482:
   bad argument #2 to 'format' (string expected, got nil)
Debug:
   [C]: ?
   Ovale\dist\AST.lua:482: visitor()
   Ovale\dist\AST.lua:1927: Unparse()
   Ovale\dist\AST.lua:492: UnparseGroup()
   Ovale\dist\AST.lua:374: visitor()
   Ovale\dist\AST.lua:1927: Unparse()
   Ovale\dist\AST.lua:551: visitor()
   Ovale\dist\AST.lua:1927: Unparse()
   ...ddOns\Ovale\dist\simulationcraft\SimulationCraft.lua:454: Emit()
   ...ddOns\Ovale\dist\simulationcraft\SimulationCraft.lua:507:
      ...ddOns\Ovale\dist\simulationcraft\SimulationCraft.lua:502
   [C]: ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:51:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:843:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664
   [C]: ?
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:61:
      ...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:58
Locals:
None

**Comment by Xeltor** [comment]
I am having the same issue, it occurs when you go into /ovale simc and press accept after adding a simcraft profile.

In this case i was trying to get it to work with the T24 Hunter Beast Mastery profile.

```
Ovale\dist\AST.lua:482: bad argument #2 to 'format' (string expected, got nil)
[C]: ?
Ovale\dist\AST.lua:482: in function `visitor'
Ovale\dist\AST.lua:1927: in function `Unparse'
Ovale\dist\AST.lua:492: in function `UnparseGroup'
Ovale\dist\AST.lua:374: in function `visitor'
Ovale\dist\AST.lua:1927: in function `Unparse'
Ovale\dist\AST.lua:551: in function `visitor'
Ovale\dist\AST.lua:1927: in function `Unparse'
...ddOns\Ovale\dist\simulationcraft\SimulationCraft-1.12.3.lua:454: in function `Emit'
...ddOns\Ovale\dist\simulationcraft\SimulationCraft-1.12.3.lua:507: in function <...ddOns\Ovale\dist\simulationcraft\SimulationCraft.lua:502>
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-78.lua:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[C]: ?
...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-40.lua:72: in function <...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0-40.lua:290: in function `Fire'
...AceGUI-3.0-40\widgets\AceGUIWidget-MultiLineEditBox.lua:61: in function <...AceGUI-3.0\widgets\AceGUIWidget-MultiLineEditBox.lua:58>
```
