### ISSUE TITLE
Icons Dont Show and Settings Dont Save

### ISSUE THREAD

**Issue by tehmufifnman** [Sidoine/Ovale#661]
New Brewmaster T24 profile is selected.

Icons Not Showing:
https://i.imgur.com/n1W82SK.jpg

When I move/resize the icons, and then /reload - Ovale reverts to default.

UPDATE:
Looks like icons only show when I have a target, other issues remain.  There should be a toggle for this feature though - I prefer the old way of icons being populated always.

**Comment by Bingo176** [comment]
This commit fixed everything but the icons only show when you have something targeted. Different behavior than previous builds.
