### ISSUE TITLE
Wind Walker Monk - Whirling Dragon Punch

### ISSUE THREAD

**Issue by tehmufifnman** [Sidoine/Ovale#665]
When talented, Whirling Dragon Punch is never suggested as the next spell.

**Comment by tehmufifnman** [comment]
It definitely seems like some kind of bug with the SpellInfo definition
```
SpellInfo(whirling_dragon_punch unusable=1 cd_haste=melee)
SpellRequire(whirling_dragon_punch unusable 0=oncooldown,rising_sun_kick)
SpellRequire(whirling_dragon_punch unusable 0=oncooldown,fists_of_fury)
```

I added a temporary icon that was nothing more than `Spell(whirling_dragon_punch)` and it would suggest the spell whenever EITHER rising_sun_kick or fists_of_fury was on cooldown (the spell requires BOTH to be on cooldown).

In addition, if I surround the spell in an if statement, it NEVER shows - regardless of the cooldown of the aforementioned spells.
```
if spellcooldown(fists_of_fury) > 0 and spellcooldown(rising_sun_kick) > 0 spell(whirling_dragon_punch)
```

**Comment by tehmufifnman** [comment]
This continues to be an issue and is preventing the use of the current Ovale for WW Monks.

**Comment by frontierliu** [comment]
I got the same issue on the lastest version Ovale from curse. How to fix?

**Comment by tehmufifnman** [comment]
No known fix, I reverted to an old version.  @Sidoine needs to fix it.

**Comment by petrov121** [comment]
I think this is the same bug as listed in under issue SpellCooldown
