### ISSUE TITLE
tsc issues

### ISSUE THREAD

**Issue by Hemario** [Sidoine/Ovale#666]
@Sidoine I've pulled the latest master but now I'm unable to build the project and compile new scripts

```
E:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns\Ovale>tsc
src/Ovale.ts:136:9 - error TS2322: Type 'AceModule' is not assignable to type 'AceModule & T & U & V & W'.
  Type 'AceModule' is not assignable to type 'T'.

136         return ret;
            ~~~~~~~~~~~

src/Queue.ts:80:2 - error TS7023: 'BackToFrontIterator' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

80  BackToFrontIterator() {
    ~~~~~~~~~~~~~~~~~~~
```

Would you be able to assist?

**Comment by Sidoine** [comment]
That's strange because it compiles with no error on Travis CI. I see that you typed tsc directly, you should use yarn to launch the command (yarn prepare-tools) otherwise it will use your globally installed typescript, which may not be up to date.

**Comment by Hemario** [comment]
This is the command I use to compile fully by command line (it's a file called build.bat on my local system)
`cls && yarn install && tsc && node dist\utils\importsimc.js d:\src\simc && yarn prepare`

I did try yarn prepare-tools and that gave me no error. I will replace tsc with yarn prepare-tools

**Comment by Hemario** [comment]
and what's up with the lowercase in all the scripts? :(

**Comment by tehmufifnman** [comment]
> 
> 
> and what's up with the lowercase in all the scripts? :(

This is the absolute WORST for Code/Script readability and makes me a sad engineer ;(
