### ISSUE TITLE
spellCoolDown()

### ISSUE THREAD

**Issue by Ronfar** [Sidoine/Ovale#669]
entire function seems broken, if using spellcooldown() > x it never rings false, if using spellcooldown() == x or spellcooldown() < x, it always comes out true from my testing so far

**Comment by Ronfar** [comment]
downgraded to 8.2.11 and it works, stopped working with 8.3.0 beta

**Comment by petrov121** [comment]
The problem here was an added sanity check. It makes the function SpellCooldown require a comparator.

I've put in a merge request with a fix (removal of the check)
