### ISSUE TITLE
3 Errors when using a DemonHunter in combat with Humanoids

### ISSUE THREAD

**Issue by Dhragas** [Sidoine/Ovale#674]
Hello

When using an Night Elf Demon Hunter in combat these 3 errors occurs 

Using Ovale 8.3.3 and English EU client.

Error1:
`21x ...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua:51: LibBabble-CreatureType-3.0: Translation "demon" not found.
[string "@Ovale\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua"]:51: in function <...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0.lua:28>
[string "@Ovale\dist\conditions.lua"]:691: in function <Ovale\dist\conditions.lua:685>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:353: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:778: in function `GetAction'
[string "@Ovale\dist\Frame.lua"]:152: in function <Ovale\dist\Frame.lua:123>
[string "=(tail call)"]: ?`

Error2:
`21x ...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua:51: LibBabble-CreatureType-3.0: Translation "humanoid" not found.
[string "@Ovale\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua"]:51: in function <...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0.lua:28>
[string "@Ovale\dist\conditions.lua"]:691: in function <Ovale\dist\conditions.lua:685>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:353: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:778: in function `GetAction'
[string "@Ovale\dist\Frame.lua"]:152: in function <Ovale\dist\Frame.lua:123>
[string "=(tail call)"]: ?`

Error3:
`21x ...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua:51: LibBabble-CreatureType-3.0: Translation "beast" not found.
[string "@Ovale\libs\LibBabble-CreatureType-3.0\LibBabble-3.0-2.lua"]:51: in function <...le\libs\LibBabble-CreatureType-3.0\LibBabble-3.0.lua:28>
[string "@Ovale\dist\conditions.lua"]:691: in function <Ovale\dist\conditions.lua:685>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:353: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function <Ovale\dist\BestAction.lua:787>
[string "=(tail call)"]: ?
[string "@Ovale\dist\BestAction.lua"]:338: in function `visitor'
[string "@Ovale\dist\BestAction.lua"]:849: in function `RecursiveCompute'
[string "@Ovale\dist\BestAction.lua"]:826: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:797: in function `PostOrderCompute'
[string "@Ovale\dist\BestAction.lua"]:778: in function `GetAction'
[string "@Ovale\dist\Frame.lua"]:152: in function <Ovale\dist\Frame.lua:123>
[string "=(tail call)"]: ?`

**Comment by Sidoine** [comment]
Should be fixed
