### ISSUE TITLE
Spells Not Recognized With Latest Update

### ISSUE THREAD

**Issue by Tempest2537** [Sidoine/Ovale#678]
I installed the new update and when I went into a character it said in the chat log that it wasn't recognizing any of my abilities and tried with other characters and got the same thing.

**Comment by A-Lou-Sir** [comment]
On Shadow Priest Ovale reports errors:
OvaleAST : Error unknown function 'shadowcwactions'
OvaleAST : Error unknown function 'shadowmainactions'
OvaleAST : Error unknown function 'shadowessenceactions'

Addon only show Vampiric Touch as spell option.

Cannot find function names defined in the shipped lua files

**Comment by Statticc** [comment]
I get the following issues since the update on my shaman.
![image](https://user-images.githubusercontent.com/72889467/96039260-eb9e0700-0eaf-11eb-8565-492629748a87.png)

**Comment by tpayne57** [comment]
Same as Statticc, but also it doesn't seem to recognize that I have lightning shield applied. It keeps displaying to cast lighning shield.

**Comment by Tempest2537** [comment]
My druid is a feral druid and it doesnt even recognize that i entered cat form let alone what my abilities are
