### ISSUE TITLE
Repeated error leveling shadow priest

### ISSUE THREAD

**Issue by syntax53** [Sidoine/Ovale#68]
seems to happen while i'm channeling either mind flay or mind sear

Message: Interface\AddOns\Ovale\Future.lua:1007: attempt to compare nil with number
Time: 08/28/16 22:37:14
Count: 3
Stack: (tail call): ?
Interface\AddOns\Ovale\Future.lua:1007: in function `LastSpellSent'
Interface\AddOns\Ovale\Aura.lua:732: in function `LostAuraOnGUID'
Interface\AddOns\Ovale\Aura.lua:804: in function `ScanAuras'
Interface\AddOns\Ovale\Aura.lua:523: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by kevindesmet** [comment]
This does not only occur to shadow priests, not does it happen only when levelling.
The error occurs when you channel the same spell you were already channeling.

For instance: affliction warlock

1. Start channeling Drain life
2. After 1 tick of damage, click Drain life again

**Comment by syntax53** [comment]
I just noticed the Mr. Robot reference in my error log.  Going to disable that and see if there is any difference.

Message: Interface\AddOns\Ovale\Future.lua:1007: attempt to compare nil with number
Time: 08/29/16 23:19:39
Count: 6
Stack: (tail call): ?
Interface\AddOns\Ovale\Future.lua:1007: in function `LastSpellSent'
Interface\AddOns\Ovale\Aura.lua:732: in function `LostAuraOnGUID'
Interface\AddOns\Ovale\Aura.lua:804: in function `ScanAuras'
Interface\AddOns\Ovale\Aura.lua:523: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...bot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: (*temporary) = "UNIT_AURA"
(*temporary) = "player"
(*temporary) = "UNIT_AURA"
(*temporary) = "player"
(*temporary) = <function> defined =[C]:-1

**Comment by syntax53** [comment]
Nope, still got the error, just complained about a different Ace3 addon at the bottom:

Message: Interface\AddOns\Ovale\Future.lua:1007: attempt to compare nil with number
Time: 08/29/16 23:26:00
Count: 1
Stack: (tail call): ?
Interface\AddOns\Ovale\Future.lua:1007: in function `LastSpellSent'
Interface\AddOns\Ovale\Aura.lua:732: in function `LostAuraOnGUID'
Interface\AddOns\Ovale\Aura.lua:804: in function `ScanAuras'
Interface\AddOns\Ovale\Aura.lua:523: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: (*temporary) = "UNIT_AURA"
(*temporary) = "player"
(*temporary) = "UNIT_AURA"
(*temporary) = "player"
(*temporary) = <function> defined =[C]:-1
