### ISSUE TITLE
Incombat() issue

### ISSUE THREAD

**Issue by Volgrath** [Sidoine/Ovale#682]
"if not incombat()" is not bypassing my precombat portions of code.

Example of code:
AddIcon enemies=1 help=main specialization=feral
{
 if not incombat() feralprecombatmainactions()
 feral_defaultmainactions()
}

**Comment by tpayne57** [comment]
not sure if related but on enhancement shaman. pre-combat script wont go away. (wants me to cast my buffs lightning shield, windfury weapon firebrand weapon.

even if they are applied and in combat it wont get past them (i can comment them out in the script and rotation starts to display. more issues with maelstrom stack lightning bolt but thats a different issue)

**Comment by ultijlam** [comment]
I believe this is fixed by 0a75801244ca5fe25a563b7cad67f0cd906813e6.  InCombat() in Ovale 9.0.19 is working correctly on my system.
