### ISSUE TITLE
ERROR: Unknown spell list. On all Characters with 90% of spells

### ISSUE THREAD

**Issue by Brizz0l** [Sidoine/Ovale#683]
Hi, after the most recent update Ovale does not seem to recognize most spells for all the different alts I've logged into (Druid, all forms and specs, Mage, all specs,
 and Warlock all specs)

The below picture just shows a small number of spells missing however if I keep scrolling in the chat there are a lot more....

![ovale error](https://user-images.githubusercontent.com/72912388/96094938-de8c1280-0ec5-11eb-9478-32ffd8155488.png)

I just want to make sure you guys know this is a problem and for now I have just disabled the addon. Please let me know if there are any fixes! I will be periodically checking my addon client for updates.

Thanks

**Comment by JillyBean1899** [comment]
Same here, on my hunter (only one I've logged into so far) it's just Multi-shot.

**Comment by tpayne57** [comment]
shamans have this for hex

**Comment by auddie2015** [comment]
Warlock script for demonology is not working either. It complains of missing spells also. 

Maybe related, maybe not soI will start a new thread but SimulationCraft import is completely broken. No spells are defined.

**Comment by wyndman** [comment]
Error Unknown spell list flagellation_cleanse in spell(flagellation_cleanse).

Subtlety rogue
