### ISSUE TITLE
Enhancement shaman Maelstrom weapon stacks

### ISSUE THREAD

**Issue by tpayne57** [Sidoine/Ovale#684]
it seems the script isn't recognizing the maelstrom weapon stacks for 
" #lightning_bolt,if=buff.maelstrom_weapon.stack>=5
 if buffstacks(maelstrom_weapon) >= 5 spell(lightning_bolt)"

lightning bolt never shows up in rotation

**Comment by Smaghed** [comment]
Blizzard changed the behaviour of Maelstrom Weapon and gave it a new spellid.
In order for Ovale to track Maelstrom Weapon stacks you should edit the ovale_shaman_spells.lua file. or define the spell in your script.

Define(maelstrom_weapon_buff 344179)
  SpellInfo(maelstrom_weapon_buff duration=30 max_stacks=10 gcd=0 offgcd=1)
  SpellAddBuff(maelstrom_weapon_buff maelstrom_weapon_buff=1)
