### ISSUE TITLE
SimulationCraft import

### ISSUE THREAD

**Issue by auddie2015** [Sidoine/Ovale#687]
No spells seem to be defined and a very long scrolling list of errors result.

**Comment by auddie2015** [comment]
Update

The SimulationCraft script imported but now is saying:

OvaleAST: Error: Script "ovale_trinkets_wod" not found when parsing INCLUDE.
OvaleAST: Error: Failed on include
OvaleAST: Error: Failed in script visitor
OvaleAST: Error: Parse failed

I have seen this in the past but cannot recall how to resolve it.

**Comment by sirTribble** [comment]
This is list of warlord of draenor trinkets that was in all scripts in ovale 8 and prior .
Until it fixed, you can manually find and delete string in script "include(ovale_trinkets_wod)"

**Comment by auddie2015** [comment]
Thank you!
