### ISSUE TITLE
Dwarf priest error when ever he gets trapped. 

### ISSUE THREAD

**Issue by brallinoth** [Sidoine/Ovale#688]
This is the Lua error that pops up every time; 
Message: Interface\AddOns\Ovale\dist\LossOfControl.lua:29: attempt to call field 'GetEventInfo' (a nil value)
Time: Wed Oct 21 00:24:04 2020
Count: 2
Stack: Interface\AddOns\Ovale\dist\LossOfControl.lua:29: attempt to call field 'GetEventInfo' (a nil value)
[string "@Interface\AddOns\Ovale\dist\LossOfControl.lua"]:29: in function <Interface\AddOns\Ovale\dist\LossOfControl.lua:28>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by Sidoine** [comment]
You should update to 9.0.5. It has been fixed by Hemario.

**Comment by Hemario** [comment]
Not completely, check out https://github.com/Sidoine/Ovale/pull/689/commits/1b3071a0e118580f8842e1da667c1da906701083 to fully fix for now

**Comment by brallinoth** [comment]
Thank you.  Signed off after it was updated,  but will check it out
