### ISSUE TITLE
9.0.13 - Abilities with modifiable power requirements no longer working correctly

### ISSUE THREAD

**Issue by Ophidon** [Sidoine/Ovale#706]
Since the changes made between 9.0.11 and 9.0.13, SpellRequire has changed and can no longer parse lines such as:

SpellRequire(death_coil runicpower 0=buff,sudden_doom_buff specialization=unholy) 

What this means is any ability for any spec (death coil mentioned above is just an example) that has non-constant power requirements no longer scripts correctly.

**Comment by Hemario** [comment]
The syntax for this line has changed to
`SpellRequire(death_coil runicpower set=0 enabled=(BuffPresent(sudden_doom_buff) and Specialization(unholy)))`

as quoted from @Sidoine: The syntax is "name of the spell" "property name" set/add/percent=value enabled=(condition)

**Comment by Sidoine** [comment]
Yes, I need to update the documentation
