### ISSUE TITLE
[9.0.19] BuffPresent() function no longer parses target parameter

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#715]
the sample code 

addicon
{
if mouseover.BuffPresent(<buffname>) spell(<spellname>)
} 

provides error message below

"type error parameter2 has not a valid in function buffpresent"

**Comment by ultijlam** [comment]
"mouseover" is not a valid target. Ovale doesn't track that unit ID.

**Comment by sirTribble** [comment]
Ovale tracked it perfectly in 9.0.11 and prior. its tracked all valid UnitIDs
for the sample you can use "player", or "party1-4" result will be the same

**Comment by ultijlam** [comment]
I agree that it is a bug for the other unit IDs you have mentioned, but not for "mouseover" since that has never been tracked by Ovale.

**Comment by ultijlam** [comment]
Oh I see, engine/guid.ts doesn't track it, but a script was still able to call with an arbitrary unit ID and query the WoW server for the GUID of the unit on each frame refresh.

**Comment by ultijlam** [comment]
@Sidoine How do you want to try to fix this one? The target check in states/conditions.ts restricts the allowed targets to a very small number of unit IDs (plus "cycle", which I haven't looked more closely at yet). Perhaps engine/guid.ts should export a VALID_UNITS table or an IsValidUnit() function that can be used instead?  The only unit IDs that engine/guid.ts doesn't currently track are "mouseover" and "nameplateNN" for NN from 1 to 20.

**Comment by sirTribble** [comment]
> Oh I see, engine/guid.ts doesn't track it, but a script was still able to call with an arbitrary unit ID and query the WoW server for the GUID of the unit on each frame refresh.

and my scripts actively use mouseover and other UnitID target parameters :) so I hope this functionality will be restored

**Comment by Sidoine** [comment]
I'll relax the parameter format
