### ISSUE TITLE
[9.0.19] name() function no longer parses target or name parameter (localized text) to compare

### ISSUE THREAD

**Issue by sirTribble** [Sidoine/Ovale#716]
sample code

AddFunction DungeonBosses
{
boss1.Name("Жрица Алун'за")
}

**Comment by ultijlam** [comment]
This is a duplicate of #715 and is caused by the same underlying reason.

**Comment by sirTribble** [comment]
name parameter not parsed as well.

**Comment by Sidoine** [comment]
You should use boss1.name() == "whatever"
