### ISSUE TITLE
Add condition Trait()

### ISSUE THREAD

**Issue by kevindesmet** [Sidoine/Ovale#72]
Add a condition for script Trait() that works the same way as Talent()
Should return the selected rank (with or without relic boost, possibly as a parameter).
Should also support the less, equal, more, ... syntax and return a boolean when using this syntax.

**Comment by kevindesmet** [comment]
example
```
actions+=/storm_earth_and_fire,if=artifact.strike_of_the_windlord.enabled&cooldown.strike_of_the_windlord.remains<14&cooldown.fists_of_fury.remains<=9&cooldown.rising_sun_kick.remains<=5
actions+=/storm_earth_and_fire,if=!artifact.strike_of_the_windlord.enabled&cooldown.fists_of_fury.remains<=9&cooldown.rising_sun_kick.remains<=5

```

**Comment by LunaEclipse73** [comment]
This already exists, there is two Artifact condition, HasArtifactTrait and ArtifactTraitRank.

**Comment by kevindesmet** [comment]
Indeed.
