### ISSUE TITLE
[9.0.19] Havoc DH showing "pickup" as main attack when idle

### ISSUE THREAD

**Issue by kaychriskay** [Sidoine/Ovale#722]
Hi

Not getting any LUA errors, but when standing idle and also sometimes during combat, Ovale is showing "pickup" as attack. Mouseover just showing:

> Main Attack
> texture Interface\Icons\spell_shadow_soulgem
> Click to hide/show options

All abilities are in the actionbar.

![Udklip222](https://user-images.githubusercontent.com/18907706/101269668-92e14100-3771-11eb-9eca-45d34e5df9fa.JPG)

**Comment by Sidoine** [comment]
Please test with the last version, it seems that I can't reproduce this bug.

**Comment by kaychriskay** [comment]
> Please test with the last version, it seems that I can't reproduce this bug.

Since recent update, I'm not getting this error anymore :-)
