### ISSUE TITLE
Unable to download update through CurseForge

### ISSUE THREAD

**Issue by RWexelblat** [Sidoine/Ovale#736]
When I click update it seems to start downloading but terminates with the message "An error has occurred. Please check your  connection and try again."

I have about a dozen addons, many of which have had recent updates but this is the only one that gives me this message. (I can download manually from the ovale website.)

**Comment by Sidoine** [comment]
Do somebody else have this problem?
I don't use the Curseforge client anymore but I don't see why it shouldn't work for this Addon.

**Comment by Guy5491** [comment]
i have the same problem since 9.0.20 and the same results i am on macOS Big Sur version 11.0.1

**Comment by Sidoine** [comment]
That's strange. I'll install the Curseforge client to test this. I use WoWUp if you want to test another client.

**Comment by HunterFearne** [comment]
Same here - unable to update or download it from Curseforge.  All other addons updating fine.

**Comment by RWexelblat** [comment]
Interesting. OSX refused to let me open WowUP saying it was not able to
check it for malicious software.

**Comment by Guy5491** [comment]
i suppose you have reason  i put big sur (macOS version 11.0.1) at the same time you realize 9.0.21 but all other add-on  accept to be updated, and i have 80 add-ons , only ovale don't accept very curious

**Comment by Guy5491** [comment]
i just try with wowup now,  and it is good ovale accept to be updated with your latest version you realize 4 hours ago version 9.0.26
sorry for my bad english

**Comment by Guy5491** [comment]
and for RWexelblat before open wowup click  on alt and then you will be able to open wow by clicking open in the menu

**Comment by ultijlam** [comment]
I can't reproduce this issue with the CurseForge client.

**Comment by jgleigh** [comment]
I'm having the same issue with the CurseForge client.

**Comment by Guy5491** [comment]
to day it is impossible to update ovale to 9.0.28 both on curse and Wowup

**Comment by jgleigh** [comment]
Still an issue with every new update.

**Comment by Guy5491** [comment]
i am oblige at every update to do it manualy from curse forge, its the same with wowup  sorry for sidoine but perhaps Big Sur (mac os) is very hard for security

**Comment by jgleigh** [comment]
I'm still running Catalina and this is the only addon that Curseforge has issues with updating.

**Comment by Sidoine** [comment]
It should be fixed in the next release

**Comment by Guy5491** [comment]
its the same for 9.02.34, always manually

**Comment by Sidoine** [comment]
Do you still have the bug? It should be solved.

**Comment by RWexelblat** [comment]
It's working now. Thanks

**Comment by Guy5491** [comment]
it's working also but don't forget to update curse forge app.
thanks Sidoine

**Comment by jgleigh** [comment]
Working now.
