### ISSUE TITLE
Ovale Demands I Use BFA Necklace

### ISSUE THREAD

**Issue by Khanzilla** [Sidoine/Ovale#744]
Installed the latest version of Ovale this evening and it worked just fine until I made the mistake of clicking one of the script options (all defaults). Ovale immediately changed next actions for both single and multi-target to use my Heart of Azeroth necklace ability, which I am no longer wearing.

I have tried selecting any of the other script options and no change.
I have deleted and reinstalled Ovale a few times and cannot get it back to a functioning state.
No matter what abilities I use, Ovale still insists that I need to use the Heart ability as my next action.

**Comment by Sidoine** [comment]
What are the class and spec of your character?

**Comment by DeeRez** [comment]
This is happening to me on my Prot Paladin.

**Comment by ultijlam** [comment]
When the Heart of Azeroth necklace icon is being shown, if you mouse over the icon, what spell does it say that it is suggesting?

**Comment by Sidoine** [comment]
T26 scripts doesn't reference HoA anymore

**Comment by Hemario** [comment]
Just a reminder Ovale TankScripts exists https://www.curseforge.com/wow/addons/ovale_tankscripts
