### ISSUE TITLE
Ovale 9.9.26 dont works with spellflash. 9.0.24 yes, 9.0.25 no and 9.0.26 no.

### ISSUE THREAD

**Issue by fameneiros** [Sidoine/Ovale#747]
**Describe the bug**

**To Reproduce**
1. Select the script...
2. Cast XXX spell...
3. See error

**Expected behavior**

**Screenshots**

**Class, specialization and  level**
 - Class: [e.g. priest]
 - Specialization: [e.g. shadow, discipline]
 - Level [e.g. 50]

**Additional context**

**Comment by Sidoine** [comment]
It isn't a bug. SpellFlashCore support has been dropped in favor of LibButtonGlow, because it hasn't been updated for Shadowland.

**Comment by fameneiros** [comment]
I have installed the latest version of ovale. And the libbuttonglow. I am unable to make it work. Is there anything else to do besides installing the two addons?

**Comment by Sidoine** [comment]
It should work as this, and you shouldn't need to install libbuttonglow. It seems that there are issues with libbuttonglow, we should migrate to another library.
