### ISSUE TITLE
Flashing Spells using LibButtonGlow does not work with ElvUI

### ISSUE THREAD

**Issue by Chorthee** [Sidoine/Ovale#758]
**Describe the bug**
Flashing spells does not work with ElvUI, it does work with Blizzard action bars

**To Reproduce**
1. Select the script...
2. Cast XXX spell...
3. See error

**Expected behavior**
Spells on action bars 'glow' when appropriate to use.

**Screenshots**

**Class, specialization and  level**
 - Class: [e.g. priest]
 - Specialization: [e.g. shadow, discipline]
 - Level [e.g. 50]
Tested on multiple Level 50 and 60 toons.

**Additional context**

**Comment by radix-pro** [comment]
Somebody write instructions how to return original SpellFlash pls :((

**Comment by Sidoine** [comment]
Duplicates #747
