### ISSUE TITLE
Ovale wanting me to use Heart of Azeroth

### ISSUE THREAD

**Issue by DeeRez** [Sidoine/Ovale#763]
Ovale wants me to use the Heart of Azeroth when in combat.

1: Select default script

2: Enter combat

3: Ovale suggests to use HoA and doesn't progress further.

I would expect Ovale to follow the spell priority in the default script.

[1](https://i.imgur.com/0M4N2Sb.png)

[2](https://i.imgur.com/phoqC5H.png)

Class: Paladin
Specialization: Protection
Level 60

Using Ovale 9.0.31.

**Comment by Hemario** [comment]
Friendly reminder that https://www.curseforge.com/wow/addons/ovale_tankscripts exists for all your tanking needs

**Comment by ricodrknight** [comment]
As well on my Frost DK spec
