### ISSUE TITLE
Feral druid - ovale not working proberly

### ISSUE THREAD

**Issue by Itsawunder** [Sidoine/Ovale#777]
**Describe the bug**
I have tried everything but oval does not work properly (Feral Druid). After a few seconds in combat, the icon group only shows prowl (or once in between Sunfire). I do not use the owlweave script. It also seems that there are problems with spellflash. See attached photos.

Using Script: 9,0 simultationcraft T26 druid feral
Have tried Oval with Spellflash installed and without - same problem.
UI = Elvui

**Screenshots** (from training dummy)

![image](https://user-images.githubusercontent.com/76726038/103268510-ce0f1280-49b3-11eb-97da-71afb1ce95ce.png)

![image](https://user-images.githubusercontent.com/76726038/103268545-e2530f80-49b3-11eb-9933-33723ae4cec1.png)

**Class, specialization and  level**
 - Night elf druid
 - Specialization: Feral
 - Level 60

**Additional context**

Hope you can help with my problem :-)

**Comment by ultijlam** [comment]
Just wanted to note that I'm currently working on this issue. I have a simple fix for Prowl, but in my testing of the default script, it seems to not be maintaining Rake and Rip on the target, so I'm investigating that as well.

**Comment by ultijlam** [comment]
@Sidoine So, by my reading of the T26 feral druid profile, the APL is currently broken. It suggests several moonkin-related spells without properly checking for the correct owlweave talents and conditions. I don't actually see how to fix that in the scripts without major headaches. I can try modifying the importer to filter out the owlweave actions for the plain non-Owlweave feral profile, or we can make our own feral profile and import a script from that instead.

**Comment by ultijlam** [comment]
The way I did it back when I wrote the importer was I had  a vendor branch where I imported the SimulationCraft profiles and then made version-controlled changes to the profiles in the master branch. When new profiles were released, I imported the new profiles onto the vendor branch then just did a merge from the vendor branch into master to preserve local modifications.  The reason I did it that way was because the unmodified profiles from SimulationCraft are not always suited for Ovale scripts and this allowed me to make small, versioned changes to fix them.

**Comment by ultijlam** [comment]
Ovale also needs to properly implement `TicksGainedOnRefresh()` or else the feral script will always ignore putting up Rake and Rip.

**Comment by ultijlam** [comment]
I have made some progress on this issue by implementing `TicksGainedOnRefresh()`, but now the default feral script is suggesting only Rake and Rip. More investigation is needed.

**Comment by ultijlam** [comment]
I've fixed a lot of the issues for feral druid in my local repository. The script is currently suggest Primal Wrath as the only finisher, but that's a problem with how `druid.primal_wrath.ticks_gained_on_refresh` is current translated. I am still working on a good patch for this.

**Comment by ultijlam** [comment]
This should be fixed in the latest Ovale release >= 9.0.35. thanks for all of the great information and screenshots to help with analyzing this problem!
