### ISSUE TITLE
Version 7.0.16.0 login error

### ISSUE THREAD

**Issue by kalgarath** [Sidoine/Ovale#78]
I am getting this error code at login since the update. 

Date: 2016-09-01 19:58:33
ID: 2
Error occured in: Global
Count: 664
Message: ..\AddOns\Ovale\Power.lua line 378:
   attempt to concatenate local 'powerType' (a boolean value)
Debug:
   Ovale\Power.lua:378: PowerCost()
   Ovale\Power.lua:715: TimeToPower()
   Ovale\SpellBook.lua:514: GetTimeToSpell()
   Ovale\BestAction.lua:269:
      Ovale\BestAction.lua:209
   (tail call): ?
   Ovale\BestAction.lua:520: ?()
   Ovale\BestAction.lua:480: RecursiveCompute()
   Ovale\BestAction.lua:459: PostOrderCompute()
   Ovale\BestAction.lua:420: Compute()
   Ovale\BestAction.lua:812: ?()
   Ovale\BestAction.lua:480: RecursiveCompute()
   Ovale\BestAction.lua:459: PostOrderCompute()
   Ovale\BestAction.lua:420: Compute()
   Ovale\BestAction.lua:396: GetAction()
   Ovale\Frame.lua:212: OnUpdate()
   Ovale\Frame.lua:89:
      Ovale\Frame.lua:88
Locals:
self = <table> {
 IsStance = <function> defined @Interface\AddOns\Ovale\Stance.lua:182
 DebugUnitAuras = <function> defined @Interface\AddOns\Ovale\Aura.lua:1242
 class = "DEMONHUNTER"
 ApplySpellAuras = <function> defined @Interface\AddOns\Ovale\Aura.lua:1297
 UpdateCounters = <function> defined @Interface\AddOns\Ovale\Future.lua:949
 taggedEnemies = 0
 lastEnable = <table> {
 }
 level = 100
 specialization = 1
 counter = <table> {
 }
 spellHaste = 19.150009155273
 GetStateDuration = <function> defined @Interface\AddOns\Ovale\State.lua:179
 nextCast = 4858.817
 combatStartTime = 0
 currentTime = 4858.817
 GetSpellCharges = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:517
 isInitialized = true
 multistrike = 0
 GetCD = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:419
 RequireCooldownHandler = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:249
 pain = 0
 DebugPower = <function> defined @Interface\AddOns\Ovale\Power.lua:742
 serial = 4
 IsActiveAura = <function> defined @Interface\AddOns\Ovale\Aura.lua:1273
 activeEnemies = 0
 Log = <function> defined @Interface\AddOns\Ovale\State.lua:205
 RequireStanceHandler = <function> defined @Interface\AddOns\Ovale\Stance.lua:218
 futureLastEnable = <table> {
 }
 futureVariable = <table> {
 }
 stance = 0
 multistrikeRating = 0
 powerRate = <table> {
 }
 IsUsableSpell = <function> defined @Interface\AddOns\Ovale\SpellBook.lua:453
 agility = 5662
 GetGCD = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:366
 focus = 0
 combopoints = 0
 alternate = 0
 spellBonusDamage = 711
 energy = 0
 rangedCrit = 30.890909194946
 runicpower = 0
 soulshards = 0
 GetSpellHasteMultiplier = <function> defined @Interface\AddOns\Ovale\PaperDoll.lua:479
 GetMeleeHasteMultiplier = <function> defined @Interface\AddOns\Ovale\PaperDoll.lua:467
 GetSpellCooldown = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:474
 RemoveAuraOnGUID = <function> defined @Interface\AddOns\Ovale\Aura.lua:1536
 GetSpellCooldownDuration = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:481
 GetPower = <function> defined @Interface\AddOns\Ovale\Power.lua:356
 spellCrit = 30.890909194946
 GetMasteryMultiplier = <function> defined @Interface\AddOns\Ovale\PaperDoll.lua:461
 arcanecharges = 0
 maelstrom = 0
 CheckSpellInfo = <function> defined @Interface\AddOns\Ovale\Data.lua:458
 chi = 0
 mainHandWeaponDamage = 0
 insanity = 0
 strength = 1207
 fury = 0
 ApplySpell = <function> defined @Interface\AddOns\Ovale\Future.lua:1332
 critRating = 1638
 PowerCost = <function> defined @Interface\AddOns\Ovale\Power.lua:376
 GetSpellInfoProperty = <function> defined @Interface\AddOns\Ovale\Data.lua:480
 astralpower = 0
 TimeToPower = <function> defined @Interface\AddOns\Ovale\Power.lua:711
 GetRangedHasteMultiplier = <function> defined @Interface\AddOns\Ovale\PaperDoll.lua:473
 aura = <table> {
 }
 holy = 0
 rage = 0
 baseDamageMultiplier = 1
 masteryEffect = 20.200000762939
 GetDamageMultiplier = <function> defined @Interface\AddOns\Ovale\Future.lua:897
 IsChanneling = <function> defined @Interface\AddOns\Ovale\Future.lua:1313
 offHandWeaponDamage = 0
 ApplyCooldown = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:323
 DebugCooldown = <function> defined @Interface\AddOns\Ovale\Cooldown.lua:351
 spellBonusHealing = 711
 hasteRating = 1915
 GetCounterValue = <function> defined @Interface\AddOns\Ovale\Future.lua:1301
 RequirePowerHandler = <function> defined @Interface\AddOns\Ovale\Power.lua:483
 AddAuraToGUID = <function> defined @Interface\AddOns\Ovale\Aura.lua:1517
 meleeHaste = 19.150009155273
 Initialize = <function> defined @Interface\AddOns\Ovale\State.lua:159
 stamina = 4834
 meleeCrit = 30.890909194946
 GetAuraWithProperty = <function> defined @Interface\AddOns\Ovale\Aura.lua:1560
 CheckSpellAuraData = <function> defined @Interface\AddOns\Ovale\Data.lua:410
 intellect = 711
 PutState = <function> defined @Interface\AddOns\Ovale\State.lua:185
 TimeOfLastCast = <function> defined @Interface\AddOns\Ovale\Future.lua:1308
 CanApplySpellAura = <function> defined @Interface\AddOns\Ova
AddOns:
  KalielsTracker, v2.0.6
  Swatter, v7.0.5664 (TasmanianThylacine)
  NPCScan, v7.0.3.7
  NPCScanOverlay, v7.0.3.4
  acbCastBar, v16.07.23
  acbMirror, v16.07.23
  AckisRecipeList, v7.0.3.7
  AckisRecipeListQuickScan, v7.0.3.3
  Altoholic, vr171
  Arh, v1.6.2
  Armory, vv13.1.0
  ArmoryGuildBank, vv13.1.0
  Atlas, v1.34.00
  AtlasBattlegrounds, v1.34.00
  AtlasBurningCrusade, v1.33.00
  AtlasCataclysm, v1.33.00
  AtlasClassicWoW, v1.33.01
  AtlasClassOrderHalls, v1.34.00
  AtlasDungeonLocs, v1.34.00
  AtlasLegion, v1.34.00
  AtlasMistsofPandaria, v1.33.00
  AtlasOutdoorRaids, v1.34.00
  AtlasScenarios, v1.34.00
  AtlasTransportation, v1.34.00
  AtlasWarlordsofDraenor, v1.33.03
  AtlasWorldEvents, v3.15
  AtlasWrathoftheLichKing, v1.33.02
  AtlasMajorCitiesEnhanced, vv1.08
  AucAdvanced, v7.0.5664 (TasmanianThylacine)
  AucFilterBasic, v7.0.5664 (TasmanianThylacine)
  AucFilterOutlier, v7.0.5664.5459(7.0/embedded)
  AucMatchUndercut, v7.0.5664.5585(7.0/embedded)
  AucStatHistogram, v7.0.5664 (TasmanianThylacine)
  AucStatiLevel, v7.0.5664 (TasmanianThylacine)
  AucStatPurchased, v7.0.5664 (TasmanianThylacine)
  AucStatSales, v7.0.5664.5598(7.0/embedded)
  AucStatSimple, v7.0.5664 (TasmanianThylacine)
  AucStatStdDev, v7.0.5664 (TasmanianThylacine)
  AucStatWOWEcon, v7.0.5664.5613(7.0/embedded)
  AucUtilAHWindowControl, v7.0.5664.5575(7.0/embedded)
  AucUtilAppraiser, v7.0.5664.5653(7.0/embedded)
  AucUtilAskPrice, v7.0.5664.5599(7.0/embedded)
  AucUtilAutoMagic, v7.0.5664.5587(7.0/embedded)
  AucUtilCompactUI, v7.0.5664.5629(7.0/embedded)
  AucUtilEasyBuyout, v7.0.5664.5576(7.0/embedded)
  AucUtilFixAH, v7.0.5664 (TasmanianThylacine)
  AucUtilItemSuggest, v7.0.5664.5651(7.0/embedded)
  AucUtilPriceLevel, v7.0.5664.5633(7.0/embedded)
  AucUtilScanButton, v7.0.5664.5631(7.0/embedded)
  AucUtilScanFinish, v7.0.5664.5588(7.0/embedded)
  AucUtilScanProgress, v7.0.5664.4979(7.0/embedded)
  AucUtilScanStart, v7.0.5664.5347(7.0/embedded)
  AucUtilSearchUI, v7.0.5664.5657(7.0/embedded)
  AucUtilSimpleAuction, v7.0.5664.5654(7.0/embedded)
  AucUtilVendMarkup, v7.0.5664.4828(7.0/embedded)
  AzCastBar, v16.07.23
  Babylonian, v5.1.DEV.332(/embedded)
  Bartender4, v4.7.2
  BattlePetCount, v1.8.10
  BeanCounter, v7.0.5664 (TasmanianThylacine)
  BrokerEverything, v2.17-Release
  ChocolateBar, vv3.0.2
  Collectinator, v7.0.3.2
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DressUp, v2.1.5
  DropTheCheapestThing, vv70000.2
  FactionAddict, v1.35
  FlightMapEnhanced, v1.9.3
  Grail, v080
  GrailAchievements, v011
  GrailReputations, v007
  Informant, v7.0.5664 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.409(/embedded)
  Mapster, v1.7.2
  MBB, v
  MikScrollingBattleText, v5.7.146
  MountHelper, v1b1
  MountJournalEnhanced, v1.3.4
  OmniCC, v7.0.1
  Ovale, v7.0.16.0
  Pawn, v2.0.8b
  PerCharacterFavoriteMounts, v1.4
  PetBattleTeams, v3.3.0
  PetJournalEnhanced, v2.9.18
  PetTracker, v7.0.1
  PetTrackerBreeds, v
  PetTrackerBroker, v
  PetTrackerConfig, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  PokemonTrainer, v7.0.1
  Postal, vv3.5.8
  Prat30, v3.6.14      
  Prat30Libraries, v
  ProfessionsComplete, v1.5
  Rarity, v1.0
  RarityOptions, v
  Rematch, v4.5.2
  SavedInstances, v7.0.2
  Scrap, v13.3
  ScrapSpotlight, v13.3
  SexyMap, v2.4.29
  SkillHelper, vv3.2.15
  SnowfallCursor, v
  Stubby, v7.0.5664 (TasmanianThylacine)
  TinyDPS, v0.942
  TipHelper, v5.12.DEV.405(/embedded)
  TipTac, v16.08.30
  TipTacItemRef, v16.08.30
  TipTacTalents, v16.07.21
  TomTom, vv70000-1.1.0
  TransmogTokens, v1.4.4
  Wholly, v057
  WorldQuestsList, v17
  ZPerl, v5.0.8
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=1112)

**Comment by UFTimmy** [comment]
I am getting this message, as well. It happens several times per second, the count has increased to over 1200 just by typing this message.

**Comment by tivec** [comment]
This is happening to me on login with my paladin. If I reload my UI, it sorts itself out.
