### ISSUE TITLE
Error - Lua with ElvUI

### ISSUE THREAD

**Issue by Miaou75** [Sidoine/Ovale#780]
Hi guys,

I use latest version of Ovale + Ovale_TankScripts and ElvUi.

Each time I mouse over the skill at the end right of the bar I face the following error message:

---
Message: Interface\AddOns\Ovale\ui/Icon.lua:287: Usage: GameTooltip:SetText("text" [, color, wrap])
Time: Wed Dec 30 14:28:18 2020
Count: 6
Stack: Interface\AddOns\Ovale\ui/Icon.lua:287: Usage: GameTooltip:SetText("text" [, color, wrap])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetText'
[string "@Interface\AddOns\Ovale\ui/Icon.lua"]:287: in function <Interface\AddOns\Ovale\ui/Icon.lua:283>
[string "=(tail call)"]: ?

Locals

---

Please see screenshot attached.

I tried reinstalling ElvUI and Ovale, the issue still occurs.

What should I do ?

Thanks for your help.

![Error Message](https://user-images.githubusercontent.com/6953735/103354439-d5194c00-4aab-11eb-8644-2ef5fa66b629.png)

Best regards,
Miaou

**Comment by ultijlam** [comment]
At a glance, this looks like a bug in `ui/Icon.ts` in calling `SetText()` with an undefined first argument.

**Comment by Hemario** [comment]
As a workaround to not have this error popping up all the time (until the bug is fixed) you could enable the "ignore mouse clicks" option in Ovale settings. 

![image](https://user-images.githubusercontent.com/14911473/103370594-7a90e780-4acd-11eb-8c75-f9deaa20b219.png)

**Comment by Hemario** [comment]
@Miaou75 Turns out this was an issue with Ovale TankScripts, version 902.39 should fix this issue.
