### ISSUE TITLE
Feral Savage Roar displaying intermittently v7.0.16.0

### ISSUE THREAD

**Issue by Arthaei** [Sidoine/Ovale#79]
Hi, I've noticed savage roar suggestions seem to be favouring 5 combo points, is this intentional? sometimes it appears to not suggest it at all, not even with 1 cp and it not being up.

**Comment by ShmooDude** [comment]
Yes, it's intentional.  With BT, it's not worth it to SR with less than 5 CPs _except_ on the pull.  Though that last part isn't in the simcraft action list yet (and thus won't be suggested by Ovale).

Not sure about non-BT builds but I think it was neutral on them when I tested it.
