### ISSUE TITLE
Guardian Druid rotation includes non-guardian spells

### ISSUE THREAD

**Issue by zombiektn** [Sidoine/Ovale#792]
It keeps telling me to cast Wrath (a balance ability) or constantly go to feral form. Neither of these should even be used in guardian spec.....

**Comment by ultijlam** [comment]
I think you will need to uncheck the options for `owlweave_bear` and `catweave_bear`. The default scripts assume you want these and will suggest these more advanced rotations.

**Comment by ultijlam** [comment]
I think this can be closed. I believe this was answered in more detail on the Discord server.
