### ISSUE TITLE
S Priest VT spam

### ISSUE THREAD

**Issue by Msthea** [Sidoine/Ovale#809]
**Describe the bug**
At start of boss fight, I cast VT
It keeps telling me to recast VT even though it's already on target with long time left!
I see at times, DP is available and not on target and it still wants me to cast VT.
Less often. but way too much, MB is off CD and not preferred spell cast.

**Expected behavior**
Better priority on spell casts. It's odd if DoTs are OK, it wants recast even if higher priority spells are available.

**Screenshots**

**Class, specialization and  level**
 - Class: [priest]
 - Specialization: [shadow]
 - Level [e.g. 50]

**Additional context**

**Comment by Sidoine** [comment]
I don't have this bug, could you share your talents please? Do you have the bug if you take all the talents from the middle column?

**Comment by Msthea** [comment]
Interesting solution. All middle talents??

Mine are
3
1
2
3
1
2
2


Will try run Timewalking with all middle.

**Comment by Msthea** [comment]
I switched to all middle. Then back. Seems to be doing better. However, it does suggest VT Before it's low tick count and/or ignore casting DP when it;s available.

As a note, for some reason, it suggests DP as I cast VT at begining of fight and I don't have insanity! But this is ONLY during the VT cast.  I know it's not available and hit MB just as cast finishes and it disappears at that moment. Just odd.

It's not been spam suggesting VT after playing all middle then reverting.
Thanks,
