### ISSUE TITLE
Options broken

### ISSUE THREAD

**Issue by radix-pro** [Sidoine/Ovale#810]
Options broken / not visible in 9.0.38 .. 9.0.40

tried with all addon disabled, WTF folder deleted - no success

![opt](https://user-images.githubusercontent.com/4878976/104794583-a2649880-57b9-11eb-93db-cb2f772bd9e6.png)

**Comment by ultijlam** [comment]
This is the options panel that should display when left-clicking on the Ovale icon bar. I can confirm that it does not show correctly.
