### ISSUE TITLE
Start using T19P profiles

### ISSUE THREAD

**Issue by kevindesmet** [Sidoine/Ovale#85]
https://simulationcraft.org/ starts using T19P profiles for measuring. They are becoming "stable" enough to start implementing them in Ovale.

**Comment by tigew** [comment]
Still a bit of work to do before Ovale is completely compatible.

**Comment by kevindesmet** [comment]
I'm well aware ;)

**Comment by Sidoine** [comment]
As soon as I come back from vacation, I work on this :)

**Comment by kevindesmet** [comment]
Recuperate to get to full strength @Sidoine! We need you ;)
