### ISSUE TITLE
Ret Pally default indicator now GBoM

### ISSUE THREAD

**Issue by Brdrker** [Sidoine/Ovale#89]
Running 17.0.17.0: Ret Pally icon, when out of combat, now requests I cast Greater Blessing of Might, even when it was cast recently. As battle starts, this changes to the appropriate icon.

**Comment by roncli** [comment]
Corrected by modifying the following two functions:

```
AddFunction RetributionPrecombatMainActions
{
    #flask,type=greater_draenic_strength_flask
    #food,type=sleeper_sushi
    #greater_blessing_of_might
    if RetributionPrecombatMainPostConditions() { Spell(greater_blessing_of_might) }
}

AddFunction RetributionPrecombatMainPostConditions
{
    not BuffPresent(greater_blessing_of_might) or BuffRemaining(greater_blessing_of_might) < 120
}
```

**Comment by roncli** [comment]
@Sidoine I did not see this committed in the code, was this fixed another way?
