### ISSUE TITLE
Retribution "Crusade"-off cooldown issue

### ISSUE THREAD

**Issue by Valodec** [Sidoine/Ovale#93]
When playing Retribution Paladin and picking lvl100 Talent "Crusade", Ovale only suggests Crusaderstrike and Blade of Justice in the Rotation, then waiting for Judgement cooldown to recast it. This occurs while Crusade is available. If Crusade is active or on cooldown, the rotation shows just perfect with Templars Verdict and Divine Storm in it.
Can i fix this myself or can you help out in a future Update? 
thx <3

**Comment by roncli** [comment]
The script is designed to hold those spells in order to get the maximum value out of your holy power spenders while Crusade is active.  Therefore, you should cast Crusade on cooldown, and then the issue solves itself. :)

**Comment by Valodec** [comment]
Yeah that makes sense partially. But often there are situations where my cooldown is better stacked with others as bloodlust e.g.
in terms of a solo simulation, casting crusade on cooldown makes perfect sense but while playing in group i would strongly prefer picking the right time to cast crusade myself. wouldn't that be better?
thx for your time :)

**Comment by Sidoine** [comment]
Yes, you're right. The character that I play (casually) is a ret pal and I have the same problem, it bothers me, but it's as the simulationcraft script is written. I need to work on a fix :)
