### ISSUE TITLE
Fire Mage 7.0.3 - Spellflash Not Showing All Pyroblasts

### ISSUE THREAD

**Issue by warcraftrealist** [Sidoine/Ovale#96]
I've notice Ovale is not showing certain instant pyroblasts procs in the default script. The button option does work (showing to cast pyroblast during instant procs), but pyroblast does not blink using spellflash integration.

**Comment by warcraftrealist** [comment]
Still observing this behavior in Ovale as of the latest update -

**Comment by Sidoine** [comment]
I can't reproduce this bug. Is the key binding displayed on the Ovale icon?

**Comment by warcraftrealist** [comment]
Previously, pyroblast! would be proccing and Ovale not showing it with the spellflash option, but it would be there on the icon. 

However, I just tried it again now on the mage alt I use and I don't see it happening anymore. Looks like one of the updates in the past few weeks fixed it.
