### ISSUE TITLE
Blood DK - No Option to turn off Multiple Targets

### ISSUE THREAD

**Issue by solidslush** [Sidoine/Ovale#97]
When using Blood DK, there is no option to uncheck multiple target.  The option exists for Frost and Unholy, but the setting does not carry over to Blood.

**Comment by solidslush** [comment]
Vengeance DH is the same, FYI.  Seems to be a tank thing, Haven't checked my Bear Tank.

**Comment by kevindesmet** [comment]
Yes, those are the scripts I contributed as they don't exist in simcraft T18.
Protection Paladin will also show this behavior.

Guardian Druid, Protection Warrior and BrewMaster don't have any scripts defined so they won't have the issue :)
