### ISSUE TITLE
Default Script (Disabled)

### ISSUE THREAD

**Issue by c69jay** [Sidoine/Ovale#98]
I am not getting any error messages, and Ovale is enabled in my addons list. When i go to select which script to use, i get 3 options, Default Script (Disabled), Disabled and Custom Script. I have no custom scripts installed, and i have uninstalled and reinstalled the addon. I have also installed the LibStub just to make sure that's not what was causing it. Any help is appreciated. Thanks.

**Comment by kevindesmet** [comment]
@c69jay  which version of Ovale are you using?

**Comment by c69jay** [comment]
It's version 7.0.17.0

**Comment by c69jay** [comment]
@kevindesmet If it helps it's the same on my resto druid and my resto shaman, so i'm thinking there's a clash with another plugin. i will try and disable all others and start turning them on one by one to see which one it is clashing with.

**Comment by c69jay** [comment]
So i disabled everything, except Ovale, same thing, Default Script (Disabled), uninstalled and reinstalled, same thing. Not sure what's going on.

**Comment by Sidoine** [comment]
The scripts for resto druid an shaman have not been written. Do not hesitate to contribute them.

**Comment by c69jay** [comment]
Thank you!! That makes a ton more sense!
